### ISSUE TITLE
Needs a real license

### ISSUE THREAD

**Issue by ablwr** [mipops/dvrescue#10]
Right now we have "The Unlicense" listed as the license for this project, but now that the project has released its first beta release, we should consider a standard license.

**Comment by JeromeMartinez** [comment]
I thought it was wanted.
Unlicense is a standard license and relevant.  Else bsd 2-clause?

**Comment by ablwr** [comment]
I put it up there temporarily until we were in a closer state of release. That's fine with me. If we can get someone from MIPoPS to confirm, I can make the change.

**Comment by dericed** [comment]
@ablwr resolved?

**Comment by ablwr** [comment]
Closed via #19
