### ISSUE TITLE
add attributes to //media

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#114]
add `media/@count` attribute.
should be a tally of `frames/@count`.

add `media/@size` attribute
filesize in bytes

add `media/@format`(copy of MediaInfo:Format)

add `frame/@pkt_pos`
remove `frames/@pkt_pos` (since it equals `frames/frame[1]/@pkt_pos`)

**Comment by JeromeMartinez** [comment]
> add media/@count attribute.
should be a tally of frames/@count.

"count" alone at this place is difficult to understand without the XSD definition (count of what?).
--> I prefer "framecount" (and I add it only for DV content, so it is about video or audio frame count, they are together

**Comment by dericed** [comment]
Actually I don't think I need media/@count any longer, but do need the others.
