### ISSUE TITLE
avfctl: add option to produce dvrescue outputs concurrent with capture

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#119]
Such as
`avfctl -cmd capture out.dv -x out_dvrescue.xml -s out_dvrescue.vtt -c out_dvrescue.scc`

**Comment by JeromeMartinez** [comment]
in practice avfctl features would be merged in dvrescue.
Such as
`avfctl -capture -raw out.dv -x out_dvrescue.xml -s out_dvrescue.vtt -c out_dvrescue.scc`

**Comment by dericed** [comment]
Hi @JeromeMartinez, this is working in practice but only with some exit options. 

For instance, when I run
`avfctl -cmd capture - | dvrescue - --merge-log out3.log -v 7 -x out3.xml -s out3.vtt -m out3.dv`

Then the out3.dv is written during capture. If I stop the deck, which stops avfctl and then dvrescue, then the xml and vtt are okay. But if I run that command and then stop with Control-C, then the xml and vtt are empty. Can stop signals be caught to finish the xml and vtt (and scc too) outputs before stopping?

**Comment by dericed** [comment]
Updating with daily build 20211031. Now the xml, vtt, and scc are made in dvrescue which can capture from the device directly (perahps only the first device?). However, on Control-C, the xml, vtt, and optional scc are empty. cc @JeromeMartinez 

```
% dvrescue device://0 --verbosity 7 --timeout 9 -x test.dv.dvrescue.xml -s test.dv.dvrescue.vtt -c test.dv.dvrescue.scc -m test.dv
DVRescue v.0.20.11.20211031 (MediaInfoLib v.21.09) by MIPoPS

# TC Used Status Comments
#:        the frame number (0-based)
SS;FF:      the time code, if unique accross all files, SS;FF format
S:        the file number (0-based) selected as the reference (non A/V blocks are taken from it), "X" if from several frames

Status:   the status of the frame, 1 char per file
              = Fine
            T = Time code is missing
            P = Frame has problem
            M = Frame is missing

Comments: comments about the issues found
              --> Nothing displayed
            T --> List of time codes, "??:??" if no time code found
            P --> List of count of blocks picked per file, 1 number per file + count of blocks remaining with errors
            M --> Nothing displayed

File 0: device://0

     #|Abst  |HH:MM:SS:FF|U|S|Comments
^C  40 00:01:45;23 00:01:45;23
```

**Comment by dericed** [comment]
Testing latest dev build. When I control-C to stop capture the output is not frame-aligned. CC @JeromeMartinez 

```
davidrice@iMac build % dvrescue --version
DVRescue v.0.21.11.20211225 (MediaInfoLib v.21.09) by MIPoPS.
davidrice@iMac build % dvrescue device://1 -m out.dv      
DVRescue v.0.21.11.20211225 (MediaInfoLib v.21.09) by MIPoPS
^C 150 00:48:21;28 00:48:21;282
davidrice@iMac build % ls -l out.dv 
-rw-r--r--  1 davidrice  staff  17997824 Jan  4 12:03 out.dv
```

Is there a preferred way to stop the capture? Could dvrescue listen to stdin for a 'q'?

**Comment by JeromeMartinez** [comment]
> Is there a preferred way to stop the capture? Could dvrescue listen to stdin for a 'q'?

Ctrl-C is fine, it should be aligned because we catch the corresponding system event.

**Comment by dericed** [comment]
resolved. :)
