### ISSUE TITLE
draft prototypes of an eventual dvrescue gui

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#121]
via the functions of dvrescue, avfctl, dvplay I can we can envision what an eventual gui looks like. There's some related project ui's like Live Capture Plus, Premiere, FCP, AVCVHSCap. Also considering that we can make use of dvrescue xml data during transfer so could have like a qctools-like error timelines.

**Comment by ablwr** [comment]
Do you know what frameworks are going to be used to build this GUI?

**Comment by JeromeMartinez** [comment]
> Do you know what frameworks are going to be used to build this GUI?

Qt.

**Comment by ablwr** [comment]
I did this mockup in plain HTML with some CSS. @dericed can you give this an initial review before we get feedback during the upcoming workshop? http://bits.ashleyblewer.com/dvrescue-gui-mockups/

There are a lot of things I'm still uncertain about in terms of the features that will be available, so I imagine the Settings page will become more complicated as we discuss things like acceptable error threshold, etc.

**Comment by dericed** [comment]
![dvrescue](https://user-images.githubusercontent.com/762604/89227190-31cf1400-d5ab-11ea-8ec3-8630daa6013e.jpeg)

**Comment by dericed** [comment]
![dvrescue](https://user-images.githubusercontent.com/762604/89227790-511a7100-d5ac-11ea-9e84-8a408db22188.jpeg)

**Comment by dericed** [comment]
![dvrescue](https://user-images.githubusercontent.com/762604/89228045-ddc52f00-d5ac-11ea-9f11-925493636ed8.jpeg)

**Comment by libbyhopfauf** [comment]
> I did this mockup in plain HTML with some CSS. @dericed can you give this an initial review before we get feedback during the upcoming workshop? http://bits.ashleyblewer.com/dvrescue-gui-mockups/
> 
> There are a lot of things I'm still uncertain about in terms of the features that will be available, so I imagine the Settings page will become more complicated as we discuss things like acceptable error threshold, etc.

Hey Ashley, I think this is looking great! The only thing that I just remembered as I was writing the NEH report is that we need to make sure that they are sited EVERYWHERE as funding the project with their logo if possible. Would there be a way to just have a line at the bottom that has their preferred quoted "This {database, Web resource, etc.} has been made possible in part by the National Endowment for the Humanities: Exploring the human endeavor" and a tiny logo?

https://www.neh.gov/grants/manage/acknowledgment-and-publicity-requirements-neh-awards

**Comment by ablwr** [comment]
Thanks @dericed for the graphs. I updated the GUI mockups to go a bit farther and include packaging.

I'm not sure if Analysis and Package should be separate or just one view. It depends on what other Analysis things are going to be incorporated into DVRescue.

http://bits.ashleyblewer.com/dvrescue-gui-mockups/

**Comment by ablwr** [comment]
@JeromeMartinez For interface mockups, do you prefer that I make a static outlined version (like I am doing currently) and you can recreate in Qt, or do you plan on using some of the HTML/CSS (like with MediaConch WebUI + GUI)? I guess what I am asking is if I should make the mockups with, like, "good CSS" (stretchy, scalable, fits on any size screen) that can be applied to the initial GUI, or if it will just be throwaway and I shouldn't focus on that?

**Comment by ablwr** [comment]
hi @JeromeMartinez

**Comment by JeromeMartinez** [comment]
@ablwr for the moment I have enough, just late... :(

**Comment by ablwr** [comment]
OK no problem! Just wondering about the question I asked in my last comment and if you have an opinion on that.

**Comment by dericed** [comment]
closing as the progress has progressed substantially since this thread's discussion. I'll divide up new gui issues and discussions at a more granular level.
