### ISSUE TITLE
label frames that do not contain any unique information

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#123]
Related to the sample at https://github.com/mipops/dvrescue/issues/122, frame 2-9 have every dif block as error or empty (here the subcode are vaux have no packs, the audio is all error code, and the video is all concealment of the prior frame. I think in this case, it's worth simply giving the frame some flag as this type of output reflects a deck behavior rather than a tape issue. In the case of capture or packaging, it may be worthwhile to completely discard these frames.

I'm unsure what the best label for this type of frame is, maybe `<frame faux="1" ...`

These frames came from a transfer by @iamdamosuzuki, the corresponding portion of tape plays as black video and silent audio at that part.

**Comment by dericed** [comment]
Also here suggest an additional attribute if the frame contains no  AAUX source pack. `<frame no-aaux-pack="1" ...`. If these cases, ffmpeg's decoder does not output audio, so these frames need to be found and paired with silence.

**Comment by JeromeMartinez** [comment]
Result would be like:

```
                        <frame n="0" pos="0" pts="00:00:00.000000" tc="00:07:44;16" rdt="2000-13-30 18:46:00" rec_end="1" arb="4"/>
                        <frame n="1" pos="120000" pts="00:00:00.033367" arb="F" arb_nc="1" faux="1"/>
                        <frame n="2" pos="240000" pts="00:00:00.066733" arb="F" faux="1"/>
                        <frame n="3" pos="360000" pts="00:00:00.100100" arb="F" faux="1"/>
                        <frame n="4" pos="480000" pts="00:00:00.133467" arb="F" faux="1"/>
                        <frame n="5" pos="600000" pts="00:00:00.166833" arb="F" faux="1"/>
                        <frame n="6" pos="720000" pts="00:00:00.200200" arb="F" faux="1"/>
                        <frame n="7" pos="840000" pts="00:00:00.233567" arb="F" faux="1"/>
                        <frame n="8" pos="960000" pts="00:00:00.266933" arb="F" faux="1"/>
                        <frame n="9" pos="1080000" pts="00:00:00.300300" arb="F" faux="1"/>
                        <frame n="10" pos="1200000" pts="00:00:00.333667" tc="00:00:00;00" tc_nc="1" rdt="2000-13-30 18:50:09" rec_start="1" arb="1" arb_nc="1"/>
                        <frame n="11" pos="1320000" pts="00:00:00.367033" tc="00:00:00;01" rdt="2000-13-30 18:50:09" arb="2"/>
```

Does it make sense?
I don't like `faux`, it is not obvious meaning for me, any other suggestion? `deck_issue_detected`?

What would be the exact rule? STA "A" only or any STA? e.g. is 50% STA "9" and 50% STA "A" OK? and 100% STA "9" instead of "A" as seen there?

> Also here suggest an additional attribute if the frame contains no AAUX source pack.

so if AAUX control is the only missing no error, right?
i.e. test is only on AAUX source pack, right?

**Comment by dericed** [comment]
hmmm, i suppose the rule would be is STA is 100% non-zero and all of equal value, so 100% A or 100% F, but not 50% 9 and 50% A.

**Comment by JeromeMartinez** [comment]
Right now I am implementing to:
no_pack="1"
no_pack_aud="1" (only if no no_pack)
no_pack_vid="1" (only if no no_pack)
no_pack_sub="1" (only if no no_pack)
full_conceal="1"
full_conceal_vid="1" (only if no full_conceal)
full_conceal_aud="1" (only if no full_conceal)
vid_sourceorcontrol_missing="1" (if at least 1 is missing)
aud_sourceorcontrol_missing="1" (if at least 1 is missing)

**Comment by dericed** [comment]
I'd merge that
