### ISSUE TITLE
design dvrescue cil stderr output

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#124]
Needs design for a stderr output. For instance to summarize the output of the requested command (summarize the dvrescue xml if requested, was an scc made, etc)

**Comment by ablwr** [comment]
Hmmmm... by default, I think this should follow the patterns currently in place for other MediaArea projects.... but it is currently following close to what the flagship product, MediaInfo, does.

`mediainfo real-file.xyz`: Shows text output
`mediainfo false-file.xyz`: Shows nothing

`dvrescue real-file.xyz`: Shows text output
`dvrescue false-file.xyz`: Shows nothing

So, that's not super ideal.

MediaConch follows the same pattern.

@JeromeMartinez I'd be interested to know if this is a particular design feature useful from an API perspective, for returning nothing when given a wrong filepath.
