### ISSUE TITLE
Lastest build only returns error for all files (on Linux)

### ISSUE THREAD

**Issue by ablwr** [mipops/dvrescue#125]
This seems to be restricted to Linux. I'm on Ubuntu 18.04.

When testing with the latest (20200701) build, every file returns an XML with an error:

```
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.1">
	<creator>
		<program>dvrescue</program>
		<version>0.20.06.20200701</version>
	</creator>
	<media ref="test.dv" error="no frame received"/>
</dvrescue>
```

**Comment by g-maxime** [comment]
Which version of libmediainfo is installed ?

**Comment by ablwr** [comment]
I just used the latest daily build installer with `dpkg`, does that depend on my local libmediainfo? I figured it installed all the deps too.

**Comment by g-maxime** [comment]
As noted on the download page, dvrescue depends on libmediainfo and libzen (at least the versions indicated on the page).
https://mediaarea.net/DVRescue/Download/Ubuntu

**Comment by JeromeMartinez** [comment]
There is maybe an issue with daily builds not setting well the minimum version for libmediainfo, please test installing latest libmediainfo snapshot.

**Comment by ablwr** [comment]
Sorry, yes, I manually installed libmediainfo and now it's fine!
