### ISSUE TITLE
dvpackager -s and -t flags not seperating file

### ISSUE THREAD

**Issue by BleakleyMcD** [mipops/dvrescue#131]
Hi,

I have a DV file (transferred from a MiniDV tape via vrecord) that is not functioning in dvpackager as I expect it to. I know the tape should be separating into files based on start markers and/or timestamps (I shot it myself) but it is not. Maybe my expectations are misplaced?

```
/Users/Bleakley
≈:≈ dvpackager -dn /Users/Bleakley/Desktop/DVRESC/DV001/DV001.dv 
Analyzing DV001.dv
|     # | Byte Offset  | PTS Range                         | Frame Range     | Timecode    | Recording Timestamp | Size      | Fr Rate    | AsRat | ChSub | SampF | Ch.s | Start Rec Flag | TC Jump | Rec Time Jump | IsFirst |
|     1 |            0 | 00:00:00.000000 - 01:00:06.803200 |      0 -     -1 | 00:00:00;06 |                     |   720x480 | 30000/1001 |   4/3 | 4:1:1 | 32000 |    4 |                |         |               |         |


/Users/Bleakley
≈:≈ dvpackager -sn /Users/Bleakley/Desktop/DVRESC/DV001/DV001.dv 
Analyzing DV001.dv
|     # | Byte Offset  | PTS Range                         | Frame Range     | Timecode    | Recording Timestamp | Size      | Fr Rate    | AsRat | ChSub | SampF | Ch.s | Start Rec Flag | TC Jump | Rec Time Jump | IsFirst |
|     1 |            0 | 00:00:00.000000 - 01:00:06.803200 |      0 -     -1 | 00:00:00;06 |                     |   720x480 | 30000/1001 |   4/3 | 4:1:1 | 32000 |    4 |                |         |               |         |


/Users/Bleakley
≈:≈ dvpackager -n /Users/Bleakley/Desktop/DVRESC/DV001/DV001.dv 
Analyzing DV001.dv
|     # | Byte Offset  | PTS Range                         | Frame Range     | Timecode    | Recording Timestamp | Size      | Fr Rate    | AsRat | ChSub | SampF | Ch.s | Start Rec Flag | TC Jump | Rec Time Jump | IsFirst |
|     1 |            0 | 00:00:00.000000 - 01:00:06.803200 |      0 -     -1 | 00:00:00;06 |                     |   720x480 | 30000/1001 |   4/3 | 4:1:1 | 32000 |    4 |                |         |               |         |


/Users/Bleakley
≈:≈ dvpackager -nv /Users/Bleakley/Desktop/DVRESC/DV001/DV001.dv 
Analyzing DV001.dv
|     # | Byte Offset  | PTS Range                         | Frame Range     | Timecode    | Recording Timestamp | Size      | Fr Rate    | AsRat | ChSub | SampF | Ch.s | Start Rec Flag | TC Jump | Rec Time Jump | IsFirst |
|     1 |            0 | 00:00:00.000000 - 01:00:06.803200 |      0 -     -1 | 00:00:00;06 |                     |   720x480 | 30000/1001 |   4/3 | 4:1:1 | 32000 |    4 |                |         |               |         |


/Users/Bleakley
≈:≈ 
```
 XML output attached.

Blake
[DV001.dv.dvrescue.txt](https://github.com/mipops/dvrescue/files/5076338/DV001.dv.dvrescue.txt)

**Comment by kieranjol** [comment]
I wonder if it is because dvpackager is looking for timecode jumps? Maybe
your camera is not creating any timecode discontinuities when you make a
mew clip. I’d guess that this is actually a good thing? Or maybe not, I
dunno. I wonder if dvanalyser sees the different clips? Perhaps the new
clips could also be signified by the jumps in the cameras internal clock?

**Comment by BleakleyMcD** [comment]
Hi Kieran,

Yes, all good questions. I don't know the answers. I would assume pressing the start and stop record button on a camera would cause a mark in the bit stream easily recognizable by dvpackager, but again I don't know. This tape was shot on a TRV900, one of Sony's top line cameras at the MiniDV peak, over the course of a year so I, again assume, it is doing everything correctly. I'll take a peak at the camera settings and see if anything looks awry. I haven't tried dvanalyser yet. Will try to do so before Wednesday. Thanks!

**Comment by dericed** [comment]
Yep, table 17 of http://web.archive.org/web/20060927044735/http://www.smpte.org/smpte_store/standards/pdf/s314m.pdf shows where the markers for the start and stop of recordings is stored in the audio section.

But this file appears to be a single continuous recording but I see a LOT of `tc_nc="1"` which means that many frames have timecode values that are non-continuous, probably dropped frames from capture. Could you share how this file was made? (avfctl or a version of vrecord)? But this doesn't seem like it was made by a camera, maybe by a deck, like there's no recording timestamp to note discontinuity, and although the last frame has an end-recording marker there are no other ones and no start recording markers.

**Comment by BleakleyMcD** [comment]
@dericed It was made on a Sony TR900 shot over the course of a year, by me. Definitely not made by a deck. made with vrecord 2020-07-01

**Comment by dericed** [comment]
Would you mind retesting with the latest vrecord?

**Comment by BleakleyMcD** [comment]
@dericed ok

**Comment by BleakleyMcD** [comment]
@dericed similar result. more errors in the xml, otherwise the same. :(

```
/Users/Bleakley
≈:≈ dvpackager -dn /Users/Bleakley/Desktop/DVRESC/DV001/DV001.dv 
Analyzing DV001.dv, making dvrescue xml file
|     # | Byte Offset  | PTS Range                         | Frame Range     | Timecode    | Recording Timestamp | Size      | Fr Rate    | AsRat | ChSub | SampF | Ch.s | Start Rec Flag | TC Jump | Rec Time Jump | IsFirst |
|     1 |            0 | 00:00:00.000000 - 01:00:06.269333 |      0 -     -1 | 00:00:00;07 |                     |   720x480 | 30000/1001 |   4/3 | 4:1:1 | 32000 |    4 |                |         |               |         |


/Users/Bleakley
≈:≈ dvpackager -sn /Users/Bleakley/Desktop/DVRESC/DV001/DV001.dv 
Analyzing DV001.dv
|     # | Byte Offset  | PTS Range                         | Frame Range     | Timecode    | Recording Timestamp | Size      | Fr Rate    | AsRat | ChSub | SampF | Ch.s | Start Rec Flag | TC Jump | Rec Time Jump | IsFirst |
|     1 |            0 | 00:00:00.000000 - 01:00:06.269333 |      0 -     -1 | 00:00:00;07 |                     |   720x480 | 30000/1001 |   4/3 | 4:1:1 | 32000 |    4 |                |         |               |         |


/Users/Bleakley
≈:≈ dvpackager -nv /Users/Bleakley/Desktop/DVRESC/DV001/DV001.dv 
Analyzing DV001.dv
|     # | Byte Offset  | PTS Range                         | Frame Range     | Timecode    | Recording Timestamp | Size      | Fr Rate    | AsRat | ChSub | SampF | Ch.s | Start Rec Flag | TC Jump | Rec Time Jump | IsFirst |
|     1 |            0 | 00:00:00.000000 - 01:00:06.269333 |      0 -     -1 | 00:00:00;07 |                     |   720x480 | 30000/1001 |   4/3 | 4:1:1 | 32000 |    4 |                |         |               |         |


/Users/Bleakley
≈:≈ 
```

[DV001.dv.dvrescue.xml.txt](https://github.com/mipops/dvrescue/files/5099610/DV001.dv.dvrescue.xml.txt)

**Comment by BleakleyMcD** [comment]
[DV001_-nt.txt](https://github.com/mipops/dvrescue/files/5105362/DV001_-nt.txt)

**Comment by BleakleyMcD** [comment]
@dericed actually it did break on -t

my bad

**Comment by iamdamosuzuki** [comment]
It looks like the break on -t is actually erroneous. It creates 274 files! 

The "Start Rec Flag" column is empty for all of these segments. Which is the more likely scenario, that Bleakley's camera isn't inserting this flag, or that the software isn't able to read the flag that Bleakley's camera made?

**Comment by dericed** [comment]
will close as -t works (the file just has a lot of timecode breaks) and -s doesn't apply here as the recording does not use start flags.
