### ISSUE TITLE
Feature request: ability to specify dvplay -x output directory path

### ISSUE THREAD

**Issue by genfhk** [mipops/dvrescue#138]
i.e. 
dvplay -x file.dv -o /Users/me/Desktop/SpecialLandingPlace/

use case example: 
I qc files stored on drives that need to be read-only, so it would be great to be able to script this to output a batch of reports for every dv file (nested within Bags) on a drive into a different directory somewhere else - currently I have to copy the .dv file onto my machine in order to run dvplay -x, which is not ideal for qc-ing 100s of video files.

**Comment by dericed** [comment]
:) & +1

**Comment by privatezero** [comment]
Have a PR at https://github.com/mipops/dvrescue/pull/140 that should work for this
