### ISSUE TITLE
error with MKV input

### ISSUE THREAD

**Issue by privatezero** [mipops/dvrescue#151]
Files created from the default output of `dvpackager` with the MKV extension that are then rescanned with `dvrescue` throw an error. Same happens for files simply rewrapped via FFmpeg using basic command `ffmpeg -i input.dv -c copy output.mkv`. Tested on both macOS & Ubuntu 18.04

```
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.1">
	<creator>
		<program>dvrescue</program>
		<version>0.20.06.20201025</version>
	</creator>
	<media ref="test-dv.mkv" error="no frame received"/>
</dvrescue>
```

**Comment by dericed** [comment]
reproducable with

```
% ffmpeg -f lavfi -i testsrc=r=30000/1001:s=720x480 -pix_fmt yuv411p -c:v dvvideo -t 1 dv.mkv
% dvrescue dv.mkv
```

which gives the output that Andrew lists. The process above works with QuickTime and AVI containers.
