### ISSUE TITLE
dvpackager: force audio resampling

### ISSUE THREAD

**Issue by bturkus** [mipops/dvrescue#155]
We've got a number of DV tapes in which the audio switches from 2CH 48kHz to 4CH 32KHz, then back to 2CH/32. These were clearly poorly made tapes (the 4CH sections are title sequences with no discernible audio whatsoever), and it got me wondering: would there be any way that dvpackager could forcibly resample these mismatched segments to result in a single file? I know this is a stretch archivally, but it is something that we would carefully use with some regularity.

Thanks for considering it!

Ben

**Comment by JeromeMartinez** [comment]
> with no discernible audio whatsoever

If the audio content can be trashed i.e. replaced by a silent 2-ch 48 kHz content, it is "just" changing a couple of bytes about the audio settings + erasing the audio content part. Would it be acceptable to trash the 4-ch 32 kHz audio content there?

**Comment by dericed** [comment]
I don't think this could be done with the concat protocol or concat demuxer in ffmpeg. To do this, I think the 32 kHz content would have to be transcoded to temporary 48kHz files and then managing a careful series of inputs that include a mix of audio embedded within the dv stream or resampled temporary files.

**Comment by dericed** [comment]
Hey @bturkus, I'm working on this. Can you share the xml for the file you're referring to. Extra credit if you can generate a dvrescue xml using one of the recent builds.
