### ISSUE TITLE
Mockup for Analysis view

### ISSUE THREAD

**Issue by ablwr** [mipops/dvrescue#162]
Need a mockup prepared for Analysis/Playback view

Should include the following features in some sort of order:
- playback video, plain
- playback with concealment video
- timeline for analysis flags
- audio analysis
- play/stop
- jump to next marker
- ability to select what type of next marker to jump to (list below)*
- analysis report - graph
- analysis report - table
- raw xml view (maybe)
- mediainfo report (maybe)
-scc + vtt subtitle control
- ability to load multiple files

Flag list:
Timecode Jump
Recording Start Flag
Recording Timestamp Jump
Frame with Video Error
Frame with Audio Error
Change in Technical Characteristics

**Comment by dericed** [comment]
More comments:
- this view should accept two types of inputs: dvrescue xml and/or dv media files. If the input is a dv media file, then should apply `dvrescue file.dv -x /output/file.dv.dvrescue.xml -c /output/file.dv.dvrescue.scc -s /output/file.dv.dvrescue.vtt`. I think there would be a qctools-like relationship between the report (xml+scc+vtt) and the media file, where the app should have an understanding of their relationship and if one is opened, the app should check for the presence of the other.
- whereas qctools has the player and graphs separate, I think the amount of graphs and player options is reduced enough that they could be in the same ui. So the ui components could be:
   - file selector (like the dropdown bar in qctools to toggle between files)
   - player 1 (original dv input, toggle to show scc or vtt overlay)
   - player 2 (show the dv with a filtered overlay, similar to the dvplay output)
   - graph section (fortunately here, unlike qctools, all graphs can increment per frame, since audio and video will be on the same frame rate)
      - video errors
      - audio errors
      - timeline markers (as Ashley listed above)
   - navigation controls (play/pause toggle, jump to prev/next marker (as Ashley described)

Should consider that sometimes, a user could open a dvrescue xml, but the related media file is not where it's expected, so we'd need an option to locate it, or just have the ui work well even if the video is not there to play.

**Comment by dericed** [comment]
comments? @libbyhopfauf @privatezero @elderorb

**Comment by libbyhopfauf** [comment]
This sounds great! This is more or less what we covered today in our meeting, yeah?

**Comment by ablwr** [comment]
Ya. I might end up splitting this issue into smaller parts, if it's easier for thinking and implementation... wish me luuuck

**Comment by libbyhopfauf** [comment]
Okay! I'll make sure to be tracking it and other smaller part and provide more timely feedback!!

**Comment by dericed** [comment]
Wanted to jot some ideas, but no design skills, but I wrote an xml to convey the structure of the playback/analysis interface.
```xml
<analysis_playback_view>
  <toolbar>
    <file_selector description="a dropdown list of open files"/>
    <toggle description="toggle between list_view and and file_view"/>
  </toggle>
  <list_view>
    <toolbar_buttons="button to make dvrescue xml for each open file without one"/>
    <table description="a table with one row per file">
      <column description="file name" action="click here jumps to file_view"/>
      <columns description="tech metadata like mediainfo:filesize, mediainfo:format others?"/>
      <flag description="is an analysis xml file accessible (checkmark) or not (blank), or if processing show % processed"/>
      <columns description="first occurrence of dv metadata like recording timestamp, timecode"/>
      <columns description="info on dv metadata: standard (infers frame size, frame rate, chromasubsampling), aspect ratio, audio channel count, audio sampling rate"/>
      <flag description="flag to say if the dv file is all a single set of technical characteristics or a number of how many variations there are, like '2' to show a tape that is a PAL/NTSC mix"/>
      <columns description="condition metadata like percent of frames with video errors or audio errors"/>
      <column description="a value to indicate the ratio of errors in even-numbered dif sequences to odd-numbered dif sequences"/>
      <buttons description="buttons to close the file, create dvrescue xml, others?"/>
    </table>
  </list_view>
  <file_view>
    <player_component description="optionally shown if the media file is accessible (sometimes a user may open a dvrescue xml but there's no associated media to play)">
      <player_windows>
        <player_controls descriptions="toggle to display available subtitles in player_1 (scc and/or tech subs if available); toggle to provide metadata overlay (like pts and other ffmpeg data)">
        <player_1 description="window for video playback"/>
        <player_2 description="window for video playback plus overlays to highlight error concealment"/>
      </player_windows>
      <player_control_buttons description="volume control, switch to play audio channels 1/2 or 3/4 (if the active frame is 4 channel), play/pause toggle, jump to beginning, jump to end, jump to next X, jump to prev X, selector to set what X is (recording jump, timecode jump, frame with error, etc), save player 1 frame to file, save player 2 frame to file"/>
    </player_component>
    <analysis_component>
      <graph_controls description="zoom in, zoom out, zoom to fit duration to window size"/>
      <graph description="video errors on timeline"/>
      <graph description="audio errors on timeline"/>
      <graph_scrollbar description="horizontal scroller to facilitate scrubbing in video plus graphs, similar to qctools"/>
      <graph description="flags (recording start, timecode jump, recording time jump, standards change) on timeline"/>
    </analysis_component>
  </file_view>
</analysis_playback_view>
```

**Comment by privatezero** [comment]
One thing I have been testing on my end is not just an output for % of frames with video errors, but also to have scaled categories for number of frames at certain thresholds  of frame concealment.

![image](https://user-images.githubusercontent.com/12941699/100168625-76dac700-2e76-11eb-88bd-009116b5dd22.png)

**Comment by ablwr** [comment]
This document is a work-in-progress but contains a wireframe and comments/descriptions of expected values for each component and what should be included! https://docs.google.com/document/d/1AxTn6_Erwb4hkFWUpQVOy9A-eEcDMsICirl1xP2rjUU/edit#

**Comment by dericed** [comment]
Hi @elderorb, for prototyping the graphs part. Here's an [example xml](https://gist.github.com/dericed/71ed2d3b619f0af69bf99d23c6afe2ef) and the attached image shows an example of some of this data graphed.

![DVR_007 dv dvrescue xml](https://user-images.githubusercontent.com/762604/100547981-c3881e80-3237-11eb-875a-3c0c48c87e12.jpg)

The upper graph plots the tallies of `//frames/frame/dseq/sta/@n` against the time reference in `frame/@pts`. In this example, the `dseq` values have an `@n` attribute, so the graph includes both `//frames/frame/dseq[@n is odd]/sta/@n` (in red) and `//frames/frame/dseq[@n is even]/sta/@n` (in green). The odd dseq tallies are inverted to negative for plotting.

The lower graph plots the tallies of `//frames/frame/dseq[@n is odd]/aud/@n` (in pine green) and `//frames/frame/dseq[@n is even]/aud/@n` (in purple). The odd dseq tallies are inverted to negative for plotting.

Note the the y axis range of the graphs is conditional based on `frames/@size` and `frames/@video_rate`.
If `frames/@size="720x480"` and `frames/@video_rate="30000/1001"` then the y-axis of the upper graph (video errors) is -674 - 675 and -44 - 45 for the lower audio graph.
If `frames/@size="720x576"` and `frames/@video_rate="25"` then the y-axis of the upper graph (video errors) is -809 - 810 and -53 - 54 for the lower audio graph.

Note that it's rare, but that the frames/@size and @video_rate could change in the middle of the timeline.
