### ISSUE TITLE
dvrescue: Problems with XML tc and rdt value when using ffmpeg for capturing?

### ISSUE THREAD

**Issue by joerg-knitter** [mipops/dvrescue#171]
Hi,

I gave dvrescue a try with a private miniDV test tape (recorded >15 years ago) captured on Windows 10 64-Bit 20H2.

I just downloaded ffmpeg-git-full release from gyan.dev (therefore release 20201213) and used the following command to capture a miniDV tape, using a PCIe Firewire card with VIA chipset and standard (!) Windows 10 drivers (not the legacy drivers) and a Sony DCR-PC2E consumer camcorder:
ffmpeg -f dshow -i video="Microsoft DV Camera and VCR" -map 0 -c copy output.dv

The file can be played back without problems with VLC.

However, using "dvrescue output.dv -x output.xml" to output details, the determined recording time stamps are apparently wrong, e.g.:
`<frame n="3004" pos="432576000" pts="00:02:00.160000" tc="00:02:00:04" rdt="1970-01-01 12:51:46" rdt_nc="1" rec_start="1" arb="4"/>`
`<frame n="3193" pos="459792000" pts="00:02:07.720000" tc="00:02:07:18" rdt="1970-01-01 12:53:43" rdt_nc="1" rec_start="1" arb="1"/>`
`<frame n="4549" pos="655056000" pts="00:03:01.960000" tc="00:03:01:24" rdt="1970-01-01 12:56:34" rdt_nc="1" rec_start="1" arb="1"/>`
`<frame n="4835" pos="696240000" pts="00:03:13.400000" tc="00:03:13:10" rdt="1970-01-01 12:57:08" rdt_nc="1" rec_start="1" arb="B"/>`
`<frame n="5838" pos="840672000" pts="00:03:53.520000" tc="00:03:53:13" rdt="1970-01-01 12:58:37" rdt_nc="1" rec_start="1" arb="6"/>`
`<frame n="6456" pos="929664000" pts="00:04:18.240000" tc="00:04:18:06" rdt="1970-01-01 12:59:43" rdt_nc="1" rec_start="1" arb="0"/>`
`<frame n="6500" pos="936000000" pts="00:04:20.000000" tc="00:04:20:00" rdt="1970-01-01 00:04:20" rdt_nc="1" arb="8">`

The weird thing is that at the end of the tape, there seem to be valid timestamps, because 2002 is shown on some sequences as recording year. The contents of the tape:
- The tape starts with a recording made in 2004 with the same Sony DCR-PC2E
- The tape continues later on with recordings made with a Panasonic NV-GS120 - which became damaged and unusable in the meantime, that´s why I use the Sony device as player now
- The tape ends with an old recording from the DCR-PC2E that has not been overwritten by the newer Panasonic recordings, therefore, the recording year is 2002.
However, in my opinion, the time stamps should always be correct, independent of the recording order or recording device.

To check if ffmpeg could be the root of the problem, I recorded the same tape with the (now) free tool ScenalyzerLive from www.scenalyzer.com. It immediately shows the right recording date and also splits the files correctly based on the recording date. However, the tool only allows recordings in Type-1-AVI and Type-2-AVI format, not DV.

The rdt values of a non-split recording look correct:
`<frame n="4020" pos="580344328" pts="00:02:40.800000" tc="00:03:20:21" rdt="2004-10-10 12:53:43" rdt_nc="1" arb="1"/>`
`<frame n="5376" pos="776161288" pts="00:03:35.040000" tc="00:04:15:02" rdt="2004-10-10 12:56:34" rdt_nc="1" arb="1"/>`
`<frame n="5662" pos="817455112" pts="00:03:46.480000" tc="00:04:26:13" rdt="2004-10-10 12:57:08" rdt_nc="1" arb="B"/>`
`<frame n="6665" pos="962272264" pts="00:04:26.600000" tc="00:05:06:16" rdt="2004-10-10 12:58:37" rdt_nc="1" arb="6"/>`
`<frame n="7283" pos="1051501576" pts="00:04:51.320000" tc="00:05:31:09" rdt="2004-10-10 12:59:43" rdt_nc="1" arb="0"/>
`<frame n="7327" pos="1057854472" pts="00:04:53.080000" tc="00:05:33:03" rdt="2004-10-10 12:59:45" arb="8">`

But, the tc differs from the values from the ffmpeg recording of the same scenes, and even though I have started the capturing at a different position than with ScenalyzerLive, I would assume the tc to be the same.
I re-recorded the sequence with ScenalyzerLive, and in fact, the tc and rdt are the same at the specific positions.

Are you aware of problems with ffmpeg regarding the tc and rdt values (at least on Windows) and working on it in collaboration with the ffmpeg team, like done with the audio dropout problems? Or is this problem caused by not using the legacy drivers on Windows?

What about the Type-1- or Type-2-AVI files ScenalyzerLive creates? Could I also use them to create a fixed version using dvmerge or must it be a .dv file? From my understanding, dvmerge uses the XML analysis and there especially the tc and rdt values for recreating the best possible versions from all input files.

Please leave me a note if you need more details. I might also use Linux but I would be happy avoiding Linux installation and setup time if I get it working on Windows instead.

Thanks a lot for your support - and this fantastic project in general!

[EDIT:] I just installed Ubuntu 20.04 with dvrescue (snapshot 20201211) and ffmpeg (self-compiled from daily snapshot) and get the same rdt value errors with the capture made with linux, so it is apparently not related to any Windows driver or DirectShow issue. I used this command: ffmpeg -f iec61883 -i auto -map 0 -c copy output.dv

[EDIT2:] "Converting" an DV-Type-1 AVI from ScenalyzerLive to an DV-File with ffmpeg causes the rdt value to be reset to 1970, using the following command: ffmpeg -i output.avi -vcodec copy -acodec copy output.dv
So apparently, ffmpeg currently is not usable. Unfortunately, merging DV-Type-1 AVIs with dvrescue also does not seem to work.

**Comment by dericed** [comment]
Hi @joerg-knitter, I'm curious about the command they provided: `ffmpeg -f dshow -i video="Microsoft DV Camera and VCR" -map 0 -c copy output.dv`. This would rewrap the audio and video of the input into a new dv container, so the file you get is partly from the tape and partly created by ffmpeg. To output the dv from the input directly, could you try this: `ffmpeg -f dshow -i video="Microsoft DV Camera and VCR" -map 0:v -c:v copy -f rawvideo output.dv`. Am curious if this would bring you the consistency you'd expect. I suspect with your input ffmpeg will recognize a dvvideo input video stream and a pcm input audio stream, with the command I provided the video stream is copied as is (the dvvideo stream contains the audio anyway so it's okay to ignore it here) and then stored as-is (rawvideo) rather than rewrapped. Ping to @privatezero as we should draft some documentation on this particular issue.

**Comment by joerg-knitter** [comment]
Thanks for this hint - I took the command line from https://twitter.com/ffmpeg/status/1072255549540982784. In fact, your command line works, the XML looks good on two test captures I made with Windows 10.
However, the dvrescue merge functionality does not work on the generated files - the resulting file is far to short (each capture has a size of ~1GByte, the merged file just 9 MByte. Is the merge function still in development or should I create a ticket?

**Comment by JeromeMartinez** [comment]
> Is the merge function still in development or should I create a ticket?

A ticket please. We'll need the files (can be in private if needed).

**Comment by dericed** [comment]
Thanks, I [replied](https://twitter.com/dericed/status/1340682582850199560) to the referenced tweet. And yes, the merge function is still in development, but has been working well for me, so am curious about your scenario. Could you confirm that you're merging 2 outputs from the `-c:v copy -map 0:v -f rawvideo` command and not one of those with one of the prior command?

**Comment by joerg-knitter** [comment]
I am going to create a new ticket with details, and yes, I used the command line you delivered.
