### ISSUE TITLE
DVRescue Merge Segmentation Fault

### ISSUE THREAD

**Issue by dirextric** [mipops/dvrescue#179]
Hi,

I've been trying to merge two recordings and the process consistently fails with a segmentation fault. I'm running Fedora 33 (Linux) with the dvrescue-0.20.11.20201226 snapshot provided on https://mediaarea.net. Both recordings are complete captures of an entire tape done through dvgrab. Below is the command I used and the output at maximum verbosity:

```
[user@localhost tapes_directory]$ dvrescue -v 9 video_1.dv video_1_SECOND_CAPTURE.dv --merge final_video_1.dv
DVRescue v.0.20.11.20201226 by MIPoPS

# TC Used Status Comments
#:        the frame number (0-based)
SS;FF:      the time code, if unique accross all files, SS;FF format
S:        the file number (0-based) selected as the reference (non A/V blocks are taken from it), "X" if from several frames

Status:   the status of the frame, 1 char per file
              = Fine
            T = Time code is missing
            P = Frame has problem
            M = Frame is missing

Comments: comments about the issues found
              --> Nothing displayed
            T --> List of time codes, "??:??" if no time code found
            P --> List of count of blocks picked per file, 1 number per file + count of blocks remaining with errors
            M --> Nothing displayed

File 0: video_1.dv
File 1: video_1_SECOND_CAPTURE.dv

   #|SS:FF|U|St|Comments
   0 00;08 0 M 
   1 00;09 0   
   2 00;10 0   
   3 00;11 0   
   
... (nothing eventful, cut for brevity)

10135 38;13 0   
10136 38;14 0   
10137 38;15 0   
10138 ??:?? X PP,   36    0 block picks & 1404 remaining block errors, ??:?? ??:??
10139 ??:?? X PP,   36    0 block picks & 1404 remaining block errors, ??:?? ??:??
Segmentation fault (core dumped)
[user@localhost tapes_directory]$ 
```

This is what comes up when I look at the core dump with GDB:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  file::Merge_Process() [clone .constprop.0] (this=<optimized out>) at ../../../Source/Common/Merge.cpp:368
368     ../../../Source/Common/Merge.cpp: No such file or directory.
```

My guess is that the problem is due to the fact that frames 10138 and 10139 are equally completely corrupted in both copies (according to DV Analyzer, which says both frames have 100% video error concealment in both files). Unfortunately, I can't provide the video files (they're not mine and I'm not allowed to share them), but I can try to help in any other way.

Thanks!

**Comment by JeromeMartinez** [comment]
@dirextric please test [the latest snapshot](https://mediaarea.net/download/snapshots/binary/dvrescue/).

**Comment by dirextric** [comment]
I have upgraded to the latest snapshot and the initial issue is resolved, but now there is a new problem. DVRescue functions normally until frames 10138 and 10139, but then it gets stuck in an infinite loop adding new frames to the output file, continuing even past the end of the input files. Below is the output:

```
[user@localhost tapes_directory]$ dvrescue -v 9 video_1.dv video_1_SECOND_CAPTURE.dv --merge final_video_1.dv
DVRescue v.0.20.11.20201226 by MIPoPS

... (info message)

File 0: video_1.dv
File 1: video_1_SECOND_CAPTURE.dv

   #|SS:FF|U|St|Comments
   0 00;08 0 M 
   1 00;09 0   
   2 00;10 0   
   3 00;11 0   
   
... (nothing eventful, cut for brevity)

10135 38;13 0   
10136 38;14 0   
10137 38;15 0   
10138 ??:?? X PP,   36    0 block picks & 1404 remaining block errors, ??:?? ??:??
10139 ??:?? X PP,   36    0 block picks & 1404 remaining block errors, ??:?? ??:??
10140 38;18 1 PM
10141 38;19 0 MM
10142 38;20 0 MM
10143 38;21 0 MM

... (same thing repeating)

527180 10;16 0 MM
527181 10;17 0 MM
527182 10;18 0 MM
527183 10;19 0 MM
527184 10;20 0 MM
^C
[user@localhost tapes_directory]$ 
```

I was forced to kill the process, which up until that point produced a 60GB video file (the initial file was 13GB). The video was normal up to the broken frames, after which it continued repeating the last working frame continuously (making the video look like a still image).

Should I open a new issue with this information, @JeromeMartinez?

**Comment by JeromeMartinez** [comment]
> Should I open a new issue with this information, @JeromeMartinez?

Yes, please, for better tracing of issues.
