### ISSUE TITLE
DVRescue merge looping after broken frames

### ISSUE THREAD

**Issue by dirextric** [mipops/dvrescue#181]
After what happened in #179, I have upgraded to the latest snapshot and there is a new problem. DVRescue functions normally until frames 10138 and 10139, but then it gets stuck in an infinite loop adding new frames to the output file, continuing even past the end of the input files. Below is the output:

```
[user@localhost tapes_directory]$ dvrescue -v 9 video_1.dv video_1_SECOND_CAPTURE.dv --merge final_video_1.dv
DVRescue v.0.20.11.20201226 by MIPoPS

... (info message)

File 0: video_1.dv
File 1: video_1_SECOND_CAPTURE.dv

   #|SS:FF|U|St|Comments
   0 00;08 0 M 
   1 00;09 0   
   2 00;10 0   
   3 00;11 0   
   
... (nothing eventful, cut for brevity)

10135 38;13 0   
10136 38;14 0   
10137 38;15 0   
10138 ??:?? X PP,   36    0 block picks & 1404 remaining block errors, ??:?? ??:??
10139 ??:?? X PP,   36    0 block picks & 1404 remaining block errors, ??:?? ??:??
10140 38;18 1 PM
10141 38;19 0 MM
10142 38;20 0 MM
10143 38;21 0 MM

... (same thing repeating)

527180 10;16 0 MM
527181 10;17 0 MM
527182 10;18 0 MM
527183 10;19 0 MM
527184 10;20 0 MM
^C
[user@localhost tapes_directory]$ 
```

I was forced to kill the process, which up until that point produced a 60GB video file (the initial file was 13GB). The video was normal up to the broken frames, after which it continued repeating the last working frame continuously (making the video look like a still image). Unfortunately, I can't provide the video files (they're not mine and I'm not allowed to share them), but I can try to help in any other way.

**Comment by JeromeMartinez** [comment]
> I can't provide the video files (they're not mine and I'm not allowed to share them), but I can try to help in any other way.

I need only the last 4 frames (last 480 000 bytes, 133 ms), is it possible to share in private that?
If not, I'll try to put some logs, but I'll need you to compile the code yourself if you can.

**Comment by dirextric** [comment]
Sadly no, I can't provide any part of the files. I should be able to try the second option and compile the code myself. I'll await further instructions.

**Comment by dirextric** [comment]
Quick update: with the latest snapshot from PR #182, the issue changes slightly. Whereas before the merge process continued infinitely adding the last working frame to the output file, now the process itself continues infinitely (saying it's adding frames) but the output file ends at the last working frame. Judging from the comment on the PR, could this be because the recording in question has two broken frames in a row?

On a related note: does the merge process combine timecode information as well? I've had some files where different captures have either lacked or contained timecodes at certain frames, and the merge process chooses to use a frame from the capture without a timecode, resulting in an output file where the frame lacks a timecode even though one of the input files had this information.

**Comment by JeromeMartinez** [comment]
> now the process itself continues infinitely (saying it's adding frames) but the output file ends at the last working frame.

I think that there is a huge gap in the timecodes, and the tool tries to fill the gap. the next PR will limit the tentative of filling gaps, I hope it will fix your issue.

> On a related note: does the merge process combine timecode information as well?

Not for the moment, as I take the non AV data from the most wealthy frame, hoping that the non AV data is the most wealthy too (there is no flag about how wealthy is the non AV data) without checking the time code there. I'll add a test on time code, but please open a dedicated issue so we better track the issues.

**Comment by JeromeMartinez** [comment]
@dirextric please try [latest snapshots](https://mediaarea.net/download/snapshots/binary/dvrescue/), I expect that latest updates prevents the infinite loop.

**Comment by dirextric** [comment]
Indeed, the latest snapshots fix the infinite looping. However, the new algorithm seems to have a separate problem. When I merge with only full captures as inputs, everything goes as expected, but when I try to merge using a combination of full and partial captures, the output file is much shorter than it should be (the output file is about 27,500 frames and the inputs are captures from a 112,500 frame tape). Judging from #212, this might be because the partial captures do not contain the same number of timecode resets as the full captures.

Also, you were right about a timecode gap being at the root of my issue. I've inspected my files and found that what I thought were broken frames are actually frames in between timecode resets. These frames consistently have some unique characteristics: they always have 100% video error concealment and 60% audio errors, and they have no timecodes or recording date/time information. However, their arbitrary bits are consistent. The last good frame before these frames always has an end marker, and they come in sets of three. I think it's these pesky frames that are causing my problems, since the output file produced by the merge process is normal up to the first timecode reset, but then it jumps ahead to the next frame with a sequential timecode (for example, if the last good frame before the first timecode reset has a timecode of 00:05:38;15, the merge process will jump ahead to the next frame with a timecode of 00:05:38;16, skipping everything in between).

Since the infinite looping problem is resolved, I will close this issue, but I am unsure how to proceed. Should I open a brand new issue, or do you think my new problem and #212 are related and I should put further information there? What information (besides the files themselves, unfortunately) would you want me to provide?

**Comment by dericed** [comment]
Hi @dirextric, the mix of full/partial captures could be merged if you dissect them a bit first. Try `dvpackager -e dv -t  your.dv` and it will split the pieces apart into dv segments by the breaks in the timecode.
