### ISSUE TITLE
QT problem with linux GUI build

### ISSUE THREAD

**Issue by privatezero** [mipops/dvrescue#187]
Attempted to install new [build for Ubuntu 20.04](https://old.mediaarea.net/download/snapshots/binary/dvrescue-gui/20210111-3/), and when run it will fail to load with the error:
```
QQmlApplicationEngine failed to load component
qrc:/main.qml:3 module "QtQuick.Controls" version 2.15 is not installed
```

**Comment by g-maxime** [comment]
Unfortunately the GUI depends on Qt 5.15 at runtime. I lowered this to 5.14 in latest snapshot, so Ubuntu 20.10 works, but I can't go further without removing features.

 I will prevent packages generation for unsupported distributions versions.

**Comment by JeromeMartinez** [comment]
> Unfortunately the GUI depends on Qt 5.15 at runtime. I lowered this to 5.14 in latest snapshot, so Ubuntu 20.10 works, but I can't go further without removing features.

@ElderOrb is it a big problem to use Qt 5.12 features only? it is the version on Ubuntu 20.04 (with is the LTS version).

**Comment by ElderOrb** [comment]
@JeromeMartinez I've already returned back support for Qt 5.12 (the cost is one minor feature which can be returned later if needed). But to be fully sure there is not surprises here I need to finish player integration first.

**Comment by dericed** [comment]
@privatezero can you re-review the status of this?

**Comment by privatezero** [comment]
GUI is building successfully now in Ubuntu 20.04 with version 0.20.11.20210201-1

**Comment by dericed** [comment]
Hey @privatezero, can you also check the latest at https://mediaarea.net/download/snapshots/binary/dvrescue-gui/ and see if that works and if it still doesn't have audio (https://github.com/mipops/dvrescue/issues/187).

**Comment by privatezero** [comment]
I'm not seeing any more recent builds in there for linux than 2/11? In testing `v.0.20.11.2021021` the GUIi fails to load with following error (Ubuntu 20.04)

> QQmlApplicationEngine failed to load component
qrc:/main.qml:153 Type AnalysePage unavailable
qrc:/AnalysePage.qml:217 Type DataView unavailable
qrc:/DataView.qml:7 module "Qt.labs.qmlmodels" is not installed

**Comment by privatezero** [comment]
Continuing to get same error when testing `0.20.11.20210226` on Ubuntu 20.04

> QQmlApplicationEngine failed to load component
qrc:/main.qml:159 Type AnalysePage unavailable
qrc:/AnalysePage.qml:242 Type DataView unavailable
qrc:/DataView.qml:7 module "Qt.labs.qmlmodels" is not installed

**Comment by JeromeMartinez** [comment]
Please try this snapshot https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20210226-9/

**Comment by privatezero** [comment]
thank you!  - I just tested 0.20.11.20210228 and it is loading correctly now

**Comment by dericed** [comment]
ok to close?

**Comment by privatezero** [comment]
I figure it probably is - I'll let you know if it breaks again
