### ISSUE TITLE
No audio in Ubuntu GUI playback

### ISSUE THREAD

**Issue by privatezero** [mipops/dvrescue#220]
Testing on version 0.20.11.20210201-1 Ubuntu 20.04, and there is no audio during playback when viewing input file in embedded player.

**Comment by dericed** [comment]
@privatezero, still the case?

**Comment by privatezero** [comment]
Not sure! See https://github.com/mipops/dvrescue/issues/436

**Comment by privatezero** [comment]
Hi @dericed just confirmed that this is still an issue

**Comment by g-maxime** [comment]
Fixed in latest snapshot (added qtmultimedia-plugins as dependency)

**Comment by dericed** [comment]
Will close based on @g-maxime's review. @privatezero please reopen if not the case.

**Comment by privatezero** [comment]
Will test again - I believe I already confirmed it was working on my end (and then neglected to report)
