### ISSUE TITLE
scaling problems in Windows GUI

### ISSUE THREAD

**Issue by privatezero** [mipops/dvrescue#221]
Testing windows build from [this snapshot](https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20210131-2-3/), and the GUI window doesn't appear to be scaling as intended. On initial startup it will open scaled too large to be fully displayed on screen, and when I attempt to resize individual GUI components do not scale accordingly. (This results in even more buttons being cut off as well as general jumble).
<img width="509" alt="gui-scaled" src="https://user-images.githubusercontent.com/12941699/106513049-43747400-6487-11eb-9071-a70aa3d1b9b8.PNG">

**Comment by ElderOrb** [comment]
What is your resolution? Not sure we ever tested behavior on resolution lesser than startup size

**Comment by privatezero** [comment]
Resolution is 1920x1080, with app scaling set to the system "Recommended" setting of 150%.

**Comment by ElderOrb** [comment]
@privatezero can you please try the latest version? Looks like this for me: 

<img width="959" alt="image" src="https://user-images.githubusercontent.com/23638/201176979-bebc9e62-6972-47e8-8601-7db92dea010d.png">

**Comment by dericed** [comment]
Will close, as the ui has undergone a lot of development since this issue was open. @privatezero please reopen if still an issue.

**Comment by privatezero** [comment]
This was still in fact an issue in the most recent build I tested on Windows, but is mainly a problem on my laptop so maybe not worth focusing a ton of energy on right now
