### ISSUE TITLE
designing sdterr status bar for read dv

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#223]
Starting to issue to define the status output of dvrescue when reading a dv input:

```
01234567890123456789012345678901234567890123456789012345678901234567890123456789
Frame# AbsTr# Timecode    RecordingDateTime FrErr% BlErr% Progress
012345 012345 HH:MM:SS:FF YY-MM-DD HH:MM:SS XX.XX% XX.XX% XX.XXX%
```

- `Frame#` is a counter of read frames
- `AbsTr#` is absolute track number of last read frame or ------ if none
- `FrErr%` is the percentage of frames read with errors (dseq/sta and/or dseq/aud)
- `BlErr%` is the percentage of DIF blocks read with errors (dseq/sta and/or dseq/aud)
- `Progress` is disabled when a piped input, else would provide a percentage of how much of the input file(s) is read.

I tried to keep the output under 80 characters in width. This example uses 66 so possibly another field could be added. Comments?

**Comment by privatezero** [comment]
I think all these look like the most useful pieces of information that I would want! Would it be useful to have something that gave some sort of rolling peak or average error rate across a preceding amount of time (60 seconds or so)? Might provide a little more context for people paying active attention to a transfer (but might also be overkill?)

**Comment by ElderOrb** [comment]
where exactly in dvrescue-ui you would like to see it @dericed ?

**Comment by libbyhopfauf** [comment]
@dericed agreed! these are really useful! Also, @privatezero I think that could be really helpful, but maybe annoying with a really bad tape? Would it be difficult to have it as a feature/filter that could be turned on and off?

**Comment by dericed** [comment]
Closing as this is defined in the csv document now.
