### ISSUE TITLE
dvrescue -m log files

### ISSUE THREAD

**Issue by privatezero** [mipops/dvrescue#226]
From a preservation provenance perspective, I think it would be helpful for the results of `dvrescue -m` that are currently displayed in the terminal to also be written to an associated log file that can be saved by holding institutions if desired.

Currently these results can be obtained by adding `> name.log` to the merge command, but this feels like something that would be most useful supported directly by the tool.

**Comment by dericed** [comment]
Hey @privatezero in the latest daily build there's:
```
     --merge value | -m value
        Merge all input files into value (file name),
        picking the best part of each file.

    --merge-info-output value
        Store Merge info output to value (file name).
```

Any better idea for the name of the argument or definition?

**Comment by JeromeMartinez** [comment]
I switch to `--merge-log` option name for the moment. Can be changed if something better is found.
