### ISSUE TITLE
icons needed

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#245]
Making a list of icons needed:

These icons would replace the current "Recording Marks" column, which is empty or says "Start" and/or "End"
- recording start
- recording end

Playback controls:
Currently these are in the gui as `<<`, `<`, `PLAY`, `>`, and `>>` but could match the style of other icons.
- jump to first frame
- prev frame
- play
- pause
- next frame
- jump to last

Captioning
- we need an icon for a broken caption. This is rare, but something like the `[cc]` symbol in a broken way.

**Comment by dericed** [comment]
My bad, playback icons are already set up at https://github.com/mipops/dvrescue/tree/main/Source/GUI/dvrescue/dvrescue/icons. @ElderOrb can you integrate the svg icons for play, rewind, stop, fastforward, rewind.

**Comment by dericed** [comment]
![image](https://user-images.githubusercontent.com/762604/108568199-a2cfe200-72d7-11eb-8ddc-fc0862094ec2.png)

In this image, there's many jumps in the recording time. Some jumps correlate to a Start Recording Mark, so the recording time jump is explained by someone starting and stopping the camera. Some jumps do not correlate to a Start (this could be because of an edit or dropped frames in the capture). Based on this I'd like to change [the non-continuous icon[(https://github.com/mipops/dvrescue/blob/2069da82afab9d1bf2c377fcb86ed907cecb2238/Source/GUI/dvrescue/dvrescue/icons/alert-non-continuous-jump.svg) into two:
- non-continuous because of the recording method
- non-continuous for another reason

Alternatively since we may make a Recording Start icon, we could consider that the Recording Start icon implies a non-continuous recording time.

**Comment by libbyhopfauf** [comment]
@dericed agreed! I think that would be much more intuitive for users to understand why/how the error occurred. Will create a second icon to note the record one.

**Comment by libbyhopfauf** [comment]
What if we do color coded ones:

non-continuous because of the recording method = green
non-continuous for another reason = red

![image](https://user-images.githubusercontent.com/13877631/108777494-ba49dd80-7518-11eb-933a-723d2148ca51.png)
![image](https://user-images.githubusercontent.com/13877631/108777560-d483bb80-7518-11eb-8a99-a734b857e21a.png)

**Comment by libbyhopfauf** [comment]
Here are the closed captioning icons:
closed-caption-end-error.svg
closed-caption-end.svg
closed-caption-middle-error.svg
closed-caption-middle.svg
closed-caption-start-error.svg
closed-caption-start.svg

**Comment by libbyhopfauf** [comment]
Closed captioning icons are available here: https://drive.google.com/drive/folders/1dx_ZUjRc5YTH8zJf-FBC8rvFs2pLemy7?usp=sharing

**Comment by libbyhopfauf** [comment]
> My bad, playback icons are already set up at https://github.com/mipops/dvrescue/tree/main/Source/GUI/dvrescue/dvrescue/icons. @ElderOrb can you integrate the svg icons for play, rewind, stop, fastforward, rewind.

Great! Do we still need next frame [>] and previous frame [<]? I didn't see those SVGs listed with the others, so just wanted to double-check.

**Comment by libbyhopfauf** [comment]
Closed captioning icons added here: #246

**Comment by libbyhopfauf** [comment]
Mock-ups for recording start and recording end:

![recording-marker-stop_options_ALL](https://user-images.githubusercontent.com/13877631/108792145-774a3300-7535-11eb-9f38-ba5af1e123c8.png)

**Comment by dericed** [comment]
oh i like these as option 1 could be used in the table while option 2 could be used as a marker in the graph.

**Comment by dericed** [comment]
@libbyhopfauf I like best option 1 for the table and option 2 for the graph, but could you also make a third value, for the crazy-rare situation of a frame that has both the start and end marker, like a combination of both together.

**Comment by libbyhopfauf** [comment]
> @libbyhopfauf I like best option 1 for the table and option 2 for the graph, but could you also make a third value, for the crazy-rare situation of a frame that has both the start and end marker, like a combination of both together.

Yeah! That's what I was thinking as well (re: graph vs. table). I can definitely make a start/end combined marker.

**Comment by libbyhopfauf** [comment]
@dericed how about this?

![recording-marker-stop_options_table+graph](https://user-images.githubusercontent.com/13877631/108922058-7bd12300-75eb-11eb-8400-6fb3ce30694a.png)

**Comment by ElderOrb** [comment]
> My bad, playback icons are already set up at https://github.com/mipops/dvrescue/tree/main/Source/GUI/dvrescue/dvrescue/icons. @ElderOrb can you integrate the svg icons for play, rewind, stop, fastforward, rewind.

Sure, but need two more icons for step back / step forward

**Comment by dericed** [comment]
@libbyhopfauf the start/stop ones look great. Please add them to https://github.com/mipops/dvrescue/tree/main/Source/GUI/dvrescue/dvrescue/icons in a pull request.

**Comment by libbyhopfauf** [comment]
@ElderOrb no problem! I'll get a mock up going.

@dericed will do!

**Comment by libbyhopfauf** [comment]
@dericed any other icon requests?

**Comment by libbyhopfauf** [comment]
@dericed okay, I have all the new SVG icons uploaded. Any other that need to be created?

**Comment by dericed** [comment]
@libbyhopfauf, what do you think of a pair of icons for the extender action to show/hide the file-list
![image](https://user-images.githubusercontent.com/762604/110801052-d785e800-824a-11eb-9f6a-47be0a315e86.png)
![image](https://user-images.githubusercontent.com/762604/110801077-dce33280-824a-11eb-9da2-4d060c5226ed.png)

Currently it's a simple `^` vs `>`.

**Comment by libbyhopfauf** [comment]
See #271 and #272

**Comment by dericed** [comment]
will close, i think we got everything listed, will reopen when we get to this work on other tabs
