### ISSUE TITLE
Linker error if libzen isn't built with zlib 

### ISSUE THREAD

**Issue by henryborchers** [mipops/dvrescue#26]
When building dvrescue, if libzen isn't built with zlib, I get a linker error.

`
../../.local/lib64/libzen.so.0.4.37: undefined reference to `pthread_create'
`
Tested with  Centos 7, Centos 8, Fedora 31, Ubuntu 16.04, and Ubuntu 18.04

**Comment by g-maxime** [comment]
Do you build ZenLib with autotools or CMake?

If you build with CMake, can you try with this patch? MediaArea/ZenLib#103

**Comment by henryborchers** [comment]
Why closed? It’s still an issue

**Comment by JeromeMartinez** [comment]
We didn't have feedback from https://github.com/MediaArea/ZenLib/pull/103#issuecomment-560132661.

**Comment by henryborchers** [comment]
Sorry, I'm working on dockerfiles to make it easier to explain. I had a busy week coming back from work from Thanksgiving. I'll have them shortly.

**Comment by henryborchers** [comment]
My mistake, it's not zlib. It's CURL. If libcurl isn't installed, then I get linker errors. 

@JeromeMartinez I have build logs on my Jenkins server to prove it. Can I PM you a link?

**Comment by JeromeMartinez** [comment]
> Can I PM you a link?

@g-maxime would handle that, his email address is on the PR/commit previously linked.

**Comment by henryborchers** [comment]
Sure thing!
