### ISSUE TITLE
Mac GUI - suggestions for improving Transfer interface

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#277]
Below is an image of the sections that I am referring to with each item in the numbered list.

1.) Did the inverted logo/any of the variations on a transparent background work in here? Do I need to make a new version so we can use one with a transparent background?

2.) Could we bold this text for the table? Or change the color? It is really hard to read, so not very accessible.

3.) Super minor, but should we use a colorbars still from a DV capture for the static image here? It looks like this one is from a U-matic capture (super nerdy, I know…)

4.) To be consistent, should we change the “capture” to read “transfer”? I know @ablwr did a survey about using "transfer" vs. "capture" and I believe "transfer" was the preference. Or how would you all feel about using a recording icon instead (so it is more consistent with the other navigation buttons)? My personal preference would be to use a red record style icon button, but I'm open to either :)

5.) Can we center the navigation buttons?

<img width="1279" alt="GUI_Transfer_Suggestions" src="https://user-images.githubusercontent.com/13877631/112397873-222e4800-8cc0-11eb-82cb-72e3ee261aa3.png">

**Comment by dericed** [comment]
1. I'm unclear on this issue. Is that was https://github.com/mipops/dvrescue/blob/main/Source/GUI/dvrescue/dvrescue/icons/logo-inverse.png file is for?
2. IIUC, this table is unused. @ElderOrb, i suggest the list in this table match the file table in other sections. I agree with @libbyhopfauf about readability.
3. Hmmm, @libbyhopfauf can you replace https://github.com/mipops/dvrescue/blob/main/Source/GUI/dvrescue/dvrescue/colorbars.jpg. The way to make clean color bars from `ffmpeg -f lavfi -i smptebars -vframes 1 colorbars.jpg` or we could consider something else, like a grey screen with "No signal..." to communicate that the image isn't from the deck.
4. +1
5. +1
cc @ElderOrb

**Comment by libbyhopfauf** [comment]
@dericed @ElderOrb 

1. Yep! That's it!
2. OOO yes, that would be great if it matched the others!
3. I like that idea better, actually! How about this:


![transfer-no-signal](https://user-images.githubusercontent.com/13877631/141696914-f78c83e8-55ba-4284-8545-6e1596591789.png)

**Comment by libbyhopfauf** [comment]
@ElderOrb would it be possible to replace the DVRescue logo in the GUI with this file: https://github.com/mipops/dvrescue/blob/main/Source/GUI/dvrescue/dvrescue/icons/logo-inverse.png ?

**Comment by dericed** [comment]
@libbyhopfauf we have https://github.com/mipops/dvrescue/blob/main/Source/GUI/dvrescue/dvrescue/dvrescue.png and https://github.com/mipops/dvrescue/blob/main/Source/GUI/dvrescue/dvrescue/icons/logo-inverse.png. But could we make this into an alpha background svg logo that could work with either light or dark mode?

**Comment by libbyhopfauf** [comment]
@dericed I'm not exactly sure what you're asking. Is that just a different setting for exporting the SVG or do you mean you just need me to export both as SVGs? I might have to rebuild the logo entirely to make a "real" SVG, but just let me know which you mean and I can get going on that.

**Comment by libbyhopfauf** [comment]
> @dericed @libbyhopfauf is it still relevant?

Yes, the GUI logo still needs to be replaced with this one that has white text and no background, please and thank you!

 https://github.com/mipops/dvrescue/blob/main/Source/GUI/dvrescue/dvrescue/icons/logo-inverse.png

**Comment by libbyhopfauf** [comment]
Also see #535 for additional suggested changes to the dvcapture GUI layout.

**Comment by dericed** [comment]
Closing as much is out of date and I think the last piece is solved in https://github.com/mipops/dvrescue/pull/557.
