### ISSUE TITLE
device not recognized in dvrescue

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#279]
Despite a bunch of reboots and settings troubleshooting, I can't seem to get DVRescue to detect any of my decks....

<img width="1792" alt="Screen Shot 2021-03-24 at 5 13 24 PM" src="https://user-images.githubusercontent.com/13877631/112399971-805d2a00-8cc4-11eb-9c71-6a90df64f4fe.png">

....but they are showing up in vrecord

<img width="1792" alt="Screen Shot 2021-03-24 at 5 17 28 PM" src="https://user-images.githubusercontent.com/13877631/112400101-dc27b300-8cc4-11eb-8c62-2c24409bc545.png">

**Comment by NMAAHC** [comment]
I'm having the same problem

**Comment by dericed** [comment]
@libbyhopfauf, still? I just tested in the latest daily build and seems ok.

**Comment by libbyhopfauf** [comment]
Oh no, this is resolved now!

**Comment by dericed** [comment]
:D
