### ISSUE TITLE
Docs: Define XML parameters

### ISSUE THREAD

**Issue by ablwr** [mipops/dvrescue#28]
Need to draft documentation around XML parameters for users

**Comment by dericed** [comment]
Maybe worth keeping that documentation in sync with what is in https://github.com/mipops/dvrescue/blob/master/tools/dvrescue.xsd. Although the HTML report may use very different terms since it is derived from the xml.

**Comment by ablwr** [comment]
Oh yesss yes, thank you.

**Comment by dericed** [comment]
Noting that the logic of https://github.com/mipops/dvrescue/issues/123#issuecomment-692973269 needs to be clear within the xsd documentation.

**Comment by dericed** [comment]
@privatezero, we have the documentation at https://github.com/mipops/dvrescue/blob/main/tools/dvrescue.xsd, are you interested in making some sort of process to 'make' a user-friendly doc from the xsd in case users really want to understand the dvrescue xml content?

**Comment by privatezero** [comment]
Cool, yeah - I'm on it!
