### ISSUE TITLE
"Settings" menu

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#280]
I do think it's nice to have the option to change the location/version of dvrescue that you want the GUI to use, but could there maybe be a default (for example /usr/local/bin/dvrescue)?

<img width="559" alt="Screen Shot 2021-03-24 at 1 18 39 PM" src="https://user-images.githubusercontent.com/13877631/112400275-44769480-8cc5-11eb-8995-fb4f6459b7c9.png">

<img width="546" alt="Screen Shot 2021-03-24 at 5 21 20 PM" src="https://user-images.githubusercontent.com/13877631/112400310-5bb58200-8cc5-11eb-9533-6f9f60c68d48.png">

**Comment by ElderOrb** [comment]
In fact dvrescue-gui auto-detects tools path on first startup and then stores it in settings. I should finally add the way of clearing that settings (at least to demonstrate existing behaviour) but this is separate story

**Comment by dericed** [comment]
Hmmm, is this issue still open @ElderOrb, @libbyhopfauf, @JeromeMartinez . I would like to have these bundled within the app, so that the app is usable even if the user doesn't have the dependencies installed outside of the gui.

**Comment by libbyhopfauf** [comment]
@dericed I think that would be great and make it a lot easier for folks!! It seems like when I install a new version it remembers where the paths were, but when I tried it on a different computer where dvrescue hadn't been install previously, I had to manually input the paths.

**Comment by ElderOrb** [comment]
@JeromeMartinez @g-maxime anything you need from me to package stuff properly? dvrescue auto-detects tools from anything inside PATH. Also it adds a few folders (like tools) into PATH. One of such folders could be used for bundling
