### ISSUE TITLE
plotted data should include all <sta> values

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#287]
Most of our sample data uses `<sta t='10'` but @privatezero found a sample that does use an alternate error value. See https://gist.githubusercontent.com/privatezero/2b1b465d51deceafeea97fcc39ffca26/raw/f0ab1f3ed97094611d6fd81c99cd537b581e1459/dvrescue-out.xml. Perhaps we should differentiate the sta error values somehow but for now let's parse all `frame/sta` values regardless of what the value of `sta/@t` is.

**Comment by dericed** [comment]
Interestingly, the table's plot of the sta error codes does include t=14 but not the graph.

**Comment by dericed** [comment]
@ElderOrb, could you send a pull request, the fix seems to be only in your fork

**Comment by ElderOrb** [comment]
changes seem to be in main already
