### ISSUE TITLE
Mac GUI - "Help" menu

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#291]
Currently, the "Help" menu is empty. Are we planning to have the -h page here or will it link to a GitHub/the DVRescue website for documentation?

**Comment by dericed** [comment]
Hi @libbyhopfauf, we can put whatever we like there. In QCTools, the links to a tabbed window that flips between various HTML pages.

**Comment by dericed** [comment]
Nudge to @libbyhopfauf, where should we have this link to?

**Comment by libbyhopfauf** [comment]
I really like the idea of having it go to a tabbed window like QCTools. @privatezero would that be a separate thing to work into the documentation website or would it work the same way?
