### ISSUE TITLE
Mac GUI - suggestions for improving "Analysis" layout

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#293]
Should we maybe change the color used for highlighting the current frame in the graph and table? Like since we already use red to indicate stop markers (as well as green, blue and orange for other types of markers), maybe we could use like...purple to highlight rows in the table/plot point on the graph to make it a little less confusing?

**Comment by dericed** [comment]
purple sounds good to me, for graph cursor and row highlight.

**Comment by libbyhopfauf** [comment]
Perfect! Thank you!
