### ISSUE TITLE
GUI - Behavioral suggestions 

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#294]
I know we've talked about this previously, but I wasn't sure where we landed: in the workshop today several people mentioned it would be nice to have the navigation buttons change color when hovered or any indicators of hovering (movement or color change).

**Comment by dericed** [comment]
Yes this effect was added to the timeline markers, so they show an outline during mouseover. The playback buttons on the analysis tab also show a slight darkening in color during hover. Do you mean with the transfer/analysis/package/settings/help/debug buttons? @ElderOrb could you add a similar highlight to these during hover as with the markers, maybe also setting the svg to darken to mid-gray if we are active on that layout.

**Comment by libbyhopfauf** [comment]
Awesome! Thank you!
