### ISSUE TITLE
DVRescue Capture won't working in vrecord without camera permissions

### ISSUE THREAD

**Issue by iamdamosuzuki** [mipops/dvrescue#301]
A user tried capturing via vrecord using macOS 10.14.6 and got the following error

![DVRescue_Error](https://user-images.githubusercontent.com/3967767/115444348-4d299000-a1c9-11eb-87e0-ee21fe730e9c.png)

The key part here is "this app is not authorized to use DV-VCR"

The user changed the OS camera permissions (System Preferences -> Security and Privacy -> Privacy -> Camera -> Added Terminal to the list)

After that the capture worked.

**Comment by BleakleyMcD** [comment]
I had this same problem with avfctl a while back. Solved with the same solution!

**Comment by libbyhopfauf** [comment]
Thank you! Adding to the troubleshooting section of the documentation/guidance page!

**Comment by dericed** [comment]
@libbyhopfauf, closing as it's in the documentation now
