### ISSUE TITLE
Suggestion for Documentation

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#308]
I think it would be easier to navigate the website if we made the deck guide its own page vs. how now you have to scroll through the setup page to get to it.

**Comment by privatezero** [comment]
makes sense to me!

**Comment by libbyhopfauf** [comment]
I think maybe "Cleaning and Maintenance" should be its own thing too and that the "Cleaning Supplies" should be under that page. Just seems like it would be more intuitive to navigate. And on that same note, the poster link under "Cleaning Supplies" needs to be updated to this one: https://drive.google.com/file/d/1rl-0pmiTF3_98wLNPf2_KS9UVbYfYQys/view?usp=sharing

**Comment by privatezero** [comment]
Should be addressed in https://github.com/mipops/dvrescue/pull/314
