### ISSUE TITLE
dvplay -x mode not creating XML/images (directory)

### ISSUE THREAD

**Issue by ablwr** [mipops/dvrescue#31]
I'm getting an error when running `dvplay -x`.

Here is the output:
```
Assessing error.dv...
./dvplay: line 63: samples/error.dv_dvrescue/error.dv.dvrescue.xml: No such file or directory
Making jpegs of errors within error.dv...
./dvplay: line 66: xml: command not found
```

The bottom error on line 66 can be averted by my changing `xml` to `xmlstarlet`. However I haven't figured out what's up with line 63 -- it seems to not be creating this folder.

I'm on Linux Ubuntu 18.04, which may be the issue, assuming this was written for and on a Mac!

**Comment by ablwr** [comment]
Line 63 is `dvrescue "${DVFILE}" > "${DVRESCUE_XML}"`

**Comment by ablwr** [comment]
Got it! On Line 63, I added `mkdir "${SIDECAR_DIR}"`

**Comment by dericed** [comment]
fixed via https://github.com/mipops/dvrescue/commit/94143fc46f065416c50de80d00b29ff2badcd818 https://github.com/mipops/dvrescue/commit/63c04826dcf693ef67847ba2bf0d303d35a6c60a

**Comment by ablwr** [comment]
Cool thanks for testing on a Mac and patching!

**Comment by libbyhopfauf** [comment]
I am currently encountering this issue. I haven't been able to run `dvplay -x` on any files for the last couple days. I keep getting the same error message (similar to the one Ashley was getting):

```
MAC1:~ mipopsmac1$ dvplay -x /Users/mipopsmac1/Desktop/DV_Rescue_Tests/SMA_7350/7350.dv 
Assessing 7350.dv...
/usr/local/bin/dvplay: line 63: /Users/mipopsmac1/Desktop/DV_Rescue_Tests/SMA_7350/7350.dv_dvrescue/7350.dv.dvrescue.xml: No such file or directory
Making jpegs of errors within 7350.dv...
failed to load external entity "/Users/mipopsmac1/Desktop/DV_Rescue_Tests/SMA_7350/7350.dv_dvrescue/7350.dv.dvrescue.xml"
MAC1:~ mipopsmac1$ 
```

I'm running version dvrescue 0.19.11.20191114
