### ISSUE TITLE
website: macOS Transfer Station Set-up

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#312]
These images (related to the website guidance/documentation) for the "macOS Transfer Station Set-up" are ready for review. They are available here: https://drive.google.com/drive/folders/1gVpzu19n54w6VjNos7F8LG-3OVD2TSjB?usp=sharing

Feedback appreciated. 

Accompanying text is in the works and will be submitted for review shortly.

**Comment by privatezero** [comment]
Should be addressed in https://github.com/mipops/dvrescue/pull/314
