### ISSUE TITLE
docs image sizing

### ISSUE THREAD

**Issue by privatezero** [mipops/dvrescue#313]
We need to:
* resize many images to more web friendly resolutions when hi-res isn't needed
* edit css to display larger images when needed (currently limited to 400 px)

**Comment by libbyhopfauf** [comment]
Here are the new, properly sized images for the repair and cleaning supplies:

https://drive.google.com/drive/folders/1bWMB-jZGgJMFQJgjnh99BoUBW-8ndjx1?usp=sharing

**Comment by libbyhopfauf** [comment]
And here are the smaller versions of the macOS transfer station images:

https://drive.google.com/drive/folders/1nzLiiPeeBl4lK_ngJShlDvCggQZXdsiw?usp=sharing

Let me know if you have trouble accessing the link!

**Comment by dericed** [comment]
who's got this one? @privatezero @libbyhopfauf
