### ISSUE TITLE
dvpackager: error in ffmpeg command (line 347)

### ISSUE THREAD

**Issue by frozenAntilope** [mipops/dvrescue#330]
dvpackager throws an error, when inspecting a *.dv (I tried various) file:

`/usr/local/bin/dvpackager: line 347: ffmpeg: command not found`

looking at the code here on github line 347 brings a
`fi`
command. But no direct ffmpeg command.

What could be the issue here?

**Comment by dericed** [comment]
Thanks for reporting this. The dvpackager script relies on ffmpeg and in this case the script was running without verifying that it was installed. With the updates referenced, it should complain and give a better error is ffmpeg is missing.
