### ISSUE TITLE
rename `<frames>`

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#333]
I've found the name of the `<frames>` element creates some confusion, particularly when discussed along with the `<frame>` element. I suggest to rename it and am welcome to suggestions.

@libbyhopfauf and I discussed: section, sequence, part. This value is a label for a series of frames that share key properties; when there's a change in aspect ratio or ntsc/pal or channel count* then that would start a new occurrence of this.

**Comment by JeromeMartinez** [comment]
I like that "frames" element includes "frame" elements.
"seq" wording is also used in a DV frame.

I understand that this may be confusing for the user, so I let you decide :).

**Comment by dericed** [comment]
Ok, frames for now. If you were lurker and had an opinion, please feel free to speak up or reopen.
