### ISSUE TITLE
GUI Feature Request: Playback Timestamp

### ISSUE THREAD

**Issue by iamdamosuzuki** [mipops/dvrescue#346]
There currently isn't a way to view the current playback timestamp when you're playing a video in the GUI. I'm not exactly sure where it should go. Maybe in the blank space to the left or right of the transport buttons? Left side could be current time stamp and right side could be duration.

**Comment by dericed** [comment]
I was thinking of waiting on this until we support filterchains in the player. @ElderOrb, are we ready for filters in the player, or should we consider displaying pts outside of the player?

**Comment by ElderOrb** [comment]
Simple cases should be working now (at least works for me in QCTools). Also we will never know till try. What is required from me here? Just apply some filter unconditionally? @dericed

**Comment by dericed** [comment]
@elderorb, can we test the player on the analysis tab with this filter:

`-vf "drawtext=text=%{pts\\\:hms}:x=(w-text_w)/2:y=(h-text_h)*(4/5):box=1:boxcolor=gray@0.5:fontsize=36"`

**Comment by dericed** [comment]
@iamdamosuzuki, this will be in the next daily build. Please test and reopen or comment any impressions. Thanks. :D
