### ISSUE TITLE
GUI Modification Request: Show only filename in file dropdown, not entire path

### ISSUE THREAD

**Issue by iamdamosuzuki** [mipops/dvrescue#347]
For my QC workflow I'm regularly opening 10 videos at a time in dvrescue, but it's hard to page through them because the entire path shows up in the dropdown menu and the file name itself is truncated. Personally I would never need to see the entire path here, but maybe it could be an option?

**Comment by dericed** [comment]
Ya I agree that filename alone would suffice. Maybe if there were two files open with the same name then the file path could be shown instead, else just the filename.

**Comment by dericed** [comment]
This is done is the recent daily builds. Thx!
