### ISSUE TITLE
2021-09-29 GUI: multiple decks?

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#363]
It seems like the GUI is only recognizing one of my decks that I have connected to my computer, but vrecord sees two.

![Screen Shot 2021-09-29 at 3 58 11 PM](https://user-images.githubusercontent.com/13877631/135362587-644f2f45-3115-4a17-b36b-6bb4c07b4717.png)

But if I close out of the GUI, turn off the first deck and then restart the GUI, it does see the other deck. So it seems like it's only recognizing one at a time for capture. 

![Screen Shot 2021-09-29 at 3 59 52 PM](https://user-images.githubusercontent.com/13877631/135362672-b6666e5c-cb73-4758-9212-1730b93ca47f.png)

And if I leave it open and turn the first deck back on, it switches and doesn't see to have a way to select which one you want. Would it be possible to add a drop-down menu so that you can select which deck you want to capture with?

**Comment by ElderOrb** [comment]
Actually what if dvrescue could present as much 'players' as much decks are connected? This way controlling decks would be much simpler than via combobox and visualizing captured frames too.

**Comment by libbyhopfauf** [comment]
I think that would work! That would be better too for stopping captures so that you didn't accidentally end the wrong one. I think @dericed was envisioning that previously too!

**Comment by libbyhopfauf** [comment]
@dericed @ElderOrb last i checked, this was resolved, yeah?

**Comment by dericed** [comment]
Yes, resolved :D
