### ISSUE TITLE
2021-09-29 GUI: must enter ".dv" with identifier

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#364]
Using the 2021-09-29 GUI, when prompted to enter an identifier after clicking on "Capture" you need to manually enter ".dv" after the identifier (vs. just the identifier, as with vrecord) before clicking "Save" otherwise the file is saved as a text document.

![Screen Shot 2021-09-29 at 3 31 08 PM](https://user-images.githubusercontent.com/13877631/135363047-d7afa3fa-1ac0-45a5-adfc-8d63eda02cbe.png)

**Comment by ElderOrb** [comment]
![image](https://user-images.githubusercontent.com/23638/141363566-0f185368-17dd-4d16-a4eb-20a768f55cb1.png)

**Comment by dericed** [comment]
closing as fixed
