### ISSUE TITLE
dvpackager error: file expected but missing

### ISSUE THREAD

**Issue by svhartzell** [mipops/dvrescue#371]
Hi, I'm using dvpackager to repackage a .dv file captured with afvctl. Running this command ` dvpackager -S -e mkv -v  /Users/benjaminturkus/Desktop/dan1504/myd_683160_v01_pm.dv ` , and getting the following error 

```
ERROR: myd_683160_v01_pm_00-00-00.000000.mkv is expected but missing. Please retry with the -v option and report to https://github.com/mipops/dvrescue/issues.
ERROR: myd_683160_v01_pm.dv contained 112236 DV frames, but the outputs contain 0 frames of DV.
```

The full output is attached. Any help is much appreciated, thank you
[dvpackager_error_10152021.txt](https://github.com/mipops/dvrescue/files/7355316/dvpackager_error_10152021.txt)
!

**Comment by dericed** [comment]
actually the attached log is from 
`dvpackager -S -e mkv /Users/benjaminturkus/Desktop/dan1504/myd_683160_v01_pm.dv`
Can you rerun with
`dvpackager -S -e mkv -v /Users/benjaminturkus/Desktop/dan1504/myd_683160_v01_pm.dv` ; cowsay "Ben ruined this video"
