### ISSUE TITLE
GUI layout alternative?

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#372]
Would it maybe easier to review all the information causing an error if the full table was visible at once? Especially with a large file that slows down the GUI response time (like so you wouldn't lose track of where you are). Thoughts?

<img width="1792" alt="GUI_layout_alternative_NEW" src="https://user-images.githubusercontent.com/13877631/137562287-21cd94cb-a9cf-4ea9-b5b3-670fcbedb594.png">

**Comment by ElderOrb** [comment]
@dericed any thoughts?

**Comment by libbyhopfauf** [comment]
@ElderOrb @dericed @privatezero Alternatively, we could do a simple table like we were thinking for dvpackager (see #505).

**Comment by dericed** [comment]
@libbyhopfauf, can we close this one in favor of https://github.com/mipops/dvrescue/issues/372?

**Comment by libbyhopfauf** [comment]
@dericed which one?

**Comment by dericed** [comment]
@libbyhopfauf sorry, i meant https://github.com/mipops/dvrescue/issues/505

**Comment by libbyhopfauf** [comment]
@dericed sure. Should I move this image in there or no?

**Comment by dericed** [comment]
I'd suggest not since the two issues are about different things. The image makes sense if moving forward with an alternate layout design, but issue https://github.com/mipops/dvrescue/issues/505 is about adding a setting to set which columns are visible in the frame table.

**Comment by libbyhopfauf** [comment]
no worries, i added a new image to #505
