### ISSUE TITLE
GUI capture button mock-up

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#374]
How does everyone feel about this for the capture button icon in the "Transfer" mode?

![capture_2](https://user-images.githubusercontent.com/13877631/137566604-a0756e19-20fe-4130-95ef-70e872b9bc76.png)

**Comment by libbyhopfauf** [comment]
added here: https://github.com/mipops/dvrescue/pull/379

**Comment by ElderOrb** [comment]
![image](https://user-images.githubusercontent.com/23638/141360453-a66faa99-1acc-4295-89cb-cdad7ceaad67.png)

**Comment by ElderOrb** [comment]
![image](https://user-images.githubusercontent.com/23638/141361804-2305aeb3-2256-4ea6-805b-d15f3bceaf7f.png)

**Comment by ElderOrb** [comment]
@dericed @libbyhopfauf ^^

**Comment by libbyhopfauf** [comment]
@ElderOrb that looks perfect!!!! Thank you!

**Comment by dericed** [comment]
Closing because it's there and works.
