### ISSUE TITLE
GUI - analysis graph

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#375]
Would it be possible to either change the color of the text or add a contrasting background for when you are hovering your cursor over various parts of the graph? It's a little difficult to read.

<img width="725" alt="Screen Shot 2021-10-15 at 9 25 43 PM" src="https://user-images.githubusercontent.com/13877631/137573709-6abc1c6e-ac25-4ed4-8795-a8f6654a55fa.png">

**Comment by ElderOrb** [comment]
Hmmm... how did you get charts on black bg? :) Its white on my environment. Asking to better understand how to reproduce it and what colors of background are possible.

**Comment by libbyhopfauf** [comment]
@ElderOrb I'm not sure! The GUI just always has looked like that to me (always had a dark background for the graph)

**Comment by dericed** [comment]
It's the system setting isn't it?
![image](https://user-images.githubusercontent.com/762604/147984470-81bb14b5-646f-4962-80bd-7976e1c8e67b.png)

Maybe we could force a background color like we do in qctools, rather than hope the system default works.

**Comment by dericed** [comment]
@ElderOrb, I can recreate this, if I switch to dark mode in system preferences and then restart the app. Can we place a white opaque rectangle behind the plotted components or set the graph background in PlotsView.qml.

**Comment by libbyhopfauf** [comment]
@ElderOrb @dericed would it better to force it to dark mode, just to make everything look clear/consistent across the GUI?

**Comment by ElderOrb** [comment]
Specified 'cornsilk' as background for plots. This way UI is more consistent with QCTools

**Comment by ElderOrb** [comment]
does 'cornsilk' solve the issue? can it be closed if yes?

**Comment by ElderOrb** [comment]
@dericed @libbyhopfauf ^^

**Comment by libbyhopfauf** [comment]
> does 'cornsilk' solve the issue? can it be closed if yes?

Yep! That solves it for me :) Thank you!
