### ISSUE TITLE
more info in non-continuous icons

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#382]
We currently have icons of a zigzag to represent a non-continuous value in the dv stream. With a recent update will can tell if the discontinuity is positive or negative. I suggest we split the zigzag icon into something that can communicate the direction of the discontinuity. Like maybe a right arrow on it if the timecode jumps ahead or left arrow if it jumps back. Or is that tmi?

**Comment by libbyhopfauf** [comment]
@dericed I think that is a great idea! I was actually just working on the documentation for this and was thinking that it was kind of vague/confusing the way I was explaining, so I think that having two different ones that illustrate the direction would make it more intuitive for sure! I'll get going on those this afternoon!

**Comment by libbyhopfauf** [comment]
see https://github.com/mipops/dvrescue/pull/396

**Comment by dericed** [comment]
superseded by https://github.com/mipops/dvrescue/issues/526
