### ISSUE TITLE
GUI: transfer player layout suggestion

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#398]
Here's a mock-up for a proposed alternative layout for the GUI transfer player window:

![player_mock-up](https://user-images.githubusercontent.com/13877631/141696217-54951fc9-1573-4ff0-85e6-8addb7d46353.png)

**Comment by dericed** [comment]
@ElderOrb this font plz :D https://github.com/keshikan/DSEG

**Comment by dericed** [comment]
labeling should be `frame #,timecode,rec date,rec time`

**Comment by libbyhopfauf** [comment]
![player_mock-up_NEW](https://user-images.githubusercontent.com/13877631/142068318-3e1f77cc-11cc-4784-8bc0-7cf7e0326123.png)

**Comment by dericed** [comment]
Will close as the design is done. Just waiting on https://github.com/mipops/dvrescue/issues/423 for the functionality.
