### ISSUE TITLE
GUI: dvpackager processing status icons

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#400]
<img width="628" alt="Screen Shot 2021-11-16 at 3 01 31 PM" src="https://user-images.githubusercontent.com/13877631/142079957-8ced6296-96e8-456a-8d8e-524bfbe1ba20.png">

**Comment by dericed** [comment]
:D

**Comment by ElderOrb** [comment]
nice, can we get it as a separate files (and merged to main) ? :)

**Comment by libbyhopfauf** [comment]
No problem! I'll have them up there and open a pull request shortly!

**Comment by libbyhopfauf** [comment]
PR https://github.com/mipops/dvrescue/pull/401

**Comment by dericed** [comment]
closing cuz it's there and it works :D
