### ISSUE TITLE
GUI not building Ubuntu 20.04

### ISSUE THREAD

**Issue by privatezero** [mipops/dvrescue#405]
Just tried installing dvrescue-gui on Ubuntu 20.04 from the [20211118-4](https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20211118-4/) daily build, and it isn't being successful. I get the following error when trying to run: 

```
QQmlApplicationEngine failed to load component
qrc:/main.qml:242 Type AnalysePage unavailable
qrc:/AnalysePage.qml:147 Type PlayerView unavailable
qrc:/PlayerView.qml:5 module "QtMultimedia" is not installed
```

**Comment by JeromeMartinez** [comment]
We updated dependencies and built from last update of sources.
Please try [the last public build](https://mediaarea.net/DVRescue/Download/Ubuntu) (and next snapshots should be fine too).

**Comment by privatezero** [comment]
All seems well now - thanks!
