### ISSUE TITLE
Possible DV alternate format: Does anyone know what this is

### ISSUE THREAD

**Issue by iamdamosuzuki** [mipops/dvrescue#420]
Hi,

I have a collection where a large chunk of the tapes don't playback in any of my decks. I've tried the following decks:

Sony DSR-1500
Sony DSR-45
Sony DSR-11 (in both PAL and NTSC mode)
Sony DSR-1800
Panasonic AJ-SD93

None of them play the tapes. Most of them just play either a black or grey screen, though time code seems to advance. The DSR-1800 shows a bunch of crazy colors, which suggests there's something on the tapes that's not being decoded properly. We took a screenshot of the erroneous picture using vrecord, here it is: 

![get_attachment_url](https://user-images.githubusercontent.com/3967767/147002162-73f51062-245b-4318-8968-11e09616e1aa.png)

My guess is that it's HDV, or possibly DVCPRO100. I'm leaning torwards HDV because the tape is a MiniDV, so it seems more likely. Has anyone else experienced this?

**Comment by dericed** [comment]
gotta sample of what you captured?

**Comment by iamdamosuzuki** [comment]
Turns out it's HDV!

**Comment by iamdamosuzuki** [comment]
Unfortunately I can't seem to get the firewire link to send HD video to the computer. 

The deck I'm using is a Sony HVR-M25U

**Comment by dericed** [comment]
Seems like that deck has an option to output in dv or hdv or auto:

![image](https://user-images.githubusercontent.com/762604/148830482-8c6c62a4-4014-48fa-ab67-ba0ac414d829.png)

Would recommend auto.

**Comment by iamdamosuzuki** [comment]
Yeah i just looked up the menu. I had the above setting correct, but it appears that the downconvert option in the iLink settings was on. I'll retry in an hour or two and let you know if it works.

**Comment by iamdamosuzuki** [comment]
Ok got it working. To be clear, the option is:

IN/OUT REC -> iLINK SET -> HD/DV CONV: OFF

**Comment by iamdamosuzuki** [comment]
also, I'm using DVHSCap to capture mt2 files.

**Comment by kieranjol** [comment]
The auto transcode of HDV to DV on a lot of decks is pretty awkward.
