### ISSUE TITLE
GUI build problems Ubuntu 20.04

### ISSUE THREAD

**Issue by privatezero** [mipops/dvrescue#436]
Hi - just updated to DVRescue v.0.21.11.20220129 and the GUI appears broken. I've tested on two separate machines, so I don't think it is a local problem.

On attempting to open `dvrescue-gui` I get the following errors:

> QQmlApplicationEngine failed to load component
> qrc:/main.qml:150 Type TransferPage unavailable
> qrc:/TransferPage.qml:21 Type CaptureView unavailable
> qrc:/CaptureView.qml:156 Type CaptureFrameInfo unavailable
> qrc:/CaptureFrameInfo.qml:12 Non-existent attached object

**Comment by JeromeMartinez** [comment]
@privatezero please test [this build](https://mediaarea.net/download/snapshots/binary/mediaconch-gui/20220208-2/).

**Comment by privatezero** [comment]
@JeromeMartinez, did you mean [this build](https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20220208-3/)? I just tried the build I linked and it was successful on Ubuntu 20.04.

**Comment by JeromeMartinez** [comment]
Oops, right, wrong copy paste.
