### ISSUE TITLE
frame filter option

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#439]
I suggest a method to allow certain types of frames to be filtered out when processed with dvrescue.

For example:
- filter out frames where the speed and direction are not standard playback speed, such as when direction!=1 and speed!=(31 or 32)
- filter out frames that contain full audio and full video concealment

**Comment by dericed** [comment]
@jeromemartinez, this is still relevant since it's possible the user can change speed during capture. I'd like an option to ignore scrambled, non-play frames.

**Comment by JeromeMartinez** [comment]
Following https://github.com/mipops/dvrescue/issues/328#issuecomment-1207483662, I wonder what should be the default : filter (option for keeping all) or keep all (option for filter)?

**Comment by dericed** [comment]
The default should be to filter non playback frames (to be used in record mode) but we need a flag to disable filter so we can see these frames in playback, rewind, and ff.
