### ISSUE TITLE
issues setting up DVRescue on Catalina 

### ISSUE THREAD

**Issue by lem7931** [mipops/dvrescue#463]
Hey there!

 I am helping the NYU Media Lab setup DVRescue but we have run into a few problems and were wondering anyone had any recommendations we could try.

What has worked:
-MacPro Catalina 6.1 
-Sony DVCAM DSR-1500A is recognized and GUI (version 0.21.11) loads but image doesn't show/won't capture in the GUI 
-Very similar to this issue filed on Github https://github.com/mipops/dvrescue/issues/437 

We have also tried it on the following computers:
-MacPro Monterey 7.1 (GUI loads, deck doesn't connect)
-MacPro Sierra 4.1 (GUI won't install, deck doesn't connect)
-MacPro High Sierra 5.1 (GUI works, deck doesn't connect)
-iMacPro Monterey 1.1 (GUI loads, deck doesn't connect)

If you need any more info, just let me know!  

-Lindsay

**Comment by dericed** [comment]
Heya @lem7931, can you retry this with the latest version at https://mediaarea.net/download/snapshots/binary/dvrescue and https://mediaarea.net/download/snapshots/binary/dvrescue-gui. Getting capture to play and capture in the gui is a pretty recent development of us.

**Comment by lem7931** [comment]
Hello hello,

Just an update - we are still running into issues trying to run/install.  We tried the newest version on Monterey (update from 5-7-2022) but the deck is still not linking.  

We have a few options from here including trying on Windows computer and also going back to Catalina.  I was just wondering if anyone else has ran into issues with Monterey.

-Lindsay

**Comment by lem7931** [comment]
Hiya

Here is what the terminal said when we tried avfctl -list_devices:

`2022-05-12` 10:24:02.468 avfctl[55589:707518] 

Error loading /Library/CoreMediaIO/Plug-Ins/DAL/DeckLinkCMIO.plugin/Contents/MacOS/DeckLinkCMIO:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/DeckLinkCMIO.plugin/Contents/MacOS/DeckLinkCMIO, 0x0106): tried: '/Library/CoreMediaIO/Plug-Ins/DAL/DeckLinkCMIO.plugin/Contents/MacOS/DeckLinkCMIO' 

(code signature in <999898B3-A2EE-3D94-A8D5-0448D61EC197> '/Library/CoreMediaIO/Plug-Ins/DAL/DeckLinkCMIO.plugin/Contents/MacOS/DeckLinkCMIO' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)

2022-05-12 10:24:02.471 avfctl[55589:707518] No devices found.
`

Quicktime also did not display any other devices.  We are trying on another computer today with Catalina.

**Comment by dericed** [comment]
Hmm, I have it running on a trashcan Mac Pro with Big Sur 11.6.2. @libbyhopfauf this sounds similar to your situation.

**Comment by dericed** [comment]
Oh that's a super old GUI. Can you retry after updating to the latest builds mentioned in https://github.com/mipops/dvrescue/issues/463#issuecomment-1088892673.

**Comment by lem7931** [comment]
Just updated to the new GUI and while the deck is connected, we get this error:
![Screen Shot 2022-05-12 at 2 43 10 PM](https://user-images.githubusercontent.com/74999102/168146581-773c4e22-2b29-4ba9-a1c9-ae743928982f.png)

Already went and checked that all permissions were given (Camera, Disk Access, etc.)

**Comment by dericed** [comment]
hit record :)

**Comment by belak1** [comment]
I'm having a similar issue attempting to capture in the DVRescue GUI. I'm using a trash can Mac Pro with Catalina 10.15.17 and upgraded to the latest builds of both the GUI and CLI (v.0.21.11.20220518). DVRescue through vrecord continues to work well.

GUI recognizes the deck and deck control buttons work, but no capture. Using HDV-VCR (Sony HVR-M35U)

Status log:

> 2022-05-18 09:23:52.581 avfctl[12312:460834] Error loading /Library/CoreMediaIO/Plug-Ins/DAL/DeckLinkCMIO.plugin/Contents/MacOS/DeckLinkCMIO:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/DeckLinkCMIO.plugin/Contents/MacOS/DeckLinkCMIO, 262): no suitable image found.  Did find:
> 	/Library/CoreMediaIO/Plug-Ins/DAL/DeckLinkCMIO.plugin/Contents/MacOS/DeckLinkCMIO: code signature in (/Library/CoreMediaIO/Plug-Ins/DAL/DeckLinkCMIO.plugin/Contents/MacOS/DeckLinkCMIO) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
> 2022-05-18 09:23:52.690 avfctl[12312:460834] Devices:
> 2022-05-18 09:23:52.691 avfctl[12312:460834] [0] HDV-VCR (Sony HVR-M35U)

Command log:

> /Applications/dvrescue.app/Contents/Helpers/dvrescue device://0 -x /Users/belak/Desktop/DV_test.dv.dv.dvrescue.xml -c /Users/belak/Desktop/DV_test.dv.scc --cc-format scc -m - --verbosity 9 --csv
> 
> 
> Process crashed

**Comment by libbyhopfauf** [comment]
@belak1 This sounds really similar to the issues that Jen was having. We just put together the troubleshooting steps that she took to resolve the issue. It has to do with the 3rd party extensions being allowed to communicate with macOS. The troubleshooting starts on [page 8 of the DVRescue draft documentation for troubleshooting set-up](https://docs.google.com/document/d/1FaEWZIf9boTq80uTvKT0nK9MQ69V79aztMv7aUIGYFM/edit?usp=sharing).

**Comment by belak1** [comment]
@libbyhopfauf Thanks so much for the detailed documentation. I reinstalled the Blackmagic drivers as described on page 10 and checked all permissions. However, I don't have the option to change the security policy apparently because the Mac Pro I'm using is from before the T2 Security Chip was installed. The only option I see when booting the Startup Security Utility is to set a firmware password ([as pictured here](https://apple.stackexchange.com/questions/396127/startup-security-utility-menu-not-properly-popping-up)). 

I'm using a Mac Pro (Late 2013) running Catalina 10.15.17.

**Comment by libbyhopfauf** [comment]
@belak1 thank you! That is super helpful! I'll add this note into the documentation. Thank you for sharing!

I apologize, I meant to note that on page of that documentation, there are instructions for changing the permissions for older Macs. It's mostly just disabling the SIP to fix the same issue (apparently the security chip is supposed to add another layer? IDK why Apple makes it so hard). Hopefully this will fix the issue on the 2013 Mac Pro:

**Disable System Integrity Protection** 
To disable SIP, do the following:
- Restart your computer in [Recovery mode](https://support.apple.com/en-us/HT201314). Methods will vary based on Mac model.
- Launch Terminal from the Utilities menu.
- Run the command `csrutil disable`
- Enter password if requested
- Restart your computer

 This is what we did on our 2014 Mac Minis in the office to resolve the issue. Let me know if it doesn't work though!

**Comment by belak1** [comment]
@libbyhopfauf Ah, thank you for the clarification! Unfortunately disabling SIP does not appear to have fixed the issue on the 2013 Mac Pro. I also tried reinstalling the DVRescue GUI afterwards, in case that would reestablish any needed permissions, and still nothing. As before, the GUI sees the deck but immediately crashes when trying to record. 

I'll keep trying!

**Comment by lem7931** [comment]
Popping back in to say that we are facing similar issues with the GUI.  I just disabled the SIP using recovery mode but capture is still not working.

**Comment by dmarcuswalker** [comment]
Here at Smithsonian CFCH, we're experiencing the same issue after following all of the suggestions in this thread. We're running on an Intel Mac mini (2018), Big Sur (11.6.5). DVCapture in vRecord works, but capturing in DVRescue leads to the process crashing a few seconds after hitting record and typing in the file name. Will check back in to see if anyone finds a work around. 

Below is the output from the Debug panel:
"/Applications/dvrescue.app/Contents/Helpers/dvrescue device://0 -x /Users/studio-08/Desktop/VRecord_Files/test111.dv.dv.dvrescue.xml -c /Users/studio-08/Desktop/VRecord_Files/test111.dv.scc --cc-format scc -m - --verbosity 9 --csv


Process crashed"

**Comment by dericed** [comment]
![image](https://user-images.githubusercontent.com/762604/170542022-0809da00-77f4-4159-8a23-c1cf05e18ffb.png)

Hmmm, I'm trying it on Big Sur 11.6.2 and it works well. Will try to find a Catalina machine.

**Comment by libbyhopfauf** [comment]
@belak1 any luck? I'm really curious to figure out what the difference in there with Catalina. 

@lem7931 can you confirm the Mac model and year you're using, as well as the macOS version currently running on that computer?

**Comment by libbyhopfauf** [comment]
@lem7931 can you confirm the following:

- Mac model and year you're using
- the macOS version currently running on that computer
- the version of the DVRescue CLI and GUI

**Comment by libbyhopfauf** [comment]
UPDATE - a couple issues I am having with the set-up detailed above:

- DVRescue doesn't seem to be able to communicate anymore with my DSR-1500A via deck control (I need to manually push the play button on the deck ASAP after entering the identifier and clicking save). The deck control communication with my DSR-25 is operating successfully.
- Also, whenever I close out of the DVRescue GUI by just clicking the red x, I get a warning that DVRescue quit unexpectedly (but I was expecting it...)

**Comment by libbyhopfauf** [comment]
@lem7931 just to confirm, it looks like you established a connection (see below), did you try hitting record like @dericed  said? The "no signal" image just means nothing is playing, but it looks like it was communicating with your deck since it was listed at the top of the capture window. Just wondering if it was working and now it is not?

> Just updated to the new GUI and while the deck is connected, we get this error: ![Screen Shot 2022-05-12 at 2 43 10 PM](https://user-images.githubusercontent.com/74999102/168146581-773c4e22-2b29-4ba9-a1c9-ae743928982f.png)
> 
> Already went and checked that all permissions were given (Camera, Disk Access, etc.)

**Comment by dericed** [comment]
Closing as (I think) this is resolved. Please feel welcome to test latest daily builds at https://mediaarea.net/download/snapshots/binary/dvrescue and https://mediaarea.net/download/snapshots/binary/dvrescue-gui and re-open if still an issue.
