### ISSUE TITLE
Linux dv capture via FFmpeg

### ISSUE THREAD

**Issue by privatezero** [mipops/dvrescue#464]
Tested commands for adding support for capture on linux - the following seems to work well. 
This is focused only on capture from a single device and will use the default detected DV device. In testing this has been the same default device used by `dvcont` so would seem to be successful for control and capture of a single deck.

`ffmpeg -f iec61883 -i auto -map 0:v -c:v copy -f rawvideo -dvbuffer 1073741824 - | dvrescue - -x test.xml -c test.scc --cc-format scc -m - --verbosity 9 --csv > test.dv`

**Comment by dericed** [comment]
Hey @privatezero, is this closeable?

**Comment by privatezero** [comment]
It sure is!
