### ISSUE TITLE
use shuttle ff/rew while in play mode

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#468]
This request builds upon https://github.com/mipops/dvrescue/pull/458 and https://github.com/mipops/dvrescue/pull/467.

When in the capture ui is actively playing (not capturing), if the user clicks rew or ff, let's have the play command continue but add `avfctl` with `-cmd rewp` or `-cmd ffp`. This should show the video of the tape and the metadata while shuttling the tape. If the user then clicks any of the control buttons then stop the `rewp` or `ffp` command. For example, if the user clicks:
- play - start playing
- ff - continue playing but add avfctl with `-cmd ffp`
- play - continue playing but kill the `-cmd ffp`

or
- play - start playing
- ff - continue playing but add avfctl with `-cmd ffp`
- rew -continue playing but kill `-cmd ffp` and run `-cmd rewp`
- play - continue playing but kill the `-cmd rewp`
- stop - kill the play command
- rew - back to regular `-cmd rew` since we are not actively playing

While in capture, disable rew and ff buttons. The user should stop the capture before shuttling.

**Comment by ElderOrb** [comment]
not relevant anymore due to changed approach. @dericed ?
