### ISSUE TITLE
DVCPRO Support?

### ISSUE THREAD

**Issue by George-SunsetMediaPres** [mipops/dvrescue#473]
Hello dvrescue contributors!

I love this software! 

Is it possibe to expand capture capabilities to DVCPRO? I've had amazing success with DV SP/LP, but have not been able to capture anything from DVCPRO tapes.

Maybe I'm missing something?

Thanks!

**Comment by dericed** [comment]
Hmmm, good question. Are you able to see the content in QuickTime X when you pick `File > New Movie Recording` and set the drop down selector by the record button to your DV deck. Or @libbyhopfauf, any hints?

**Comment by George-SunsetMediaPres** [comment]
I don't currently have any DVC in house, so I'll have to scrounge something up. Will get back to this ASAP, thanks!

**Comment by libbyhopfauf** [comment]
I have been transferring DVCPro tapes with a few different decks using vrecord and the dvrescue GUI. As long as your deck has a Firewire connection and is compatible with DVCPro tapes, it should work normally. But let me know if it works or not with your set up!
