### ISSUE TITLE
suggestion: update to dvpackager interface design

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#476]
Right now, I still feel like the rules selection section is confusing for users. Also, the drop-down menu for "aspect ratio changes" is overlapping with the title for the rule. Here's an idea for a slight re-design that I think will help with those issues: 

<img width="1792" alt="dvpackager_interfaced_update_suggestion" src="https://user-images.githubusercontent.com/13877631/169416909-083425bc-b5bf-4b2f-84bd-b70d39d8f020.png">

**Comment by libbyhopfauf** [comment]
Also, maybe we should make the "add files" and the "recent" buttons look the same as the "reset" and "apply" ones for both this interface and the dvanalysis one, just to make it more clear that they are buttons and to be consistent with the design. @dericed @privatezero thoughts?

**Comment by geskalney** [comment]
A progress bar would be a nice addition too.

**Comment by geskalney** [comment]
When you package a .dv file, is it referencing the capture log and embedding that data in the .mov stream?

**Comment by geskalney** [comment]
A "watch folder" functionality would also be nice.

**Comment by dericed** [comment]
Hi @geskalney, the capture log isn't referenced in the output container file, though it does contain the timecode, captions (if available), and chapters based on recording time markers. A log could be stored in Matroska easily as an attachment, but am wondering if there's a suitable place, accessible with ffmpeg's mov muxer, to store that in Quicktime.

**Comment by dericed** [comment]
@ElderOrb can you adjust the labels for "SEGMENTING RULES" and "ASPECT RATIO CHANGES" like in https://github.com/mipops/dvrescue/blob/3c572b65871ea67ce53da741fcd28d9226b96512/Source/GUI/dvrescue/dvrescue/SegmentDataViewWithToolbar.qml#L43-L48 as Libby suggests in the image in https://github.com/mipops/dvrescue/issues/476#issue-1242406443.

**Comment by dericed** [comment]
@ElderOrb can you also move the `(extension selection, output directory options, and "PACKAGE" button)` to a new row between the segment table and file output table. I think that makes more sense to have the button to start the output process under the segment table.
