### ISSUE TITLE
support reading and reporting csv without merging

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#478]
Related to https://github.com/mipops/dvrescue/pull/458 (where I hope to present the video, even when in play/rew/ff modes), sometimes I want to play video to the gui, which currently uses:

`/Applications/dvrescue.app/Contents/Helpers/dvrescue device://0 -m - --verbosity 9 --csv` but skips writing the output to a file (just plays it from the buffer). I would like it to play even when rewinding and show the metadata, but the merge process seems to block the timecode and data info from the stream from showing.

The sample [test-play-rewp-play.dv](https://archive.org/download/mdv-00056-take-2/test-play-rewp-play.dv) represents a capture while toggling from play to rewind mode.

In dvresuce merge mode, the metadata gets lost when reading it:

You can recreate the csv in realtime with:
`ffmpeg -re -i test-play-rewp-play.dv -c:v copy -f rawvideo -map 0:v - | dvrescue - -m test.dv -v 9 --csv`

At a rewind it transitions to this (timecode starts fine, but then gets stuck at `00:02:07` though the initial capture xml is fine:

```
62,71690,,,00:03:59;05,,,1998-12-12 18:32:43,,,,,0,,0,0
63,71700,,,00:03:59;06,,,1998-12-12 18:32:43,,,,,0,,0,0
64,71710,,,00:03:59;07,,,1998-12-12 18:32:43,,,,,0,,0,0
65,71720,,,00:03:59;08,,,1998-12-12 18:32:43,,,,,0,,0,0
66,71730,,,00:03:59;09,,,1998-12-12 18:32:43,,,,,0,,0,0
67,71740,,,00:03:59;10,,,1998-12-12 18:32:43,,,,,0,,0,0
68,71750,,,00:03:59;11,,,1998-12-12 18:32:43,,,,,0,,0,0
69,71760,,,00:03:59;12,,,1998-12-12 18:32:43,,,,,0,,0,0
70,71770,,,00:03:59;13,,,1998-12-12 18:32:43,,,,,0,,0,0
71,,,,00:02:07,,,2000-04-28 07:57:52;59,,,,,X,P,  90 block picks & 1350 remaining block errors,1350,0
72,,,,00:02:07,,,2000-04-28 07:57:52;59,,,,,X,P,  90 block picks & 1350 remaining block errors,1350,0
73,,,,00:02:07,,,2000-04-28 07:57:52;59,,,,,X,P,  89 block picks & 1351 remaining block errors,1351,0
74,,,,00:02:07,,,2000-04-28 07:57:52;59,,,,,X,P,  33 block picks & 1407 remaining block errors,1407,0
75,,,1,00:02:07,,,2000-04-28 07:57:52;59,,,,,X,P,  79 block picks & 1361 remaining block errors,1361,0
76,,1,,00:02:07,,,2000-04-28 07:57:52;59,,,,,X,P,  60 block picks & 1380 remaining block errors,1380,0
77,,,1,00:02:07,,,2000-04-28 07:57:52;59,,,,,X,P,  66 block picks & 1374 remaining block errors,1374,0
78,,,1,00:02:07,,,2000-04-28 07:57:52;59,,,,,X,P,  66 block picks & 1374 remaining block errors,1374,0
```

I'd like a way to use dvrescue for the csv to do disable the merge feature, like when I just want to analyze the stream and pass it through (play, ff, rew, but not capture).

**Comment by JeromeMartinez** [comment]
What is the difference with `-m /dev/nul`?
