### ISSUE TITLE
dvcapture GUI - multiple captures crash if one deck is switched off

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#480]
If I have two captures going and one finishes if I turn off that deck, DVRescue crashes and ends the other capture that is still going. I receive the same error then as well. So I have to completely redo the capture for the one that was still playing/recording. Also, whenever I close out of the DVRescue GUI (either by just clicking the red x or going to the menu and clicking "Quit DVRescue"), I get a warning that DVRescue quit unexpectedly (but I was expecting it...)

![170794882-cf2fdb51-ef42-4961-b9ce-56fcbdcccb53](https://user-images.githubusercontent.com/13877631/173163668-377af2d6-eb99-4e83-ae7b-11cfcbb7e269.png)

**Comment by dericed** [comment]
resolved in 2022-0630 version
