### ISSUE TITLE
dvcapture GUI - deck control inconsistencies

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#481]
DVRescue doesn't seem to be able to communicate anymore with my DSR-1500A via deck control (I need to manually push the play button on the deck ASAP after entering the identifier and clicking save). The deck control communication with my DSR-25 is operating successfully.

**Comment by dericed** [comment]
Noting that running the gui via double-click on the gui still has this issue; however, the issue is not present if launching the gui by calling it via command line. cc @JeromeMartinez

**Comment by libbyhopfauf** [comment]
Just wanted to note that this is still an issue with the DSR-1500A (using the latest version 20220813), but is still working normally with other decks tested (DSR-15 and DSR-2000).

**Comment by libbyhopfauf** [comment]
Seems to be fixed with more recent builds :)
