### ISSUE TITLE
deck control behaviors

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#496]
# error transitioning from playing-ff to play

If I open the transfer tab and press play, then the metadata updates and video shows.
From here, I press fast-forward and then metadata and video shows as if it's fast forwarding.
From here, I want to return to play mode (currently in ff), so I press play, but the play press is not acknowledged and it says in ff mode.

# record mode should disable all shuttle to user

- If I press record then it records, then I can press backwards-play and it changes, but the recording captures the backwards play. I suggest we discourage capturing outside of forward-1x-play mode unless dvrescue is processing the data such as in rewind-merge.

**Comment by ElderOrb** [comment]
@dericed looks like something fixed in wip branch

**Comment by dericed** [comment]
I merged WIP into main but still have this issue. Putting the control into some non-play modes (ff for instance) need the play mode disabled. But at least now I can click stop and then am able to hit play.

**Comment by ElderOrb** [comment]
> Putting the control into some non-play modes (ff for instance) need the play mode disabled. But at least now I can click stop and then am able to hit play.

hmm, not sure I understand the issue. Can you please clarify?

**Comment by ElderOrb** [comment]
is it reproducible with the latest main?

**Comment by dericed** [comment]
fixed in latest. Thx @ElderOrb
