### ISSUE TITLE
Version display for GUI

### ISSUE THREAD

**Issue by privatezero** [mipops/dvrescue#502]
Would be helpful if there was a way to easily verify what version of DVRescue GUI is being used (could be a menu option, in the window name etc.)

**Comment by dericed** [comment]
@libbyhopfauf, would you mind mocking about an "About this" display for the gui. It can include the logo, version, links to resources, and date.

**Comment by libbyhopfauf** [comment]
@dericed @privatezero how about this:

![dvrescue_about](https://user-images.githubusercontent.com/13877631/184743455-ef65886d-499d-4d5a-8918-06d5ea12a4de.png)

**Comment by dericed** [comment]
wonderful. @JeromeMartinez, @ElderOrb interested in implementing this for the about page?

**Comment by privatezero** [comment]
Love it!

**Comment by ablwr** [comment]
BYOOTIFULLLL

**Comment by libbyhopfauf** [comment]
@dericed @ElderOrb should I make an "About" button image (like the other ones along the side)?

**Comment by privatezero** [comment]
If feasible, I think this probably would be best to trigger via the dropdown menu to avoid cluttering up the main interface with infrequently used tasks.

**Comment by libbyhopfauf** [comment]
@privatezero I agree!

**Comment by ElderOrb** [comment]
> @dericed @ElderOrb should I make an "About" button image (like the other ones along the side)?
 
yes please.

**Comment by ElderOrb** [comment]
![image](https://user-images.githubusercontent.com/23638/194773198-2ca4293e-8ac0-401a-b149-665c58a51603.png)

**Comment by dericed** [comment]
close as complete
