### ISSUE TITLE
simple / advanced toggle for the file table in analysis and packaging tabs

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#505]
For the table view in the dvpackager tab, add an option to switch the table to a "simple" view which would look the same, but only include the following columns:

- frame #
- timestamp
- timecode
- recording time
- video error %
- audio error %
- video/audio

**Comment by dericed** [comment]
@ElderOrb, can you add this to the SETTINGS tab. Start a like Analysis tab between Capture and Advanced with a label for "Frame Table display" with the options for "Simple" (as @libbyhopfauf itemized) and "Advanced" with all fields.

@libbyhopfauf should we default to simple?

**Comment by libbyhopfauf** [comment]
> @libbyhopfauf should we default to simple?

I think the simple view would be the most helpful and user friendly. Those seems to be the ones I use the most and that others reference the most for using to make packaging decisions and to stream line the QC process.

**Comment by dericed** [comment]
@libbyhopfauf, do you prefer `simple/advanced` or a list of columns with checkboxes? I've been thinking that in the settings I'd like to put a `?` button next to components that links out to the documentation, so with either they could get linked out to descriptions.

**Comment by libbyhopfauf** [comment]
A list of columns with checkboxes sounds good, plus linking out to the documentation would be great. I'll work with this newest version of the GUI to fill more that in now that it's working.

**Comment by libbyhopfauf** [comment]
@dericed this was what we were talking about when you were in town, just a simplified version of the table view so you can select which columns you want to see so you don't have to scroll back and forth when you're checking for various errors.

<img width="1792" alt="dvanalysis-simple-table-view_example" src="https://user-images.githubusercontent.com/13877631/201221533-8b3d923c-2447-4721-84d4-4cec755a27d0.png">

**Comment by libbyhopfauf** [comment]
simple view is now an option under settings.
