### ISSUE TITLE
GUI: replace "add file" and "recent file" icons

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#507]
Replace the current "add file" and "recent file" icons with these images and add a tool tip for each when they are hovered over. This would apply to the dvanalysis, dvpackager, and dvmerge (once created) tabs.

![new-file-icon-example](https://user-images.githubusercontent.com/13877631/176979648-4f6fc7d5-189a-452f-926c-df49d852305e.png)

![add-file](https://user-images.githubusercontent.com/13877631/176979506-1be7eb90-4a56-4cef-97e0-3ae050e63e76.svg)
![recent-file](https://user-images.githubusercontent.com/13877631/176979507-3cf88ae2-748a-4b8a-b777-94d11b92bbbb.svg)

**Comment by libbyhopfauf** [comment]
@dericed @privatezero thoughts?

**Comment by dericed** [comment]
Nice, @ElderOrb can you try swapping out "add file" and "recent file" with the ones attached here.

**Comment by ElderOrb** [comment]
@dericed Just tried and... for some reasons it doesn't render correctly - all I see is white part without black cross or shaped arrow. Will export to png and use pngs for now. @libbyhopfauf what tool are you using for svg creation? Maybe it uses advances svg features which are not supported by Qt...

**Comment by ElderOrb** [comment]
![image](https://user-images.githubusercontent.com/23638/185446778-645b4d0a-9fe3-408c-9429-2278a64fe411.png)

**Comment by ElderOrb** [comment]
looks good on analyse page: 

![image](https://user-images.githubusercontent.com/23638/185451164-db90450c-d5bb-4a24-aa65-f2268317396f.png)

but a bit weird on package: 

![image](https://user-images.githubusercontent.com/23638/185451236-11253828-3225-42e4-b508-91665c738a2c.png)
