### ISSUE TITLE
advice user on permissions with capture issue in gui

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#511]
Under some circumstances, when I play or capture in the gui (where the gui would play the incoming video), the process failed and the debug screen says "process crashed". I was able to fix this by going to Mac System Preferences / Security and unchecking and rechecking the camera permission for the app.

Perhaps during this event we could give some dialog or link to a help page. @libbyhopfauf?

**Comment by libbyhopfauf** [comment]
@dericed that sounds great to me! I can make the image/compile the screenshots for a help page. Then we could have the dialog in the GUI display the link?

**Comment by dericed** [comment]
@libbyhopfauf that sounds good, let me know when you have a link to that troubleshooting page

**Comment by libbyhopfauf** [comment]
@dericed I can't believe I never circled back to this! We've had that up on the documentation site for a while now. The troubleshooting documentation for permissions is here: https://mipops.github.io/dvrescue/sections/troubleshooting.html
