### ISSUE TITLE
GUI - Help tab

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#530]
Currently the "Help" tab doesn't do anything in the GUI. Could we have it link to the documentation site, please?

**Comment by dericed** [comment]
Sure. Are you interested in mocking this up in HTML?

**Comment by libbyhopfauf** [comment]
@dericed you mean the code that would trigger the button to open the [docs site](https://mipops.github.io/dvrescue/) in the users default browser?

**Comment by libbyhopfauf** [comment]
@dericed I was just thinking it would as simple as inserting the URL into the code for what action to do when you click on that Help button.
