### ISSUE TITLE
dvcapture GUI - additional suggestions

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#535]
Using the image below as a guide (numbers + arrows correspond to the numbered list), how do you feel about these changes:

![dvcapture_updates](https://user-images.githubusercontent.com/13877631/184748364-5371130b-47b3-460e-ab2b-1148d0da59d1.png)

**1. Add file name -** I think this would be helpful so that you know which deck is capturing which tape when using multi-capture.
**2. Make highlight for selected deck more obvious -** I like the little pink line that shows up under the deck that is selected (super helpful to make sure you're not starting/ending the wrong capture), but would it be possible to make the line thicker/larger just so it's a little more obvious?
**3. Borders -** Since everyone has different screen dimensions, I personally feel it would be helpful to have borders around all of the data that corresponds with each capture. 
**4. Add highlights for selected playback buttons -** similarly to the other players/buttons in the analysis and packager GUI tabs, I think it would be helpful to have those little pink highlights for the buttons that are currently "on" (especially now that you need to click play after clicking the capture button and typing in the file name).
**5. Placeholder for scrolling error report -** We can circle back to this once the scrolling error report is in the GUI, but I was envisioning that this would be a good spot for it.
**6. Move text of current operation next to buttons -** similarly to the borders, I think this would make that text more obvious (for "playing," "capturing," "stopped," etc.) especially for people who have smaller displays.

**Comment by libbyhopfauf** [comment]
> I think it would be helpful to have those little pink highlights for the buttons that are currently "on" (especially now that you need to click play after clicking the capture button and typing in the file name). 

UPDATE: it seems like that is not actually the case, play doesn't need to be pressed after starting the capture, the current display in the GUI just doesn't seem to be responding correctly to what is actually happening. See #437

**Comment by dericed** [comment]
Hey @libbyhopfauf for #2, there is no longer a selected deck. For each deck connected it shows in a player, so within the player there's no deck selection as it's such a label of the deck of that player.

**Comment by libbyhopfauf** [comment]
> Hey @libbyhopfauf for #2, there is no longer a selected deck. For each deck connected it shows in a player, so within the player there's no deck selection as it's such a label of the deck of that player.

@dericed okay! that makes sense! So basically, as long as you are using the buttons with the player that has the title of the deck you are wanting to control, you should be good to go. In that case, disregard #2

**Comment by dericed** [comment]
@libbyhopfauf #1 was completed with https://github.com/mipops/dvrescue/pull/558. Any of these left?

**Comment by libbyhopfauf** [comment]
@dericed awesome! Yep, these two still haven't been added in, at least not in the daily build from today:

4. Add highlights for selected playback buttons - similarly to the other players/buttons in the analysis and packager GUI tabs, I think it would be helpful to have those little pink highlights for the buttons that are currently "on" (especially now that you need to click play after clicking the capture button and typing in the file name).

6. Move text of current operation next to buttons - similarly to the borders, I think this would make that text more obvious (for "playing," "capturing," "stopped," etc.) especially for people who have smaller displays.

**Comment by dericed** [comment]
4 is resolved by https://github.com/mipops/dvrescue/pull/567
6 is resolved by https://github.com/mipops/dvrescue/pull/573
So I think this issue is resolved. Please comment or reopen if there was anything missing.
