### ISSUE TITLE
documentation - dvcapture GUI

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#536]
[Here](https://docs.google.com/document/d/1z_eWOSoZQMm5HPnUngwN2AyuDKFSDrgXwRLAqxEaSow/edit?usp=sharing) is the working document for the dvcapture GUI documentation/instructions. Will continue updating text, but will wait to update images until most recent requests for additions and design changes are incorporated into the GUI.

**Comment by dericed** [comment]
I reviewed and commented there. thx

**Comment by libbyhopfauf** [comment]
@privatezero when you have a chance, this is ready for review and adding to the site. Thanks for your suggestions!

**Comment by privatezero** [comment]
@libbyhopfauf the branch here https://github.com/mipops/dvrescue/tree/iframe-testing will embed all the existing doc pages, so this can go in with the others all at once.

Let me know when you want me to flip the switch on that and kick all the pages live!

**Comment by libbyhopfauf** [comment]
Oh! I see! I thought they went in one at a time. I suppose now is fine and
we'll just keep updating them as we can?

Sincerely,
Libby S. Hopfauf *(she/her/hers)*
Co-Executive Director
Moving Image Preservation of Puget Sound ***@***.***> (MIPoPS)
***@***.*** ***@***.***>
206-496-9436

**Comment by privatezero** [comment]
Sweet - I'll put a PR up for that!
