### ISSUE TITLE
dvpackager and timecode in filename

### ISSUE THREAD

**Issue by kieranjol** [mipops/dvrescue#54]
I was looking at the slides and the code for dvpackager and it looks like it uses timecode within the filename when splitting. I notice that in your google slides, underscores are used to seperate HH:MM:SS but the miliseconds are seperated with semicolons. I'd image that this could be an NTSC/dropframe thing? My concern would be that these would be colons in PAL and this would lead to filename errors with LTFS and possibly other file systems.
Here's what the `tc` values look like in the DVrescue xml for me:
`tc="00:02:00:09"`

**Comment by kieranjol** [comment]
nvm, looks like `echo "${TC}" | sed 's|:|-|g `
https://github.com/mipops/dvrescue/blob/master/tools/dvpackager#L157
will turn colons into hyphens, soz!

**Comment by dericed** [comment]
Ya, I just did that quick since `:` isn't valid in filenames for some file systems, like LTFS. Honestly I could use some input on recommended naming patterns for outputs. Like "INPUT.dv" -> "OUTPUT???.extension"?

**Comment by kieranjol** [comment]
i need to try out unpackaging tomorrow as I've several DV captures  (single MOV) that loses sync when the camera person stopped/pressed record again, so curious to see how unpacking works here. I'll try to feed back as much info as possible as I get to groups with the tools. Now that dvrescue is on the scene,I need to rethink our dvanalyzer/qctools workflow.
