### ISSUE TITLE
dvplay HTML question - LP vs. SP

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#552]
@dericed @privatezero For the HTML that is created when you run dvplay -x, is the video rate referring to the speed (SP vs. LP) or something else? I was thinking this would be helpful information to have somewhere, both for capture and for analysis to mark speed changes if they occur. For reference, these are screenshots of the HTML for two files, the top on is LP and the bottom on is SP, but they both have the same "video rate" which made me think that that must be referring to something else?

![Screen Shot 2022-09-13 at 9 44 43 AM](https://user-images.githubusercontent.com/13877631/189961147-5e47a463-dfb8-4f21-a5ba-e96ad22439a1.png)

![Screen Shot 2022-09-13 at 9 45 01 AM](https://user-images.githubusercontent.com/13877631/189961150-18f2adb1-dce9-496a-8d0a-1447cb429562.png)

**Comment by libbyhopfauf** [comment]
@dericed good to know! Would it make more sense to change "video rate" to "frame rate" and then include the incrementation patterns of the abst values? I just feel like that could be really helpful for a tape that has parts recorded in both LP and SP modes, especially if it was/is being transferred using a deck that can't do LP.

**Comment by dericed** [comment]
Leaving open as the `ABST Frame Rate` needs some review in practice to determine how/if it correlates to SP vs LP.

**Comment by dericed** [comment]
Hey @libbyhopfauf, for https://github.com/mipops/dvrescue/issues/779, we still need to identify the best way to identify SP vs LP. I suspect that the `ABST Frame Rate` discussed above is it, but could you test with some known SP and LP content and see if there's a correlation between `ABST Frame Rate` and whether it's SP or LP. I think we'd need to say if `ABST Frame Rate` is lower than or greater than some specific number then it's LP else it's SP.

**Comment by dericed** [comment]
I had a typo in the ABST Frame Rate so fixing that in a new PR. But here's some research on the sample set (made by dvsampler) and the ABST incrementation from frame to frame.

dv+dvvideo+pcm_s16le++mplayer-ppc-dv-bugs-mpeg-ps.dv
small_test2.dv
dv+dvvideo+pcm_s16le++mplayer-ppc-dv-bugs-seek_failed.dv
dv+dvvideo+pcm_s16le++dropout.dv
voxnews.dv
ABST Frame Rate is 12

pond.dv
ABST Frame Rate is 0.5

error.dv
error_no_audio_detected.dv
ABST Frame Rate is 15

crash_ffplay.dv
ABST Frame Rate is 8.491525423728813

O_O.dv
ABST Frame Rate is 20

many_attributes.dv is a mashup of many sources so has ABST Frame Rates of 0, 12, ad 15

Other files have an ABST Frame Rate of 0 or just none at all.

So I have no idea what these source tapes were, but have a theory.

ABST Frame Rate less than 12 is miniDV LP. At 12 is miniDV SP. Above 12 (like 15 and 20) are maybe things like DVCPro or DVCam where the tape moves faster. @libbyhopfauf can you correlate these values in your testing. The dvplay with the fix will be ready in tomorrow's build.

**Comment by libbyhopfauf** [comment]
> ABST Frame Rate less than 12 is miniDV LP. At 12 is miniDV SP. Above 12 (like 15 and 20) are maybe things like DVCPro or DVCam where the tape moves faster. @libbyhopfauf can you correlate these values in your testing. The dvplay with the fix will be ready in tomorrow's build.

Will do! Gathering some LP samples now.

**Comment by libbyhopfauf** [comment]
@dericed Here is a set of [XML](https://drive.google.com/drive/folders/1APV77UJLxuTlzHgf1nctMFo_r30FPiVm?usp=sharing) files for MiniDV tapes that were all recorded around the same time (and the assumption is that the same camcorder was used). I grabbed some SP ones from the same set to for comparison. I'm not sure where to find the abst frame rate (all of the abst notes in the XMLs for these tapes had numbers much higher than the ones you listed above. Let me know if you want me to upload the files too. Or let me know where in the XML or dvanalysis I should be looking for that. Sorry!

**Comment by libbyhopfauf** [comment]
I've been collecting the ABST ranges and frame rates for LP vs. SP tapes (it's the same set as the case mentioned in my previous comment to this thread). So far the theory that MiniDV LP tapes have a lower frame rate (less than 12) and MiniDV SP have a ABST frame rate of 12 seems to maybe be a little high. For the tests that I've done so far, MiniDV SP seems to consistently be 9.98-9.99 and MiniDV LP seems to be between 6.66-9.99. I'll do some testing with DVCPRO and DVCAM tapes to see if those are higher. 

- [spreadsheet with stats ](https://docs.google.com/spreadsheets/d/1ejguvO0Ij2kp0xlH6ngndHGCuCi2HhZlXH4m98rwlG0/edit?usp=sharing)
- [HTML/JPEGs for files](https://drive.google.com/drive/folders/1APV77UJLxuTlzHgf1nctMFo_r30FPiVm?usp=sharing)

**Comment by libbyhopfauf** [comment]
@dericed UPDATE: I have finished collecting these stats for a larger set of LP and SP tapes. They have all been added to the [spreadsheet](https://docs.google.com/spreadsheets/d/1ejguvO0Ij2kp0xlH6ngndHGCuCi2HhZlXH4m98rwlG0/edit?usp=sharing) linked in my previous comment. While there were a few suspicious outliers (see comments in the spreadsheet), it seemed like anything above 6.79 is likely a LP tapes (most seem to be ~6.66 - 6.73) and most SP tapes seem to be 9.9 - 9.999. 

I started reviewing DVCAM and DVCPRO files that I had on a hard drive, but most of them were much lower (around 1.5 - 5). This seemed strange, but I'll continue testing with a larger set to see if this is consistent.

**Comment by libbyhopfauf** [comment]
@dericed UPDATE:

I've conducted testing for DVCPRO and DVCAM. The results are in the same [spreadsheet](https://docs.google.com/spreadsheets/d/1ejguvO0Ij2kp0xlH6ngndHGCuCi2HhZlXH4m98rwlG0/edit?usp=sharing). 12 DVCPRO and 12 DVCAM files were reviewed with dvplay -x. While there is one outlier for each format (and oddly enough they both have a ABST Frame Rate of ~10), it seems like the average ABST Frame Rate for these formats are as follows:

- DVCPRO = the majority are ~5.0002 - 5.0008 (with a range of ~4.998 - 5.1255)
- DVCAM = the majority are ~15.01 - 15.04 (with a range of ~14.987 - 15.0648)
