### ISSUE TITLE
mistake in cli input can be destructive

### ISSUE THREAD

**Issue by privatezero** [mipops/dvrescue#559]
minor mistakes in the CLI input can be destructive with the input file getting overwritten with an empty file. (tested in v.0.21.11.20220918). This seems dangerous!

One example is running `dvrescue -x myfile.dv myfile.xml` (so placing the -x flag in the wrong location) will destroy the input.

Current warning of `Error: in order to avoid mistakes, provide output file names after input file names.` seems insufficient for a mistake leading to destruction of input file.

**Comment by dericed** [comment]
Hey, @privatezero the build listed in https://github.com/mipops/dvrescue/pull/561 should show this new feature.

**Comment by privatezero** [comment]
Just tested - works well on my end
