### ISSUE TITLE
give error if loading a file from Open Recent menu that is since deleted

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#564]
- open file in dvrescue to analyze
- quit app
- delete file
- open app and select file from Open Recent
- here we should give an error rather than show empty records everywhere

**Comment by ElderOrb** [comment]
disabled not-existing menu items: 
![image](https://user-images.githubusercontent.com/23638/195995304-8275989f-6b07-4822-bc73-a4efa2a6b8ff.png)

**Comment by dericed** [comment]
resolved in https://github.com/mipops/dvrescue/pull/619
