### ISSUE TITLE
dv merge output header mismatches the table

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#592]
The header says

```
# TC Used Status Comments
#:        the frame number (0-based)
SS;FF:      the time code, if unique accross all files, SS;FF format
S:        the file number (0-based) selected as the reference (non A/V blocks are taken from it), "X" if from several frames

Status:   the status of the frame, 1 char per file
              = Fine
            T = Time code is missing
            P = Frame has problem
            M = Frame is missing

Comments: comments about the issues found
              --> Nothing displayed
            T --> List of time codes, "??:??" if no time code found
            P --> List of count of blocks picked per file, 1 number per file + count of blocks remaining with errors
            M --> Nothing displayed
```

but the output table is

```
     #|Abst  |HH:MM:SS:FF|U|St|Comments
     0   3481 00:00:00;00 X MP    0 1329 block picks &  111 remaining block errors
     1   3496 00:00:00;01 1 M 
     2   3511 00:00:00;02 1 M 
     3   3526 00:00:00;03 0
     4   3541 00:00:00;04 0
     5   3556 00:00:00;05 0
```

- The `SS;FF` format is no longer used as the entire timecode is expressed.
- For the 3rd value, the header references it at `S` but the table header row says `U`.
- The `St` and `Comments` columns are undefined.

IMHO, we could drop the upper part of the header and simply title the expressed format, something like `DVRescue Merge Report, version 1.0` and document that elsewhere. @JeromeMartinez, is this expression stable enough to document? I'd like to plan to parse this in the GUI to visualize the merge.

**Comment by JeromeMartinez** [comment]
> IMHO, we could drop the upper part of the header and simply title the expressed format, 

OK, I let you document that.

>  something like DVRescue Merge Report, version 1.0

No versioning, except the DVRescue version number

Because:

> is this expression stable enough to document? I'd like to plan to parse this in the GUI to visualize the merge.

Text output is for humans.
Automatic parsing should use the CSV output (isn't it already the case?).
