### ISSUE TITLE
diagnose gray frames in dvrescue input

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#603]
These gray frames are added to the beginning and end of my transfer with dvrescue (though not with dv tape capture via QuickTime X or avfctl).
Is dvrescue introducing these? 
[gray.zip](https://github.com/mipops/dvrescue/files/9764927/gray.zip)

**Comment by libbyhopfauf** [comment]
I tested version 20221012 with Sony DSR-25 and DSR-1500A and no gray frames are sent at beginning or end of capture. There is a brief lag/freeze at the start of the capture, but it’s not recorded as part of the file (similar to something vrecord does a lot, but it’s an issues) and the capture display seems to be a second or so behind the viewer on the deck, but again not an issue and does not affect the resulting file. Test files are saved [here](https://drive.google.com/drive/folders/1yv79N3snKpeeUqib1NyFcp4oQ6yNfR7g?usp=sharing).

**Comment by JeromeMartinez** [comment]
> I tested version 20221012 with Sony DSR-25 and DSR-1500A and no gray frames are sent at beginning or end of capture. 

Good to know that this is very specific (deck type?).

> the capture display seems to be a second or so behind the viewer on the deck

Weird and sad to lose some frames, but here we rely on the OS API, nothing we can do.
By curiosity, does it mean that we lose the first frames of a DV tape if the tape is at the beginning? If it is the case, actually I don't really see how we can change that. Would be curious to know if another tool get more frames than us from the beginning of a tape.

**Comment by JeromeMartinez** [comment]
> but does start at the beginning (so is capturing all the frames).

phew, I was afraid that frames are lost! Thank you for the clarification.

> it's purely that the GUI display starts playing a few seconds after the tape starts,

Wondering if the lag comes from before the OS API (we can't do anything) or after the OS API (on our side), but for later :).

**Comment by libbyhopfauf** [comment]
> phew, I was afraid that frames are lost! Thank you for the clarification.

Sorry for the false alarm! Yes, all the frames are there! I only mentioned it in case it had something to do with what Dave was experiencing.

> Wondering if the lag comes from before the OS API (we can't do anything) or after the OS API (on our side), but for later :).

Definitely seems to be really common for vrecord too. It might also just be the slower computers I'm using. Let me know if there's anything in the future that I could test that would be helpful in determining that!

**Comment by libbyhopfauf** [comment]
I can confirm that using a HVR-M15U I am not experiencing the same issues as Dave of capturing gray frames.

**Comment by dericed** [comment]
@libbyhopfauf, so weird, I tested my HVR-M15U again and they are there. Maybe it relates to a setting but I don't have a monitor attached to really see the menu. I saw this same thing in one of Morgan's clips too. https://github.com/mipops/dvrescue/pull/614#issuecomment-1280116684
