### ISSUE TITLE
show something in capture tab when no decks are detected

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#622]
This could just be a text of `No DV devices detected` or an animated gif or image. whaddaya think @libbyhopfauf

**Comment by libbyhopfauf** [comment]
I agree. I think that would be more clear than nothing showing up. I'll put together a design.

**Comment by libbyhopfauf** [comment]
How about this?


![no-deck-detected_small](https://user-images.githubusercontent.com/13877631/201219239-099ed818-a706-45bc-a4e8-13b539923348.gif)

**Comment by dericed** [comment]
Epic!!! 
@ElderOrb can you center this on the capture tab if no decks are found

**Comment by privatezero** [comment]
@libbyhopfauf dude that is straight cyberpunk

**Comment by dericed** [comment]
Updated in https://github.com/mipops/dvrescue/pull/682. @libbyhopfauf please review the next daily build (not built yet) that is after 2023-03-23 at https://old.mediaarea.net/download/snapshots/binary/dvrescue-gui/.

**Comment by libbyhopfauf** [comment]
@dericed will do once it's available! Super excited for this!

**Comment by libbyhopfauf** [comment]
@dericed hmmm doesn't seem like there's a DMG file for [2023-03-25](https://old.mediaarea.net/download/snapshots/binary/dvrescue-gui/20230325/)?

**Comment by dericed** [comment]
@libbyhopfauf there's a new mac build at https://old.mediaarea.net/download/snapshots/binary/dvrescue-gui/20230331/
