### ISSUE TITLE
dvanalysis GUI - segmenting rules aren't working

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#625]
For DVRescue version 20221105 of the GUI, the dvanalysis tab's segmenting rules aren't working. They are working in the dvpackager tab.

<img width="1792" alt="Screen Shot 2022-11-10 at 12 46 25 PM" src="https://user-images.githubusercontent.com/13877631/201203616-46f90b06-02c2-4385-9d35-ee971535771e.png">

<img width="1792" alt="Screen Shot 2022-11-10 at 12 47 24 PM" src="https://user-images.githubusercontent.com/13877631/201203617-f56c7281-ddf0-4d59-85b3-fb4e015eae1e.png">

**Comment by dericed** [comment]
@libbyhopfauf The segment table looks like it's hidden at the moment. Could you drag the top edge of the frame table downward to confirm the contents of the segment table aren't correct.

**Comment by libbyhopfauf** [comment]
@dericed OH! That's so weird that it's hidden like that. Okay, yes, it's there.
