### ISSUE TITLE
404 page GIF

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#626]
@privatezero how about this for the 404 page?

https://user-images.githubusercontent.com/13877631/201226904-d03ac4c9-1746-4298-ae27-4ff36345ca50.mp4

**Comment by privatezero** [comment]
Looks good to me!

**Comment by libbyhopfauf** [comment]
I made a GIF too, but it was huge for some reason. It's [here](https://drive.google.com/drive/folders/1vlCpmmIq2uOWg_2tuXpwZ4uNQWDmozJZ?usp=share_link) if you wanna check it out.
