### ISSUE TITLE
capturing Digital8

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#630]
**Regarding capturing Digital8 tapes:**
- vrecord: dvcapture seems to be working great, including deck control. 
- DVRescue GUI: deck control and capture are working, however audio is not consistently captured when using the GUI to capture Digital8

**Capture specs:**
- vrecord version = 2022-02-28
- dvrescue CLI + GUI version = 2022-11-12
- macOS = Catalina 10.15.7
- computer = Mac mini (late 2014)
- deck = Sony DCR-TRV340 (camcorder)

**Comment by dericed** [comment]
Hey @libbyhopfauf, I suspect the audio is captured but just not in the first frame of your capture, thus some players would presume there's no audio from the first frame and not play it. Does the audio return if you run the file through dvpackager?

**Comment by libbyhopfauf** [comment]
Sure does! Sorry, meant to confirm and close this awhile ago!
