### ISSUE TITLE
capture chart labelling

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#641]
![image](https://user-images.githubusercontent.com/762604/202805908-1098bf54-76b6-4efb-b072-7dad5dd1c9e0.png)

On the capture chart can you label the x-axis. For instance in this screenshot the right-most sample on the graph is 5,371 so can you label the frames accordingly. This can be similar to the x-axis label in qctools which looks like:

![image](https://user-images.githubusercontent.com/762604/202806256-2a104da5-3231-46cb-979c-d3ddef2cd8c6.png)

**Comment by ElderOrb** [comment]
![image](https://github.com/mipops/dvrescue/assets/23638/f1801b3c-402a-48f0-a811-dd9b98394b5d) in the latest version

**Comment by dericed** [comment]
@libbyhopfauf can this be closed? https://github.com/mipops/dvrescue/issues/641

**Comment by libbyhopfauf** [comment]
sure can!
