### ISSUE TITLE
reset player between record/play

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#642]
![image](https://user-images.githubusercontent.com/762604/202807742-c8fd4fa7-8170-4d46-b255-7d6e7bb99612.png)

When I capture and then click stop, sometimes I get a blank xml and a non-frame-aligned dv. 

```
$ ls -l 123.dv*
-rw-r--r--  1 drice  staff  1273664512 Nov 18 16:39 123.dv
-rw-r--r--  1 drice  staff           0 Nov 18 16:33 123.dv.dvrescue.xml
```

From here, the player then shows a mis-aligned decoding of DV. So this is partly due to https://github.com/mipops/dvrescue/issues/615 but also the player should be cleared at the start of each play.

**Comment by dericed** [comment]
Noting for @JeromeMartinez that this is based on the gui using the 20221116 cli.

**Comment by ElderOrb** [comment]
@dericed still an issue?

**Comment by ElderOrb** [comment]
@dericed ^ ??
