### ISSUE TITLE
enable drawtext filter in bundled ffmpeg

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#646]
The gui uses the drawtext filter, but the bundled ffmpeg is not built with it:

```
$ ffmpeg -v 0 -filters | grep -c drawtext
1


$ /Applications/dvrescue.app/Contents/Helpers/ffmpeg -v 0 -filters | grep -c drawtext
0
```

Can we add --enable-libfreetype and --enable-libfontconfig to this configuration?

**Comment by retokromer** [comment]
+1

**Comment by g-maxime** [comment]
Is fontconfig really needed?

Current only use of drawtext in the gui don't use 'font=' parameter and fontconfig leack an official way to make an msvc build.
