### ISSUE TITLE
dvpackager queue?

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#648]
I have been trying to figure out how to queue up multiple files to package in the dvpackager GUI. Is this not an option currently, or am I just missing something? To clarify, I mean open a file, add it to the file output list and then move onto another file, add it to the file output list, etc. through multiple files so that you can queue up a few to run at a time (with differing segmentation rules if needed).

**Comment by dericed** [comment]
Hi @libbyhopfauf, please test https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20230322/

**Comment by libbyhopfauf** [comment]
@dericed see https://github.com/mipops/dvrescue/issues/617#issuecomment-1482230698 #617 
sort of replied to all the queue convos there :)

**Comment by dericed** [comment]
Will close this as #617 supersedes it
