### ISSUE TITLE
dvpackager GUI: design layout adjustments

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#661]
Based on feedback from multiple users, as well as my own experience, I think it would be more intuitive for the dvpackager window layout to be adjusted to have the "package" and file location moved below the input list and to include titles for each table:

<img width="1599" alt="dvpackager_layout-design-adjust" src="https://user-images.githubusercontent.com/13877631/205409171-db567fae-1e3b-4423-9512-4f4aa8bbed43.png">

**Comment by dericed** [comment]
@libbyhopfauf oooo i like these headers, though i think the segmenting rules should visually be within the "SEGMENTS" section as they look now like a footer to the INPUT section. I also suggest we change the OUTPUT to an OUTPUT QUEUE, but if we do that do you think we should have the PACKAGE button say "ADD TO QUEUE" and give a separate "START PACKAGING" button in the OUTPUT QUEUE section?

**Comment by dericed** [comment]
to update the above comment, i suggest "INPUT FILES", "SEGMENTATION RULES" and "OUTPUT QUEUE" as labels. The "PACKAGE" button should be called "ADD TO QUEUE".

**Comment by ElderOrb** [comment]
![image](https://user-images.githubusercontent.com/23638/221670749-11fe8578-ec7f-4ba2-9316-c0ba59a9202c.png)

**Comment by ElderOrb** [comment]
![image](https://user-images.githubusercontent.com/23638/221670974-b6ce7c37-7c28-4acb-9b79-d73036717843.png)

**Comment by dericed** [comment]
Looks good. @libbyhopfauf?
Also, can you change the "PACKAGE" button to "ADD TO QUEUE" and then once added to queue, it says until app is closed or user removes item from queue.

**Comment by dericed** [comment]
Hi @libbyhopfauf, please test https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20230322/

**Comment by libbyhopfauf** [comment]
@dericed see https://github.com/mipops/dvrescue/issues/617#issuecomment-1482230698 #617 
:)

**Comment by libbyhopfauf** [comment]
@dericed I think we can close this since the layout is adjusted and now we're just tweaking specific things that can be their own issue :) reopen if you disagree!
