### ISSUE TITLE
#No xmlstarlet error

### ISSUE THREAD

**Issue by timlake23** [mipops/dvrescue#665]
I've been running into an error with dvpackager (using the newest instance of the Mac dmg). I upgraded ffmpeg and still receiving the error message below. Thoughts?

![dvrescue error](https://user-images.githubusercontent.com/56738171/207735921-b99ebeae-4643-41c3-b651-ecc5621f6806.png)

**Comment by g-maxime** [comment]
ffmpegdecklink seems not working on your system, you can pass an working ffmpeg binary to dvrescue with the -F <path> option

**Comment by timlake23** [comment]
Thanks. That has resulted in the below error. Any other workarounds for ffmpegdecklink?

![ffmpeg error](https://user-images.githubusercontent.com/56738171/207940488-7b185b7d-b76b-456e-a406-9060dc94e40a.png)

**Comment by timlake23** [comment]
Brilliant, thank you, that did the trick.

**Comment by timlake23** [comment]
Quick follow up here: when merging two .dv files, I'm receiving an error that the resulting .dv file isn't compatible with QuickTime Player. Merge function doesn't seem to be wrapping the file properly.

![merge error](https://user-images.githubusercontent.com/56738171/207962367-7a9be5c2-0eea-479f-ad97-f44237970d1d.png)

**Comment by JeromeMartinez** [comment]
> Merge function doesn't seem to be wrapping the file properly.

Please open a separate ticket, as the title of this ticket does not match.
With link to input files (or provide the links by email if files can not be public) so we can reproduce the issue.

**Comment by dericed** [comment]
Will close (and nudge for a new issue). Noting that while dvpackager, dvplay, and few other scripts require a reference to a working ffmpeg that the dvrescue cli itself doesn't.
