### ISSUE TITLE
packaging/rewrapping DV file increases volume of audio error only

### ISSUE THREAD

**Issue by arn-mipops** [mipops/dvrescue#670]
For some DV files that have audio errors baked into the recording, we’ve been finding at MIPoPS that once they are packaged in DVRescue that the errors are more noticeable. The overall volume of the audio does not increase, but the errors are louder/more noticeable. As an experiment, we used ffmpeg to rewrap the file to see if it was an issue with DVRescue or with rewrapping. The results were the same. [Here is a set of example files](https://drive.google.com/drive/folders/1mrKJoHSycg7Nhe6VX6_wJuN5v1O8HujH?usp=share_link):

- Original captured DV file
- File packaged as MKV in DVRescue GUI
- Rewrapped file using ffmpeg
- Logs are also included here

For reference, here’s the command line we used for a straight rewrap of DV to MKV:
`ffmpeg -i SAM_2804.dv -c copy -map 0 SAM_2804.mkv`

This was on a Mac Mini (M1, 2020) running macOS Monterey 12.4.
DVrescue version is from 2022-12-12.
ffmpeg version is 5.1.2_3.

We don't think this is related to #447. 

Has anyone else experienced this? @dericed any idea what could cause this?

**Comment by privatezero** [comment]
Hi @arn-mipops - I just tested out your sample files and didn't hear any difference on my end - what software are you using to play them back? (I used mpv).

I did a quick check with FFmpeg's MD5 format too, and the audio streams for both files came out bit exact. I'm not on a mac, however, so I wonder if something in your software is treating the files differently?

**Comment by arn-mipops** [comment]
Hi @privatezero thank you for looking into it! Yes, it looks like this was an issue with playback software after all.

The dv files were playing in Quicktime and the mkvs were using VLC. For some reason in VLC the audio errors are much louder and more noticeable. When playing some of the dv files in VLC, I couldn't get any audio at all, so it was hard to compare. But I managed to test a few and they did sound the same as long as I was using the same player.

Thanks again for the quick reply! It's good to have the confirmation that nothing is being changed in the packaging.
