### ISSUE TITLE
dvpackager GUI - MOV seems to be default output even when it's not selected

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#684]
In the dvpackager GUI, if I have two or more files (file-1, file-2, file-3, etc.) loaded into packager and I have already added files to the queue for file-1, once I select file-2 and my segmenting rules and click add to queue, the wrapper applied is .mov even though .mkv was still selected. This happens every time, even if I don't make any changes to any of the segmenting rules, file location or wrapper. I noticed that if I change the selection to .mov, then back to .mkv and then click "add to queue" that the files added will add as .mkv files. But I have to do this every time for every files I have before adding each set of segments to the queue. See video example below:

https://user-images.githubusercontent.com/13877631/227683203-4a14c70c-55d4-4074-80dc-139944168ef0.mov

**Comment by ElderOrb** [comment]
@libbyhopfauf is it still an issue ?

**Comment by ElderOrb** [comment]
@libbyhopfauf ^^

**Comment by libbyhopfauf** [comment]
@ElderOrb sorry, I just saw this! Yes, so far, I have to toggle back to .mov and then back to .mkv before clicking "add to queue" otherwise dvpackager packages the file as a .mov. Here is a screen recording I took today using the latest release:


https://github.com/mipops/dvrescue/assets/13877631/4c9c2cda-c428-4485-9a61-a53ac3bc8724

**Comment by ElderOrb** [comment]
@libbyhopfauf hmmm, for some reasons video doesn't play correctly - can only see a few first frames. But based on 'toggle back to .mov and then back to .mkv' looks like you are not on the latest version - cause in a latest version 'mov' is a default selection in UI

**Comment by ElderOrb** [comment]
@dericed is it reproducible for you too?

**Comment by libbyhopfauf** [comment]
> @libbyhopfauf hmmm, for some reasons video doesn't play correctly - can only see a few first frames. But based on 'toggle back to .mov and then back to .mkv' looks like you are not on the latest version - cause in the latest version 'mov' is a default selection in UI

@ElderOrb I'm sorry that was confusing. Below is a video I took today using version 2024-02-10. But in case that one doesn't work on your end either, here are the steps I took:
- imported file
- selected segmentation rules
- clicked apply
- selected MKV
- clicked "add to queue"
- video exports as MKV
- imported a second file
- selected segmentation rules
- clicked "apply"
- since MKV was already selected, I clicked "add to queue"
- file shows up in queue and exports as MOV
- if I make no changes, but select MOV and then reselect MKV and add the file to the queue it exports as MKV.


https://github.com/mipops/dvrescue/assets/13877631/42ccf316-31e3-47ee-9e0f-969a8679c011

**Comment by dericed** [comment]
@libbyhopfauf I can't reproduce this with the latest daily build. Can you confirm?

**Comment by dericed** [comment]
ping to @libbyhopfauf

**Comment by arnicholson** [comment]
This is resolved for me. Cannot reproduce anymore.
