### ISSUE TITLE
switching tabs should stop playback

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#689]
If I play a video in the analysis tab and then switch to another tab, wait a minute, and then switch back to the analysis tab, then the video is now one minute ahead and still playing. If switching tabs can we always stop the playback.

**Comment by libbyhopfauf** [comment]
@dericed but this wouldn't apply to the capture tab, yeah? Just analysis and packager?

**Comment by ElderOrb** [comment]
https://github.com/mipops/dvrescue/pull/798
