### ISSUE TITLE
add more filter buttons

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#690]
With https://github.com/mipops/dvrescue/blob/main/Source/GUI/dvrescue/dvrescue/PlayerView.qml#L45 we support one player filter but I'd like to add more options. If more than one option is selected, then they should be semicolon delimited.

Whereas there's currently a button called `TC`, let's add `F#` and `CC` as well.

If `F#` is selected then the filter should be: `format=rgb24,drawtext=text='frame# %{frame_num}':x=0:y=0:box=1:boxcolor=gray@0.5:fontsize=36:fontcolor=white`

The `CC` button should only be clickable if the `scc` file exists (otherwise gray it out as not-applicable). Here is a sample where an scc file will be made when it's analyzed in the GUI: `https://makeinstallnotwar.org/video/Demo_DV_720x480_CC.mov`.

If `CC` button is enabled then the filter is: `subtitles=${PATH_TO_SCC}`.

So for example if someone enables both `F#` and `CC` then it's `filter1;filter2` or in this case `format=rgb24,drawtext=text='frame# %{frame_num}':x=0:y=0:box=1:boxcolor=gray@0.5:fontsize=36:fontcolor=white;subtitles=${PATH_TO_SCC}`.

**Comment by ElderOrb** [comment]
@dericed done?
