### ISSUE TITLE
dvrescue doesn't output files larger than 2 GiB, instead fills memory until crashing with "Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by erikryb** [mipops/dvrescue#696]
When I run dvrescue with the following command:

`dvrescue device://0 -m video.dv`

it writes to the output file `video.dv` until this file is almost exactly 2 GiB (2147483647 bytes = 2 GiB - 1 byte). When the output file reaches 2 GiB, it stops growing, but dvrescue continues and starts using more and more memory until the memory is full and it crashes with the following message:

`Segmentation fault (core dumped):19:22`

The same behavior happens if I use a local file as input which is larger than 2 GiB:

`dvrescue large_video.dv -m video.dv`

System info:

```
lubuntu@lubuntu:~$ uname -a
Linux lubuntu 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:09:27 UTC 2020 i686 i686 i686 GNU/Linux
```

Software version:
```
lubuntu@lubuntu:~$ dvrescue --version
DVRescue v.22.12 (MediaInfoLib v.22.09) by MIPoPS.
```

**Comment by JeromeMartinez** [comment]
32-bit architecture is not much tested but not a reason, a 32-bit integer issue somewhere.

**Comment by erikryb** [comment]
Thanks for the quick response! I wish I could use a 64-bit machine but this machine is the only one I have that is old enough to have a firewire port.

**Comment by adompeldorius** [comment]
I think I managed to avoid this issue by compiling dvrescue with `-O0` as well as `-D_FILE_OFFSET_BITS=64` as recommended [here](https://digital-domain.net/largefiles.html). The command `dvrescue device://0 -m video.dv` now manages to output files larger than 2GB, but there seems to be (at least) another issue where it crashes with `Segmentation fault (core dumped)` after capturing for some time (different time each time, one time after outputting 7.7 GB, another time after outputting 831 MB).

**Comment by erikryb** [comment]
I think I managed to avoid this bug by compiling with `-D_FILE_OFFSET_BITS=64` as recommended [here](https://digital-domain.net/largefiles.html), as well as `-O0` (which is a bit weird, as I don't think it should make a difference). Now the command `dvrescue device://0 -m video.dv` manages to output files beyond 2 GiB. However, there seems to be (at least) one other bug, where the command crashes with `Segmentation fault (core dumped)` after some random time. In one attempt this happened after outputting 7.7GB, another time after outputting 831MB. This may not be related to this issue, so I can make another issue.

**Comment by asdf618** [comment]
I can confirm that the dvrescue -m operation fills up memory then grinds to a halt. This happens for simple capture, as well as merging multiple files. This behavior is consistent across linux 64, mac and windows x64 platforms. I also tried the nightly CLI as well as the stable releases.

**Comment by JeromeMartinez** [comment]
@erikryb @asdf618  apologizes for the late answer, I'll fix that in the next days.
