### ISSUE TITLE
issue with overwriting of dvpackager temp files

### ISSUE THREAD

**Issue by bturkus** [mipops/dvrescue#706]
Hi,

I'm not sure if this issue has been resolved—I'm encountering the problem on some computers but not others, though I swear I'm installing the same version of dvrescue (the latest from Homebrew + also trying the latest daily build I can find from macOS, sometime in March)—but when using dvpackager CLI, and processing the same DV files for a second time, I'm getting this kind of error:

```
File '/var/folders/xc/ht_wgcbj4417577f0wy928wc0000gp/T/dvpackager.XXXXXX.MG0rdtOf' already exists. Overwrite? [y/N] 
```
It seems like even if I go into the temp directory and delete anything at all related to dvrescue, I'm still having the same issue. And this has been a challenge bc we've been playing around with different dvpackager settings, etc.

Any advice or thoughts would be appreciated!

Thanks,

Ben

**Comment by dericed** [comment]
Hey @bturkus can you recheck. I think this was closed a while back.
