### ISSUE TITLE
ERROR: 0 frames packaged from dvpackager

### ISSUE THREAD

**Issue by Achearoo** [mipops/dvrescue#720]
I ran the command:

> dvpackager -e mov -o /Volumes/home/Harry\'sTwentyTwentyThree/CULTURE\ VULTURE/MINIDV /Volumes/home/Harry\'sTwentyTwentyThree/CULTURE\ VULTURE/MINIDV/20230725CVSCRIPT.dv

I received this error, after it went through it's usual packaging motions:

> ERROR: 20230725CVSCRIPT_part1.mov is expected but missing. Please retry with the -v option and report to https://github.com/mipops/dvrescue/issues.
ERROR: 20230725CVSCRIPT.dv contained  DV frames, but the outputs contain 0 frames of DV and 0 were skipped

I did retry with the -v command, and it gave me a bunch of purple text:

> #CONDENSE_OPTS is set to -s
#Using /usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl for ffmpeg operations.

> #No xmlstarlet error
#DV_FRAME_COUNT=()
#SOURCE_FORMAT=()
#Trying to present a table of ranges

> #The audio range sublist (from frame  to ) is
#
>#Writing a chapter track at /var/folders/lf/hjwdck596r9_k5n5z33628dr0000gn/T/dvpackager.XXXXXX.jkMQtcB7.ffmetadata.

> #Found 1 point(s) for chapter marks.
#Skipping the process to embed chapters since there would only be one.
#Trying to run: /usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl  -y -nostdin -hide_banner -ss  -i /Volumes/home/Harry'sTwentyTwentyThree/CULTURE VULTURE/MINIDV/20230725CVSCRIPT.dv -map 0:v:0 -c:v:0 copy -f rawvideo - | ffmpeg  -y -nostdin -hide_banner -i -   -filter_complex concat=n=0:v=0:a=1[aud] -t  -c:a pcm_s16le -c:v:0 copy -f mov -map 0:v:0 -map [aud]  /Volumes/home/Harry'sTwentyTwentyThree/CULTURE VULTURE/MINIDV/20230725CVSCRIPT_part1.mov

My intended output was to receive a single .mov file from the dv stream. Neither my GUI nor CLI can package now, but my CLI can still capture. Attempted on multiple computers, both CLI and GUI. One is a Macbook 2013 on macOS Monterey and the other is a Mac Studio 2022 on macOS Ventura.

**Comment by Achearoo** [comment]
Update: Since my intention is merely to maintain the original interlacing and edit with the jagged-looking interlaced ghosting, the "Save..." button on Mac, when opening the .dv file I believe does extract the raw dv stream and combine it into a .mov with the audio. Can't be too sure, but examining the interlacing in VLC and on a Premiere Pro export, it looks quite similar.

dvpackager is still not working, but this will be a fine work around in the meantime.

**Comment by libbyhopfauf** [comment]
@Achearoo this appears to be a similar issue as #950. Please see the comments in there regarding work in progress to resolve issues stemming from ffmpeg.
