### ISSUE TITLE
Unable to install versions through 23-09-2023 to 06-09-2023 (DVRescue GUI)

### ISSUE THREAD

**Issue by Rysiek18** [mipops/dvrescue#728]
Hi,

I was trying to install daily patches of DVRescue GUI, and I'm unable to install the newest ones (23-09-2023 to 06-09-2023). They are significantly smaller in size than the older ones, and when I try to install them there is a pop-up that says: Cannot open DvRescue app - it can be broken or incomplete. (Translated text)

Best Regards,
Krzysiek

Specs:
Hardware - Macbook Pro 5.5
CPU - Intel Core 2 Duo 2.26Ghz
GPU - NVIDIA GeForce 9400M 256MB
RAM - 4GB 1067MHz DDR3
Memory - 128GB SATA SSD
OS - 12.7 Monterey

Firewire Port - 800Mbps
DV Deck - Canon MV590 (Shows up as MV600)

**Comment by JeromeMartinez** [comment]
> the newest ones (23-09-2023 to 06-09-2023).

The ones before 2023-09-06 are fine and see your deck, right?

**Comment by Rysiek18** [comment]
The latest installable version for me is 2023-08-13 (Between 2023-08-13 and 2023-09-06 the are no versions for mac)

**Comment by Rysiek18** [comment]
Hi @JeromeMartinez,

In the newest snapshot from 2023-09-30 nothing changes and the outcome is the same as earlier (see photos below).

![Zrzut ekranu 2023-10-2 o 15 04 54](https://github.com/mipops/dvrescue/assets/59761804/8936c737-ee2c-4fc4-a1d5-13008671017e)
![Zrzut ekranu 2023-10-2 o 15 06 04](https://github.com/mipops/dvrescue/assets/59761804/cd7f250d-183b-4804-8708-697c9f3f9dcb)

> The ones before 2023-09-06 are fine and see your deck, right?

I can install them, but none of them (in gui versions) seem to see my DV deck at all

Thanks,
Rysiek18

**Comment by JeromeMartinez** [comment]
Still work in progress (at https://github.com/mipops/dvrescue/pull/730).

**Comment by Rysiek18** [comment]
Oh, ok. I didn't notice.

Thanks,
Rysiek18

**Comment by JeromeMartinez** [comment]
@Rysiek18 [this dev snapshot](https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20231003-3/dvrescue_GUI_0.21.11.20231003_Mac.dmg) should be OK (for the program launch part; maybe not yet for the deck detection part, to be confirmed)
