### ISSUE TITLE
dvpackager (version 2023-11-27-1) GUI bugs

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#758]
While testing the last few versions of dvpackager the GUI aseems to have some bugs:

1. For the GUI, the icons for the progress of files sent to the package queue are inconsistent. Sometime they display accurately what they are doing/have done (in queue, successfully packaged, failed to package, etc.), but sometimes they will remain gray or blue, but will have actually packaged a file or failed to package. Sometimes when the icon remains gray, the file has successfully packaged, other times, it has failed.

https://github.com/mipops/dvrescue/assets/13877631/8b132a58-f9be-40f8-ab4f-06418ef67292

2. It seems like I can only package 1-2 files at a time before having to exit out and restart. If I don't and add more files to work on, the queue will either fail for all remaining to be processed or new additions from a new file will overwrite queue packaged files from a different file. 

3. If I have packaged a few files and specified that the extension should be mkv, sometimes the GUI will revert back to mov for the wrapper even though mkv is still selected. Seems to happen fairly inconsistently, but frequently. Closing out of the GUI and reopening resolves the problem, but similar as the bug listed above, it gets to the point where the only way to be sure that packager will function as intended is to only load in 1-2 files at a time and then quit/reopen the GUI after those 1-2 files package successfully. Another way to fix it is to select mov and then reselect mkv. Sometimes, even if mov is listed as the extension in the queue, the GUI actually outputs a mkv, but sometimes it outputs a mov (as listed, but not selected).

**Comment by dericed** [comment]
@ElderOrb any clues here?

**Comment by libbyhopfauf** [comment]
UPDATE: for version 2023-11-30, now files don't seem to want to load into the segment table or the queue:

**Comment by libbyhopfauf** [comment]
Didn't mean to close!

**Comment by libbyhopfauf** [comment]
It does seem like these errors have improved (less frequent), but I am still experiencing regular inconsistencies with processing. While testing the latest version (2023-12-08), I was still having issues with the icons being accurate (for a file that was fine and encoded successfully, the GUI just displayed the gray "waiting symbol" the whole time. It also keeps reverting back to MOV as the wrapper even though I have MKV selected.

<img width="1591" alt="Screenshot 2023-12-08 at 3 12 29 PM" src="https://github.com/mipops/dvrescue/assets/13877631/d8cba7d2-4ee8-4e87-bead-373edc8dcf43">



But if I click over to MOV and then back, it starts processing a MKV normally:
<img width="1792" alt="Screenshot 2023-12-08 at 2 19 23 PM" src="https://github.com/mipops/dvrescue/assets/13877631/c5e7c784-e0ae-400d-ad64-5990464384cc">



I also got all sorts of weird information in the segmenting table for this one file. 
<img width="1585" alt="Screenshot 2023-12-08 at 3 14 55 PM" src="https://github.com/mipops/dvrescue/assets/13877631/b8bbe0c4-6566-4cee-8953-66047f3c1ce2">

But when closed out and reloaded the same file it processed like it is supposed to:


<img width="1587" alt="Screenshot 2023-12-08 at 3 23 59 PM" src="https://github.com/mipops/dvrescue/assets/13877631/21deb85a-736d-428d-bc99-0f4b1f20fa41">

**Comment by arnicholson** [comment]
I'm still seeing some inconsistencies between what is reported in the output queue vs what is actually happening.

As an example, I queued up three files. It showed it was working through the first one...
![1_working](https://github.com/mipops/dvrescue/assets/123590485/6844a5a3-8ba2-45a2-a029-7412c8ff9ba0)

And then reported a failure. It did not seem to have moved onto the next item in the queue.
![2_failure-reported](https://github.com/mipops/dvrescue/assets/123590485/5e1c192d-717d-4dbd-b6f5-1fadb1e55cfd)

However, an .mkv WAS actually created. I can see no problems with it, either. It is the same length as the .dv file and plays just fine.
![3_mkv-created](https://github.com/mipops/dvrescue/assets/123590485/fa902616-73cd-40d1-b92e-98df2e527851)

And in fact, packager did move on and package the second file in the queue as well, as I have a perfectly good .mkv for that one, too.
![4_second-mkv-created](https://github.com/mipops/dvrescue/assets/123590485/242dbd02-d9b8-4f01-9769-3c0bd754b9bb)

Here's a log created while I did this test:
[package_log.txt](https://github.com/user-attachments/files/15796303/package_log.txt)

And here are all the relevant files, in case that's helpful:
https://drive.google.com/drive/folders/1dZJ9vE-vIUuXnvT2wfvANRnoHrdaAYt4?usp=sharing

dvrescue --version
DVRescue v.22.12.20240611 (MediaInfoLib v.24.05) by MIPoPS.
dvrescue --list_devices
0x80458280022265: Panasonic DV [DV]

Panasonic AG-DV2500
System: Mac mini (late 2014) running Monterey 12.7.3

**Comment by arnicholson** [comment]
This issue seems resolved now. I've had no problems with the output queue in multiple tests on the most recent GUI.
