### ISSUE TITLE
dvcapture GUI (2023-11-27-1) won't capture DVCPRO

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#760]
While testing out dvcapture (using the GUI dvrescue version 2023-11-27-1), I am not able to capture DVCPRO. vrecord will capture the same tape using the same device (Sony DSR-1500A). I thought this might have to do with the new "keep" vs. "ignore" capture settings, but I tested it both ways multiple times and the GUI will not capture DVCPRO. It seems to be working fine with DVCAM and MiniDV across a variety of devices.

Test files are located [here](https://drive.google.com/drive/folders/1wE4qyIl3BkWah0rUXBAYmp5rZZvtONhm?usp=sharing).

**Comment by dericed** [comment]
With a deck attached, can you try:
`dvrescue --list_devices`
`dvrescue -m trythis.dv` 

Just curious if the CLI can capture it

**Comment by libbyhopfauf** [comment]
I tried a couple times with the deck playing. Still no capture for DVCPRO. 

Here's the terminal output for those commands (it seemed like I needed to tell it to capture :):
```

Last login: Fri Dec  1 13:20:51 on ttys000
mipops-macbook@mipops-macbooks-MacBook-Pro ~ % dvrescue --list_devices
DSR-1500A (Sony DSR-1500A)
mipops-macbook@mipops-macbooks-MacBook-Pro ~ % dvrescue -m trythis.dv 
Usage: "dvrescue FileName1 [Filename2...] [Options...]"
"dvrescue --help" for displaying more information.

mipops-macbook@mipops-macbooks-MacBook-Pro ~ % dvrescue --capture /Users/mipops-macbook/Desktop/test.dv
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.2.1">
	<creator>
		<program>dvrescue</program>
		<version>0.22.10</version>
		<library version="22.09">MediaInfoLib</library>
	</creator>
</dvrescue>
```

**Comment by dericed** [comment]
`dvrescue --capture /Users/mipops-macbook/Desktop/test.dv` isnt' valid syntax
`--capture` is default is `--cmd` isn't used. In this example the filepath is uncontextualized.
`dvrescue --capture -m /Users/mipops-macbook/Desktop/test.dv` should work.

hmm
what does `avfctl -cmd capture test.dv` do?
Can you see the dvcpro input if you try in quicktime?

**Comment by libbyhopfauf** [comment]
> `dvrescue --capture /Users/mipops-macbook/Desktop/test.dv` isnt' valid syntax `--capture` is default is `--cmd` isn't used. In this example the filepath is uncontextualized. `dvrescue --capture -m /Users/mipops-macbook/Desktop/test.dv` should work.

My bad! When I run the suggested command, this is what I get (I had to use the mipops-mac as my loaner computer so I had to change the user name). But it looks like the same thing:
```
Last login: Thu Jan 11 17:49:26 on ttys000
libbyshopfauf@MacBook-Pro-55 ~ % dvrescue --list_devices
0x8004602010e007c: DSR-1500A (Sony DSR-1500A) [DV]
libbyshopfauf@MacBook-Pro-55 ~ % dvrescue --capture -m /Users/libbyshopfauf/Desktop/2024-01-11/DVCPRO-test-01.dv
Usage: "dvrescue FileName1 [Filename2...] [Options...]"
"dvrescue --help" for displaying more information.
```

Just FYI, I tried using the latest build and still cannot capture DVCPRO from the dvrescue GUI. The tape plays (and deck control works), but the file is empty. Similar to what people are describing in [this vrecord issue](https://github.com/amiaopensource/vrecord/issues/766).

> hmm what does `avfctl -cmd capture test.dv` do? 

With this command, I can capture DVCPRO from my DSR-1500A (no playback, but deck control works and I can . I get the following output and the file plays great: 
```
libbyshopfauf@MacBook-Pro-55 ~ % avfctl -cmd capture /Users/libbyshopfauf/Desktop/2024-01-11/test.dv
2024-01-11 17:53:43.469 avfctl[9149:76325] Mode changed: 0 -> 1
2024-01-11 17:53:43.469 avfctl[9149:76325] Speed changed: 0.000000 -> 1.000000
2024-01-11 17:56:19.837 avfctl[9149:76342] Speed changed: 1.000000 -> 0.000000
2024-01-11 17:56:19.837 avfctl[9149:76342] Mode changed: 1 -> 0
2024-01-11 17:56:19.837 avfctl[9149:76342] Stopping capturing.
libbyshopfauf@MacBook-Pro-55 ~ % 
```


> Can you see the dvcpro input if you try in quicktime?

Yep! Plays great and captures (as mov). 
<img width="1512" alt="Screenshot 2024-01-11 at 5 58 26 PM" src="https://github.com/mipops/dvrescue/assets/13877631/afde7179-d499-4f77-88d1-8b0010e95de6">

**Comment by libbyhopfauf** [comment]
> While testing out dvcapture (using the GUI dvrescue version 2023-11-27-1), I am not able to capture DVCPRO. vrecord will capture the same tape using the same device (Song DSR-1500A). 

@dericed As a follow up to my original comment when I opened this issue regarding using vrecord to capture DVCPRO (which was working for me when I originally posted this), but now vrecord won't capture DVCPRO. I'm using a fork from [this branch ](https://github.com/amiaopensource/vrecord/tree/updates-on-handling-recorders)(the same one that had worked previously for me). I've tried the following troubleshooting steps to resolve this (test files for vrecord capture from today are here):

- vrecord wasn't recognizing my device.
- reset my security policy in recovery mode AGAIN (the settings might have gotten reset to "full" somehow when I restored my time machine backup to this computer). 
- restarted by computer
- fresh fork of vrecord to my GitHub desktop
- opened vrecord using the command in the repository folder
- my device showed up!! love the device code btw
<img width="1086" alt="Screenshot 2024-01-11 at 6 50 29 PM" src="https://github.com/mipops/dvrescue/assets/13877631/fb1dbe40-92ec-433c-b5a2-6576d2f5fd97">
- but there is no playback window to view the recording or to close to end the recording, so I had to press stop on the deck to end the recording. 

https://github.com/mipops/dvrescue/assets/13877631/d3ef9a93-eac7-41bf-8501-615949533846


- This is the terminal output after I ended the recording:
<img width="1512" alt="Screenshot 2024-01-11 at 6 53 41 PM" src="https://github.com/mipops/dvrescue/assets/13877631/34dbf633-e92b-4d85-8be9-7425b3971b9d">
- no video was captured, just a capture log with the following information:

```
computer_name: MacBook-Pro-55.local
computer_model_name: MacBook Pro
computer_model_id: MacBookPro18,3
computer_processor_name: 
computer_processor_speed: 
computer_processor_count: 
computer_memory: 16 GB
computer_serial: LQYGH19CF6
computer_cores: 8
user_name: libbyshopfauf
operating_system_VERSION: Darwin Kernel Version 22.6.0: Wed Oct  4 21:26:23 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_ARM64_T6000
vrecord version: 2023-08-07
datetime_start: 2024-01-11T18:51:08
capture_device_node: /dev/disk3
capture_device_protocol: Apple Fabric
capture_device_name: APPLE SSD AP1024R
capture_device_block_size: 4096 Bytes
capture_device_location: Internal
capture_device_partition_type: 41504653-0000-11AA-AA11-00306543ECAC
capture_device_partition_name: APFS
capture_device_volume_uuid: 66A92C2E-EE14-4500-829F-EC49B51B21B9
capture_device_volume_available: 
capture_device_volume_total: 
FILE_PATH: /Users/libbyshopfauf/Desktop/2024-01-11/2024-01-11_DVCPRO-vrecord-test_01.dv
DVRESCUE_INPUT_CHOICE: 0x8004602010e007c: DSR-1500A (Sony DSR-1500A) [DV]
WAVEFORM_SCALE_CHOICE: digital
SIGNAL_VIEW_CHOICE: Broadcast Range
SIGNAL_INT_CHOICE: auto
MONITOR_AUDIO_CHOICE: Yes
PLAYBACKVIEW_CHOICE: Unfiltered
DV_CONTAINER_CHOICE: DV

TECHNICIAN: lsh
Capture command: dvrescue device://0x8004602010e007c --capture -m -
Record command: /usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl -nostdin -nostats -i - -map 0:v -c copy -f rawvideo /Users/libbyshopfauf/Desktop/2024-01-11/2024-01-11_DVCPRO-vrecord-test_01.dv -map 0:v -f rawvideo -c copy -
Playback command: /usr/local/opt/ffmpegdecklink/bin/ffplay-dl -v info -hide_banner -stats -autoexit -window_title mode:record - input:'0x8004602010e007c: DSR-1500A (Sony DSR-1500A) [DV]' - to end recording press q, esc, or close video window -i - -af channelmap=0|1:stereo
Capture exit code: 0
Record exit code: 1
Playback exit code: 0
vrecord command Error: invalid P2_ERR value of 1
```

**Comment by libbyhopfauf** [comment]
@bravoalphatango did some AWESOME testing on this same issue today! See the results + linked (very well documented) troubleshooting document. It looks like she's getting the same results that I am for DVCPRO. Please note that the results are almost identical and that she's using an Intel Mac while I was using a M1 chip (so the problem isn't isolated to that).

FROM BRIANNA:
Ok so I went through the tests outlined with (4) different decks that include (3) different models and had some luck! These decks included:

* (1) Sony DSR-1500A
* (1)Panasonic AJ-HD1400P
* (2)Panasonic AJ-D250P

QuickTime, vrecord and DVRescue recognize all the decks, but avfctl would give the following error message even though it was able to capture the tape on all 4 decks:

tothba@SIA-3118AV-1 ~ % avfctl --list_devices
avfctl - control and capture from DV tape players via AVFoundation
version 0.21.11
Usage: avfctl [Options...] [OutputFile]
"avfctl -h" for displaying more information.

I was able to capture using vrecord on the Panasonic AJ-HD1400 deck and Sony DSR-1500A, but neither of the Panasonic AJ-D250P decks. We also have a Panasonic AJ-D230P deck, but I did not test it since the similar models weren't playing very nice.

I was unable to capture on any of the decks using DVRescue. 

I was able to capture on all the decks using the avfctl command Dave provided, but a capture preview window does not appear like it goes with vrecord. It also doesn't provide any information in the Terminal to suggest it is doing anything. It just starts creating the file wherever you tell it to and then you play it afterward to see what was captured.

Here is my troubleshooting doc that breaks down the results of each test with each deck. Skip to page #2:
https://docs.google.com/document/d/1by5TLi7utY4Psdfo14rhiDpI7_ylFRMY1iIbxjxU7uI/edit?usp=sharing

This folder has all the logs that were generated. I got some of the same results you did.
https://drive.google.com/drive/folders/1OA_xlhPo-r2umCdJrc7SYok8a-DvNvCT

If you have insights into why some of these decks are working and not others it'd be great! I also don't understand the error message I'm getting when I try to capture with DVRescue. I believe it's the same one you got?

**Comment by libbyhopfauf** [comment]
@bravoalphatango regarding the inconsistencies with the decks:  I'm not sure why it's not working with all of the decks. I think maybe it has to do with the menu settings? I know that with the DSR-1500A, it has to have very specific output settings to connect to a computer for capture, but it's like across the board, so if the settings are off it wouldn't work with Quicktime either. Panasonics tend to do weird things, but it's interesting that they are working with some of the tools, but not others. @dericed any ideas?

HMMMM I'll do some more testing tomorrow and follow up!

**Comment by libbyhopfauf** [comment]
@bravoalphatango I'm still having the same issues as well. I've only had success capturing DVCPRO using the avfctl command, but I agree, it's hard to know what's going on without being able to monitor the capture via a playback window. 

@dericed any ideas why dvcapture for vrecord and dvrescue used to support DVCPRO, but now it doesn't?

**Comment by libbyhopfauf** [comment]
I just tested recording DVCPRO with the new release and I wasn't able to successfully capture using DVRescue. All test files are located [here](https://drive.google.com/drive/folders/1Y0Y8F6L27OB0FicttQu4zAwSbzpbXYsS?usp=sharing) (including a capture of a MiniDV from the same deck using the dvrescue GUI). Here are the tests I ran using the same DVCPRO tape and a Sony DSR-1500A:

- **dvrescue GUI** - The video will play back in the DVRescue GUI and create three files (DV, XML and log), but the DV files only seem to be capturing a single frame or nothing at all. There are two sets of files for the corresponding tests (test-1 and test-2). Tests also include log files created from Terminal read out. 

https://github.com/mipops/dvrescue/assets/13877631/5e4524c0-af44-4d82-b606-de4ba3792d10



- **dvrescue CLI** - seemed to be doing something, but only a single frame was captured. The resulting DV file and an export of the Terminal are included with the test files. 
- **vrecord** - using this version of vrecord, I cannot get a DVCPRO compatible device to show up.
- **Quicktime** - was able to capture the file

**Comment by dericed** [comment]
@JeromeMartinez any reason that dvrescue stops after a single frame with these dvcpro captures. 
[8643_test-1.dv.zip](https://github.com/mipops/dvrescue/files/14454064/8643_test-1.dv.zip)

**Comment by libbyhopfauf** [comment]
@dericed @JeromeMartinez I can confirm that this is still an issue with version 2024-03-26. Here are my [test files](https://drive.google.com/drive/folders/11w0pYGdKzIyVarJrLOuk0fa-vaU2O_p_?usp=sharing) from today.

**Comment by libbyhopfauf** [comment]
recent versions of dvrescue have worked to capture DVCPRO on my end!
