### ISSUE TITLE
dvcapture - indicator lamps for HDV and LP

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#779]
Based on feedback from the group today, here is a mock-up for adding little "lamps" to the side of the player that were grayed out (or not there) if a tape is not HDV or LP. When the deck detects a LP or HDV tape, the corresponding "lamp" would be pink (like the pink line below the player buttons highlighting which mode the deck is in). Thoughts? 

LP = off | HDV = on
<img width="765" alt="HDV-LP_lamp-design-HDV" src="https://github.com/mipops/dvrescue/assets/13877631/3449391e-70ba-478c-84d4-d060ce08facd">

LP = off | HDV = off
<img width="765" alt="HDV-LP_lamp-design-off" src="https://github.com/mipops/dvrescue/assets/13877631/8334950a-4114-405b-b27a-5c2217cda39e">

LP = on | HDV = on
<img width="765" alt="HDV-LP_lamp-design" src="https://github.com/mipops/dvrescue/assets/13877631/078463e2-8d9e-4b28-8d51-ce070697258f">

**Comment by dericed** [comment]
I like this idea. Let's do the SP/LP one first. First the question at https://github.com/mipops/dvrescue/issues/552#issuecomment-1843306954 would need an answer so we have a precise way to know if it's SP or LP.

**Comment by libbyhopfauf** [comment]
> I like this idea. Let's do the SP/LP one first. First the question at [#552 (comment)](https://github.com/mipops/dvrescue/issues/552#issuecomment-1843306954) would need an answer so we have a precise way to know if it's SP or LP.

@dericed I added links to a set of files to #552 (it's a set of tapes we did for an org that recorded them all on the same camcorder, some are LP and some are SP, I organized them accordingly in Google Drive). I wasn't sure where to look for the info you wanted though. Let me know and I can gather that data.

**Comment by libbyhopfauf** [comment]
@dericed all of the data for this has been added to this spreadsheet to track the ABST frame rates and I described my finding in #552 :)

Is HDV easier to detect since it has different encoding?

**Comment by dericed** [comment]
@libbyhopfauf did you ever add svg files for the LP lamp. Like an on or off?

**Comment by dericed** [comment]
@libbyhopfauf just a reminder that we need svg for `DV-SP` and `DV-LP`. I suggest we can add DVCam and DVCPro after more research.

**Comment by libbyhopfauf** [comment]
I just uploaded the SVGs as part of PR #880

**Comment by libbyhopfauf** [comment]
Closing since this is incorporated into the latest versions of the GUI :)
