### ISSUE TITLE
timestamp error in writing srt from dv captions

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#789]
Using this file as an example: https://makeinstallnotwar.org/video/Demo_DV_720x480_CC.mov

with
`dvrescue Demo_DV_720x480_CC.dv --cc-format srt -c OUTPUT.dv.srt`

every timestamp range starts and ends at the same timestamp: `00:01:18,912 --> 00:01:18,912`

With `dvrescue Demo_DV_720x480_CC.dv --cc-format scc -c OUTPUT.dv.scc` the timestamps seem accurate.
[dvrescue-captions.zip](https://github.com/mipops/dvrescue/files/13605743/dvrescue-captions.zip)

**Comment by dericed** [comment]
bump, another user emailed about this error. If hard to fix, let's remove the srt output option since it's not really usable.

**Comment by JeromeMartinez** [comment]
[snapshot](https://mediaarea.net/download/snapshots/binary/dvrescue/20240124/dvrescue_CLI_22.12.20240124_Mac.dmg).

**Comment by JaredGibsonAVF** [comment]
Snapshot was successful in fixing the SRT timestamps on the first file ive tested! Will continue to use and test but this seems resolved. Had to change .srt to .txt just for github to upload, but here's a successful SRT output. Deepest of gratitude.

[TEST1.dv.cc1.txt](https://github.com/mipops/dvrescue/files/14041418/TEST1.dv.cc1.txt)
