### ISSUE TITLE
distinguish frame speed icon between no frame and stopped frame

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#817]
1. here the deck is playing but not receiving frames and the frame speed icon shows "STOPPED" (black square)
<img width="693" alt="image" src="https://github.com/mipops/dvrescue/assets/762604/cf583b93-605a-4578-9349-4373a274eeb2">

2. Here the deck is stopped but dvrescue is receiving frames and the frame speed icon shows "STOPPED" (black square)
<img width="693" alt="image" src="https://github.com/mipops/dvrescue/assets/762604/67aa8dbe-27c6-4374-970e-15dbdd0f4f07">

I suggest to distinguish these. Leave the black stop from scenario two, but for scenario one let's have something else (when there's no frame and thus no frame speed). Maybe:
- a grey square
- a square that is just an outline

@libbyhopfauf any opinion? It would be good to make clearer that this icon is about what the received dv frames say is happening in regards to direction and speed.

**Comment by dericed** [comment]
I realize the frame speed icon is just representing the corresponding value of the csv. Could we distinguish these scenarios by adding an expiration time to the last received frame-speed value. Like the icon could show something only if the last csv value is less than one second old? That way no frames could be blank, but csv showing frame-speed=0 could be a black square (stop).

**Comment by libbyhopfauf** [comment]
I think the way you did this in the latest release is perfect! I'll add the new color coding and symbols to the documentation!
