### ISSUE TITLE
better handling of garbage in vaux dif blocks.

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#85]
[SEATTLETAPE_x.dv.zip](https://github.com/mipops/dvrescue/files/4603747/SEATTLETAPE_x.dv.zip)

This frame is recognized as having a caption at byte 96383.

In dseq=9 the vaux is:

```
5f8700d75900e3273050a752451a9da5969d459724eea035c1fcd8d95c77092de96db0465c1a7c1edbdec4aea9fc02174091bc2136bde43ac211b9c7c860a804ba4a87fbd1c683ac0239e7342accc706
5f87010f831e613e539e9717f0e3eaef7f59b0a2a4ec786992c52b7e5d0afe769aeb752e2368798c9816f34ced9edeed0bcd589a179390b34e1a93028246806540556ac28b340e805da90a5c3fd20cf4
508702ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff60ffff00ff610380fcff62ffffffff63ffffffffffffffffffffffffffffffff
```

The first two lines are wrong (maybe audio ¯\\_(ツ)_/¯), but the `6540556ac2` is recognized as a caption pack. However the caption pack is in the wrong position. I guess the position of the vaux packs may likely be irregularly so they should be understood when in the wrong position.

I suggest we test to validate vaux dif blocks before using their contents. Perhaps a check that the last two bytes equal `ffff`.

**Comment by JeromeMartinez** [comment]
> Perhaps a check that the last two bytes equal ffff.

If last two bytes are not FFFF, I discard the 80-byte block, right?
Should I indicate an error somewhere? Maybe a new kind of error "count of incoherent DIF blocks"?

**Comment by dericed** [comment]
From reading the spec I'm not sure how else to validate since it seems like even though vaux packs use ids in a narrow binary range that any could be defined. Still the last two bytes default to `ff`. 

From http://web.archive.org/web/20060927044735/http://www.smpte.org/smpte_store/standards/pdf/s314m.pdf
> There are 15 packs, each 5 bytes long, and two reserved bytes in each VAUX DIF block payload. A default value for the reserved byte is set to FFh.

**Comment by dericed** [comment]
This seems fixed in git master, but I'm not sure which commit fixed it. ping @JeromeMartinez

**Comment by JeromeMartinez** [comment]
Aimed to be fixed by https://github.com/MediaArea/MediaInfoLib/pull/1260, not yet merged so I didn't expect that it is fixed if you use MediaInfoLib git master.
