### ISSUE TITLE
add signalstats values to decklink capture xml and csv

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#857]
based off https://github.com/mipops/dvrescue/issues/767.

I'd like a few signalstats values in the xml, such as
```xml
<frame n="0" pos="0" pts="00:00:00.000000" tc="01:16:11:01" seqn="F">
   <signalstats satmax="900"/>
</frame>
```

Note that we'd need to add bitdepth to the `<frames>` element and to the csv output to contextualize the satmax value.

I'm open minded if these new filter values are as attributes or sub-elements.

**Comment by JeromeMartinez** [comment]
>  few signalstats values

Which ones?

**Comment by dericed** [comment]
So perhaps rather than use signalstats directly we could replicate it by doing our own math. If this is a good direction, let's start with SATMAX, SATHIGH, SATAVG, which is the highest, highest when excluding the top 10%, and the average value of 

```
b=bitdepth
sqrt( (U - 2^(b-1))^2 + (V - 2^(b-1))^2 )
```
