### ISSUE TITLE
planning for a dv capture buffer utility

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#86]
This issue is to start envisioning a utility to control and manage the output of avfctl. I'm imagining something like `avfctl -cmd capture - | dvbuffer out.dv` where dvbuffer collects frames from avfctl and if matching certain criteria then appends them to out.dv and if not, then depending on the assessment of the stream either warns the user or send an avfctl command to stop the capture, rewind briefly, and continue the capture so that dvbuffer can receive an alternate (up to x times) of the problematic time range, make a comparison and continues to append the best version of the frames to the output.

So for instance:
1. avfctl sends a minute of dv stream but a dropped frame occurs at 55 seconds (noticed because of a non-continuous timecode from 00:00:55;03 to 00:00:55;05)
2. dvbuffer writes up to 00:00:55;03 to out.dv
3. dvbuffer notices the gap and stops avfctl, then rewinds briefly, and sends the play command
4. dvbuffer monitors the frames coming from avfctl up to 00:00:55;03
5. if the subsequent frame is 00:00:55;04 then continue appending from that point to the output and discard the copy of 00:00:55;05 captured in part 1, else if the subsequent frame is not 00:00:55;04, then retry steps 3-5 up to x times (depending on a user setting)

At this point, dv buffer would help interact with avfctl in order to respond in time to dropped frames, but in subsequent development dv buffer should:

- provide metadata about the current frame read as an input (timecode, error summary, recording date, start flags) as well as metadata about the output (tally of duration, non-continuous timecode, attempted re-readings).
- be able to re-read portions of tape that contain error. For instance if frames are received with video error concealment or audio concealment over a certain threshold, then attempt a re-read, compare, and use the best known copy.

**Comment by kieranjol** [comment]
Woah, sounds like an incredible idea.

**Comment by dericed** [comment]
More planning on this from discussion with @JeromeMartinez 

- Accept input from:
  - ffmpeg -f dshow -i DV -c:v copy -map 0:v -rawvideo -
  - ffmpeg -f libiec61883 -i DV -c:v copy -map 0:v -rawvideo -
  - avfctl -device 0 -cmd capture -
  - a simulator taking a DV file in input + options for creating issues in the file

- Provide option for a status bar
  - tc=XX:XX:XX:XX rdt=YYYY-MM-DD HH:MM:SS:FF, total dur so far, format, aspect ratio, channel count, samp

- Keep x frames of input dv in buffer
- Write buffer to output dv file
  - option to start a new dv output file at certain events
    - break in recording timestamp
    - break in timecode
    - change in aspect ratio, audio channel count, format, sampling rate
- If buffer contains missing frames or errors, then send stop command, rewind the tape a little (need experiments for time), continue capture, merge first buffer and second buffer, output the merged result and continue
for deck control, it is avfctl on mac, dvcont on linux, or tbd on windows
  - options for how many retries and for the size of the buffer
  - option to drop some frames from buffer or merged result if they meet some conditions: 
    - like the frame is full conceal
    - if the frame is black/silence (like the deck is recording but there is no input), we need to collect more of these to determine a method to identify them.
- option to kill the input (from step 1) and end the dvrescue process if the tape is not sending data for x seconds (like often a tape has 1 min of content on a one hour tape.
  - option so that if data on tape ends, that we fast forward tape to seek more content, if more then stop and rewind and continue capture  (like if tape has 1 min of video, then one min unrecorded gap and then more dv)
- option to provide xml output along with the dv output

**Comment by privatezero** [comment]
this all sounds great!
