### ISSUE TITLE
analysis GUI blank until forced to generate new xml

### ISSUE THREAD

**Issue by arnicholson** [mipops/dvrescue#869]
In the batch of tapes I'm working on, when I drop them in the Analysis tab in the GUI, some are turning up totally blank, as in the below screenshot.

![original_xml](https://github.com/mipops/dvrescue/assets/123590485/b37b1399-72bc-4896-8a99-1ce9c7ea7ed4)

If I close dvrescue, remove the .xml file that is created during capture, and then re-open dvrescue and add the .dv file again, it will create a new .xml file. This takes a little bit of time, but then the file loads into Analysis successfully.

![new_xml](https://github.com/mipops/dvrescue/assets/123590485/093d9b4b-3c51-4c1b-b0fc-bc98117f55dc)

This does NOT happen with every file I'm processing. Maybe only 1/4 of them. 

Here is a google drive folder with the .dv file in question as well as the original .xml file and the newly generated .xml file, as well as a log, if that is helpful.
https://drive.google.com/drive/folders/1lqlZpR3NynIuIwlw75gj85BO4bz_XYRe?usp=sharing

dvrescue --version
DVRescue v.22.12.20240611 (MediaInfoLib v.24.05) by MIPoPS.
dvrescue --list_devices
0x80458280022265: Panasonic DV [DV]

Panasonic AG-DV2500
System: Mac mini (late 2014) running Monterey 12.7.3

**Comment by dericed** [comment]
Hey @arnicholson in this instance, do you have a before and after of the xml?

**Comment by arnicholson** [comment]
@dericed It seems github won't let me attach an xml file, but both before and after examples are in this google drive folder, which you should be able to access (but let me know if you can't for some reason): https://drive.google.com/drive/folders/1lqlZpR3NynIuIwlw75gj85BO4bz_XYRe?usp=drive_link

**Comment by libbyhopfauf** [comment]
I can confirm that this is still happening with the latest build, but it is inconsistent (sometimes the XML generated during capture contains information as expected and other times I have to delete it and regenerate it either with the GUI or using dvplay -x for the CLI).

**Comment by dericed** [comment]
Here's an example. The first xml works and the second doesn't. The presence of the `<stop>` element breaks the parsing in the analysis window.


```xml
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.2.1">
	<creator>
		<program>dvrescue</program>
		<version>22.12.20240720</version>
		<library version="24.06">MediaInfoLib</library>
	</creator>
	<media ref="/Users/drice/Movies/nowrewind.dv" fromCapture="device://0x8004601025d4bcb" format="DV">
		<stop method='timeout' extra='60'/>
		<frames count="2126" pts="00:00:00.000000" end_pts="00:05:03.703400" abst="30" end_abst="19485" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2">
			<frame n="0" pos="0" pts="00:00:00.000000" abst="30" tc="00:00:03;23" rdt="2005-01-01 00:56:36;27" seqn="F"/>
			<frame n="2125" pos="1092120000" pts="00:05:03.670033" abst="19485" tc="00:00:47;00" rdt="2005-01-01 00:57:20;06" seqn="F"/>
		</frames>
	</media>
</dvrescue>
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.2.1">
	<creator>
		<program>dvrescue</program>
		<version>22.12.20240720</version>
		<library version="24.06">MediaInfoLib</library>
	</creator>
	<media ref="/Users/drice/Movies/nowrewind.dv" fromCapture="device://0x8004601025d4bcb" format="DV">
		<frames count="2126" pts="00:00:00.000000" end_pts="00:05:03.703400" abst="30" end_abst="19485" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2">
			<frame n="0" pos="0" pts="00:00:00.000000" abst="30" tc="00:00:03;23" rdt="2005-01-01 00:56:36;27" seqn="F"/>
			<frame n="2125" pos="1092120000" pts="00:05:03.670033" abst="19485" tc="00:00:47;00" rdt="2005-01-01 00:57:20;06" seqn="F"/>
		</frames>
	</media>
</dvrescue>
```

**Comment by dericed** [comment]
fixed in https://github.com/mipops/dvrescue/pull/912
