### ISSUE TITLE
dvcapture: change "no signal" message

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#877]
Once a device is detected, the playback window currently says "no signal" which is confusing for some users. I propose we change that message to one of these options (depending on how much detail/instruction we want to provide):
- "Device Connected"
- "Device connected. Please use the buttons below to control the deck."
- "Device connected. Please use the deck control buttons below for playback and capture." (could add "review" or "repack" in there too to acknowledge FF/REW)

<img width="1040" alt="Screenshot 2024-06-19 at 12 05 31 PM" src="https://github.com/mipops/dvrescue/assets/13877631/c3f82bb3-a43d-4e19-8988-629c66a935fd">

<img width="766" alt="Screenshot 2024-06-19 at 12 07 11 PM" src="https://github.com/mipops/dvrescue/assets/13877631/8401988e-0fc8-4885-aaca-9fa777d2e89a">

One additional idea: If it's possible to detect if a tape is inserted or not, we could have the message say "Device Connected. Please insert a tape." if no tape is currently in the device. And then it could switch to one of the messages above.
<img width="786" alt="Screenshot 2024-06-19 at 12 07 50 PM" src="https://github.com/mipops/dvrescue/assets/13877631/2c7b2a0c-05aa-46bd-9784-3821b040d23a">

**Comment by dericed** [comment]
@g-maxime, I think this was feasible in sony9pin, but with the dv control protocol, can we sense if the deck is in local/remote mode? and if there is a tape loaded?

**Comment by dericed** [comment]
done in https://github.com/mipops/dvrescue/pull/911
