### ISSUE TITLE
add DV SP / DV LP icons

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#881]
From the `abst` value in the csv, deduce the difference between abst in frame n and frame n-1. Let's call that `ABST_DIFF`. I'd like an icon shown on the capture interface depending on the value of `ABST_DIFF`.

If ABST_DIFF = 5 (+/- 0.5), then show DVCPRO-lamp-lit.svg
If ABST_DIFF = 6.66 (+/- 0.5), then show DV-LP-lamp-lit.svg
If ABST_DIFF = 10  (+/- 0.5), then show DV-SP-lamp-lit.svg
If ABST_DIFF = 15  (+/- 0.5), then show DVCAM-lamp-lit.svg
else show nothing

Can we also reuse the same timer used for the frame-speed value in https://github.com/mipops/dvrescue/pull/830, so that the icon should only show if the ABST_DIFF value is very recent.

The icon can be placed to the left of the deck controls.

**Comment by libbyhopfauf** [comment]
@dericed sounds good to me! I also added in my research about detecting DVCAM and DVCPRO to #552 :)

**Comment by dericed** [comment]
@libbyhopfauf, thx i updated the original comment
