### ISSUE TITLE
add abst and abst_end to <frames> element

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#885]
If easy, this would let us deduce the DV Type (dvcam, dvcpro, dv sp, dv lp) of the sequence of frames more consistently.

**Comment by g-maxime** [comment]
Fixed by #887

**Comment by libbyhopfauf** [comment]
I'm going to close this since the labels show up for DVCAM, DVCPRO, SP and LP in the GUI now (YAY!) Please reopen if I misunderstood and this was a different part of that feature!!
