### ISSUE TITLE
dvrescue GUI: rewind and recapture not working

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#891]
@dericed For the rewind/recapture setting in the dvrescue GUI, even though I have entered the number of times I would like dvrescue to rewind and recapture when an error is encountered (in this case 4), it doesn't seem to be doing this even when it encounters an error. Is this feature still only available via the CLI?
<img width="604" alt="Screenshot 2024-07-22 at 11 50 44 AM" src="https://github.com/user-attachments/assets/0bce292f-d93c-47c3-a8f5-d9ae19cb657f">

**Comment by dericed** [comment]
It's related to https://github.com/mipops/dvrescue/issues/914. but also can you retry now that the log option is removed.
