### ISSUE TITLE
Windows: errors logged while viewing DV DIF block data during analysis: $'\r': command not found

### ISSUE THREAD

**Issue by JohnstonJ** [mipops/dvrescue#925]
Steps to reproduce:

1. Analyze a DV file on Windows.
2. Click a frame number in the list of frames with errors.
3. The image will appear in the pop-up, but the "Show DV DIF block types" buttons don't seem to do anything, and the bottom half of the window remains blank.  Additionally, a bunch of errors are logged.

This is with the latest nightly build from https://old.mediaarea.net/download/snapshots/binary/dvrescue-gui/20240730-2/dvrescue_GUI_22.12.20240730_Windows_x64.zip

![image](https://github.com/user-attachments/assets/c0c7f9b8-9264-474b-bfc7-d70579a91b9e)

```

C:/Users/JOHNST~1/AppData/Local/Temp/mpout/Software/dvrescue_GUI_22.12.20240730_Windows_x64/cygwin/bin/bash.exe C:/Users/JOHNST~1/AppData/Local/Temp/mpout/Software/dvrescue_GUI_22.12.20240730_Windows_x64/tools/dvloupe -M /cygdrive/c/Users/JOHNST~1/AppData/Local/Temp/mpout/Software/dvrescue_GUI_22.12.20240730_Windows_x64/scripts/mediainfo.sh -x /cygdrive/c/Users/JOHNST~1/AppData/Local/Temp/mpout/Software/dvrescue_GUI_22.12.20240730_Windows_x64/scripts/xml.sh -F /cygdrive/c/Users/JOHNST~1/AppData/Local/Temp/mpout/Software/dvrescue_GUI_22.12.20240730_Windows_x64/scripts/ffmpeg.sh -i C:/VideoProject/Johnston3/Johnston3-pass1.dv -b 7680000 -f json -T n


/cygdrive/c/Users/JOHNST~1/AppData/Local/Temp/mpout/Software/dvrescue_GUI_22.12.20240730_Windows_x64/scripts/mediainfo.sh: line 2: $'\r': command not found
/cygdrive/c/Users/JOHNST~1/AppData/Local/Temp/mpout/Software/dvrescue_GUI_22.12.20240730_Windows_x64/scripts/mediainfo.sh: line 3: $'\r': command not found
/cygdrive/c/Users/JOHNST~1/AppData/Local/Temp/mpout/Software/dvrescue_GUI_22.12.20240730_Windows_x64/scripts/mediainfo.sh: line 5: $'\r': command not found
/cygdrive/c/Users/JOHNST~1/AppData/Local/Temp/mpout/Software/dvrescue_GUI_22.12.20240730_Windows_x64/scripts/mediainfo.sh: line 7: $'\r': command not found
/cygdrive/c/Users/JOHNST~1/AppData/Local/Temp/mpout/Software/dvrescue_GUI_22.12.20240730_Windows_x64/scripts/mediainfo.sh: line 8: $'\r': command not found
/cygdrive/c/Users/JOHNST~1/AppData/Local/Temp/mpout/Software/dvrescue_GUI_22.12.20240730_Windows_x64/scripts/mediainfo.sh: line 11: $'\r': command not found
/cygdrive/c/Users/JOHNST~1/AppData/Local/Temp/mpout/Software/dvrescue_GUI_22.12.20240730_Windows_x64/scripts/mediainfo.sh: line 35: syntax error: unexpected end of file
[31mC:/VideoProject/Johnston3/Johnston3-pass1.dv does not seem to be a dv file, but is .(B[m




SyntaxError: JSON.parse: Parse error

```

**Comment by dericed** [comment]
Hi @JohnstonJ, thanks can you test https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20240731/ which includes @g-maxime's fix in https://github.com/mipops/dvrescue/pull/926

**Comment by JohnstonJ** [comment]
@dericed that snapshot build is working much better for this feature!  I was able to show all the different DV DIF blocks.  I did not see any errors logged in the Debug window while I used it.

I'm assuming this screenshot is what I should be seeing:

![image](https://github.com/user-attachments/assets/a66cbd08-cca4-4f95-8274-17a9926d9149)

**Comment by dericed** [comment]
Hi @JohnstonJ could you test this issue with https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20240731/. Hopefully it fixes this.

**Comment by JohnstonJ** [comment]
@dericed as noted in https://github.com/mipops/dvrescue/issues/925#issuecomment-2264219236 -- the snapshot build you linked to works!  Looking forward to #926 being merged so I can use future DVRescue builds on Windows.  In the meantime, over the past few weeks, I've been using that specific snapshot build you linked to.
