### ISSUE TITLE
detail the non-continuity in rdt_nc and tc_nc

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#94]
Currently, a non-continuous timecode or recording timestamp value produces an attribute value of 1.

I suggest expanding this from a boolean to an integer to express the following.
0: pattern is continuous (do not write the attribute in this case)
1: pattern is non-continuous and the current value > prev value
2: pattern is non-continuous and the current value < prev value
3: pattern is non-continuous and the current value = prev value

**Comment by JeromeMartinez** [comment]
> 3: pattern is non-continuous and the current value = prev value

this one is rdt_r and tc_r, it is not handled as non-continuity for the moment.
So this case is not possible.

I add the case of "2", checking the sign of the difference.

**Comment by dericed** [comment]
Sounds good to me.

**Comment by dericed** [comment]
nudge nudge :)

**Comment by dericed** [comment]
nudge nudge :) nudge nudge :) @JeromeMartinez :-D

**Comment by dericed** [comment]
reopening with https://github.com/mipops/dvrescue/pull/340#issuecomment-955574373
