### ISSUE TITLE
DVRescue install error when installing vrecord

### ISSUE THREAD

**Issue by timlake23** [mipops/dvrescue#942]
Hi all,

I've been trying to test new vrecord features, requiring that I upgrade my old vrecord version. I was initially met with issues stemming from an outdated OS, so I updated to Sequoia 15.0. The vrecord intall is showing an error related to DVRescue:

"Last 15 lines from /Users/bavcpreservation/Library/Logs/Homebrew/dvrescue/02.make:
1 error generated.
1 error generated.
...
make: *** [../../../SourceZenLib/Format/Http/Http_Utils.lo] Error 1
make: *** [../../../SourceZenLib/Format/Http/Http_Cookies.lo] Error 1
make: *** [../../../SourceZenLib/Format/Http/Http_Request.lo] Error 1
make: *** [../../../SourceZenLib/Format/Http/Html_Request.lo] Error 1
make: *** [../../../SourceZenLib/Format/Http/Http_Handler.lo] Error 1
make: *** [../../../SourceZenLib/Format/Http/Html_Handler.lo] Error 1 

Is this related to upgrading to Sequoia?
Should I try Sonoma and see if that resolves?

Thanks!

**Comment by dericed** [comment]
Ping @JeromeMartinez

**Comment by g-maxime** [comment]
Can you share the file content for
/Users/bavcpreservation/Library/Logs/Homebrew/dvrescue/02.make
and
/Users/bavcpreservation/Library/Logs/Homebrew/dvrescue/02.make.cc
?

**Comment by timlake23** [comment]
[02.make.txt](https://github.com/user-attachments/files/17248508/02.make.txt)
[02.make.cc.txt](https://github.com/user-attachments/files/17248509/02.make.cc.txt)

I'm not sure if these are helpful to view, I'm new to sharing code in github. Let me know if there's a better way.

**Comment by libbyhopfauf** [comment]
@timlake23 heyy!!! would you mind installing these snapshots and see if they resolve the issue for you?

CLI: https://mediaarea.net/download/snapshots/binary/dvrescue/20241026/dvrescue_CLI_24.07.20241026_Mac.dmg
GUI: https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20241026/dvrescue_GUI_24.07.20241026_Mac.dmg

If this version doesn't work, will you please take the following steps and share the results here?

- Make sure that the version of the DVRescue GUI you are using is installed in the Applications folder.
- Connect a DV deck/camcorder attached and in remote mode, with a tape inserted, and that the tape has content on it (i.e. that there is something to capture).
- Open the Terminal.app and launch DVRescue by running this command: /Applications/dvrescue.app/Contents/MacOS/dvrescue --log.
- Go to the capture tab, and wait for the deck to be recognized.
- Click play in the GUI. If the video does not play within a few seconds, then quit DVRescue.
- If the video does play, start a recording. If the recording doesn't start, then quit DVRescue (click the x at the top of the application window).
- Go back to Terminal and run this command cat ~/Library/Containers/net.MediaArea.dvrescue.mac-gui/Data/dvrescue-gui_logs/dvrescue-gui.log
- Copy the log that pops up and paste it into https://gist.github.com/ and save it.
- Add the link to this thread so it can be reviewed for possible troubleshooting.
