### ISSUE TITLE
dvcapture GUI: sped up recordings

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#944]
It seems unclear if this issue has to do with a specific build or if it's being caused by macOS updates. All builds  tested (2024-09-09 to currently) produce the same results on all decks tested. Playback appears normal during capture, but the resulting file is playing at 2x speed (even though it is actually playing at 1x speed during capture). Packaging is not effect (files produced are usually just random segments from the beginning of the tapes). For both of the computers this was tested on (specs below), I was able to transfer the same tapes using QuickTime and the resulting files were at normal speed. What is really strange though is that some of these versions were working fine before, but fresh installs of them produce the same sped up results. Test files are available [here](https://drive.google.com/drive/folders/1ofKCpzMo9BfYTgcR4kQGzjgRdaEQucM4?usp=sharing). 

**Computer 1**
- Macbook Pro, 2021, M1 Pro chip
- macOS Ventura 13.6.1
- dvrescue versions tested = 2024-10-19, 2024-09-09, 2024-09-21

**Computer 2** 
- Macbook Pro, 2022, M2 Max chip
- macOS Sonoma 14.4
- dvrescue versions tested = 2024-10-19, 2024-09-09, 2024-09-21

However, using version 2024-07-31 of the GUI on an old Mac Mini (see specs below) is working great! I'm able to use deck control to capture DVCPRO tapes from a DSR-1500A and regular MiniDVs from a DSR-45.

- Mac mini (late 2012)
- macOS Catalina version 10.15.7 
- dvrescue version 2024-07-31

**Comment by g-maxime** [comment]
From my tests:
- CLI from the repository: works
- GUI from the repository: 2x speed
- CLI with my control code: 2x speed

I'll look into the issue now; it might be a thread synchronization issue in some cases...

**Comment by g-maxime** [comment]
You can try this snapshot:
CLI: https://mediaarea.net/download/snapshots/binary/dvrescue/20241026/dvrescue_CLI_24.07.20241026_Mac.dmg
GUI: https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20241026/dvrescue_GUI_24.07.20241026_Mac.dmg

**Comment by libbyhopfauf** [comment]
Yep! This resolved it! Thank you!
