### ISSUE TITLE
Not getting preview from Digital-8 decks on Capture or Play

### ISSUE THREAD

**Issue by scottgravlee** [mipops/dvrescue#951]
I'm using a GV-D800. The tapes I'm currently working on are Hi8, but Digital-8 tapes do the same thing. I'm not getting any preview and have inconsistent capture. Full deck control is working, and sometimes it will capture, but a lot of the time, it will not — all with no preview. This is after I have stopped it after running a tape for a few seconds. When it does, it's like the data just rushes in, but that may be it just writing the file; not sure. If I leave the tape running, I get zero KB files.

I have tried the latest version and the nightly build from the second of this month. It tells me "No Signal," and with the latest build, "Device Connected" and says "sending record" with both and then appears to then switch to "playing." Is there a place for older versions I can download and try? I could not find a link to older builds.

The computer is a 3.6 GHz i3 2018 Mac Mini running Ventura. I've already set all the security permissions, and I'm able to see my Mini-DV decks, including a similar model GV-D1000, and capture in DV Rescue. I can see video in Quicktime Player from the D800.

I have attached screenshots and can provide any logs that may be helpful. I'm going to try on a different computer but getting this one working is optimal.   
 
![Screenshot 2024-11-07 at 11 49 27 AM](https://github.com/user-attachments/assets/0eff093e-06c6-4586-ac68-fd1b3c6c28e0)

![Screenshot 2024-11-07 at 11 56 43 AM](https://github.com/user-attachments/assets/880e73d9-6f42-4cf6-99ce-3bae0bc3a6b4)

![Screenshot 2024-11-07 at 11 59 59 AM](https://github.com/user-attachments/assets/529d38d0-899c-42fc-9390-9fc9a5b54c70)

![Screenshot 2024-11-07 at 11 59 41 AM](https://github.com/user-attachments/assets/91137a50-5182-464d-b8ee-b719aec1ee79)

**Comment by libbyhopfauf** [comment]
This seems to be the same issue as #944 which was resolved for me when I tried the snapshots from 10/26. @scottgravlee would you mind installing these snapshots and see if they resolve the issue for you? 

- CLI: https://mediaarea.net/download/snapshots/binary/dvrescue/20241026/dvrescue_CLI_24.07.20241026_Mac.dmg
- GUI: https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20241026/dvrescue_GUI_24.07.20241026_Mac.dmg

If this version don't work, will you please take the following steps and share the results here?

1. Make sure that the version of the DVRescue GUI you are using is installed in the Applications folder. 
2. Connect a DV/Digital8 deck/camcorder attached and in remote mode, with a tape inserted, and that the tape has content on it (i.e. that there is something to capture).
3. Open the Terminal.app and launch DVRescue by running this command: `/Applications/dvrescue.app/Contents/MacOS/dvrescue --log`.
4. Go to the capture tab, and wait for the deck to be recognized.
5. Click play in the GUI. If the video does not play within a few seconds, then quit DVRescue.
6. If the video does play, start a recording. If the recording doesn't start, then quit DVRescue (click the x at the top of the application window).
7. Go back to Terminal and run this command `cat ~/Library/Containers/net.MediaArea.dvrescue.mac-gui/Data/dvrescue-gui_logs/dvrescue-gui.log`
8. Copy the log that pops up and paste it into https://gist.github.com/ and save it.
9. Add the link to this thread so it can be reviewed for possible troubleshooting.

**Comment by libbyhopfauf** [comment]
Also for reference, I was previously having the same issue with DVRescue, but the snapshots linked about work for me on these computers:

- Macbook Pro, 2022, M2 Max chip (macOS Sonoma 14.4)
- Mac Mini, 2020, M1 chip (macOS Sequoia 15.1)

**Comment by scottgravlee** [comment]
I ran the first command, and I'm now getting a preview and am able to record from a Digital-8 tape. It prompted me to allow it to use my camera, which I'd already set in system settings. It also complained about not having a font for some reason. I downloaded that and reran the command, and that's when I started getting Digital-8 playback with preview. But, importantly, I'm not getting the Hi-8 tapes to transfer. I assumed these tapes would also be able to be transferred with this program.

I have attached a log file (hopefully I did things correctly when generating it)."
[https://gist.github.com/scottgravlee/48d6f711c8426c1d79b706d3d1d2661f](url)


On a side note I've had nothing but trouble getting DV-Rescue to work with  Sonoma 14.4 I may have to try that again.

**Comment by scottgravlee** [comment]
Update of sorts I ran that first command `/Applications/dvrescue.app/Contents/MacOS/dvrescue --log` on my M1 MacBook Pro running Sonoma and I now am seeing DV decks including the GV-D800 but I'm still not getting any preview from Hi-8 tapes. I also just tried the version linked. All other tapes work are analog tapes not supported? The website doesn't explicitly say no. I may need to try other software.

**Comment by scottgravlee** [comment]
Maybe this will help narrow down my issue: I installed vrecord and I am getting a similar issue where the preview of HI8 tapes rushes in after stopping. I was able to capture a short section of tape, which is in the first screenshot. The preview window only popped up after stopping the tape, and the record button in vrecord is greyed out in the GUI.

It seems it's delayed in getting data from the tape, possibly because when you start a HI-8 tape, the deck has to switch to analog mode and that takes a few seconds. If you let the tape run for a long enough time, it will not write anything because some buffer might be filling up. Maybe there needs to be something in DVRescue to detect when the deck is switching into analog mode and make note of that. But also, it could be that the time difference doesn't matter and the record commands are no different.


![Screenshot 2024-11-10 at 5 06 05 PM](https://github.com/user-attachments/assets/f92c0471-75b0-49db-b30b-c7630163a521)
![Screenshot 2024-11-10 at 5 10 56 PM](https://github.com/user-attachments/assets/1d69cabe-0171-4551-b2b1-8d380d62f5e1)
![Screenshot 2024-11-10 at 5 05 44 PM](https://github.com/user-attachments/assets/3a8085eb-e800-4d9a-b4a4-e85e9fff3e54)

I've tried DVrescue on my windows 10 laptop (was not able to see any DV devices could be an intel thunderbolt issue did not investigate further but need to)

M1 MacBook pro (same issue)

2018 MacMini  (same issue)

**Comment by scottgravlee** [comment]
Doing more testing I was able to fully transfer a tape through vrecord leaving a tape running overnight during this time I got no preview (not sure about when the tape stopped) Everything is staying at zero like in the screen shots. This looks like a partial path forward. I have yet to try the CLI version of DVRescue

**Comment by libbyhopfauf** [comment]
> I've tried DVrescue on my windows 10 laptop (was not able to see any DV devices could be an intel thunderbolt issue did not investigate further but need to)
> 

@scottgravlee Unfortunately, the Windows version of the software is only compatible for the analysis, merge and package functions for the DVRescue GUI. The Windows/Linux version [requires different background tools for that OS](https://docs.google.com/document/d/1zTqIBF-FyKaynIBgYfpBiRmOq5rkbv0S89Uy2p5YsrQ/edit#heading=h.qzakjnqnavln) and you might need to check the [Ubuntu permissions](https://github.com/mipops/dvrescue/issues/514). We're working on it though. The software is likely not recognizing your DV device because you need to have a Firewire card installed on your Windows or Linux computer. The tool being used for the Windows/Linux version doesn't communicate with adapters. Here's [an example of the set-up you need for a Windows computer](https://youtu.be/7FaZw3RoVbA?si=Ojvvk-08LRMloNmx&t=555) to capture DV videotape formats.

This will not resolve your current issue of attempting to capture analog tapes with the software. vrecord can be used with macOS and [Linux](https://github.com/amiaopensource/vrecord/blob/main/Resources/Documentation/linux_installation.md), but you will still need to have a Blackmagic capture device connected for analog videotapes.

**Comment by scottgravlee** [comment]
Ah ok good info. I have been able to transfer with some success HI8 tapes using a GV-D800 which is backwards compatible with HI8 and Video-8 so it's at-least possible somewhat. it just doesn't appear to like the deck switching to analog mode for conversion to digital.  

The reason for me going over DV is i've had better results with these two formats going out of the deck into my DPS-575 lead to a bunch of noise in the audio.

**Comment by scottgravlee** [comment]
> > Update of sorts I ran that first command `/Applications/dvrescue.app/Contents/MacOS/dvrescue --log` on my M1 MacBook Pro running Sonoma and I now am seeing DV decks including the GV-D800 but I'm still not getting any preview from Hi-8 tapes. I also just tried the version linked. All other tapes work are analog tapes not supported? The website doesn't explicitly say no. I may need to try other software.
> 
> @scottgravlee the DVRescue software is just for [DV videotape formats](https://mipops.github.io/dvrescue/sections/dv_formats.html). Via a Firewire connection, you can transfer any DV formats (MiniDV, DVCAM, DVCPRO, and Digital8), but it's not intended for transferring non-DV analog videotape formats. You should be able to use vrecord for other analog videotape formats, but you will need to use a [Blackmagic capture card](https://github.com/amiaopensource/vrecord/blob/main/Resources/Documentation/hardware.md) and will need to connect the deck to your TBC and capture card using the corresponding analog cables (varies by format).
> 
> Are you still encountering these issues for Digital8 tapes? It sounded like you were about to resolve the communication errors for that, but let us know if you're still having issues.

Yes I got digital-8 working

**Comment by libbyhopfauf** [comment]
> Ah ok good info. I have been able to transfer with some success HI8 tapes using a GV-D800 which is backwards compatible with HI8 and Video-8 so it's at-least possible somewhat. it just doesn't appear to like the deck switching to analog mode for conversion to digital.

@dericed can correct me if I am wrong, but I believe that the software isn't able to process the analog signal via the Firewire connection. But I am really curious being able to transfer Hi8 tapes this way. Was this using vrecord? Were there any issues with the resulting files?

> The reason for me going over DV is i've had better results with these two formats going out of the deck into my DPS-575 lead to a bunch of noise in the audio.

Interesting! Does this happen if you connect the camcorder you are using to the DPS? Do you have audio cards installed in the DPS?

**Comment by scottgravlee** [comment]
Yes I have the audio cards installed the GV-D800 is a nice unit when it works ![Sony-GV-D800-_2](https://github.com/user-attachments/assets/8f905d30-5937-47c6-ad32-106bc3ea2241)

And I can partly get hi8 to transfer with dvrescue GUI if I play a tape and then stop it after a few minutes and with vrecord I was able to transfer a whole tape but the last two I tried gave me this error. 
![Screenshot 2024-11-11 at 4 01 33 PM](https://github.com/user-attachments/assets/d5e2639a-4f67-45ab-9c5c-42fa6f9d17c6)

I'm also just noticing I get no audio so this seems like a lost cause wasn't a complete loss vrecord is going to entirely replace me using Media Express. I'll have to try the DPS unit again maybe my audio cables needed replacing. That is probably the best way to archive these anyway. 

I saw somewhere where y'all are working on Digital-Betacam if you got the analog over digital working this could possibly be good for archiving analog betacam over DV. 

Thanks for the help.

**Comment by libbyhopfauf** [comment]
Like I mentioned previously, for vrecord, analog videotapes need to be hooked up via analog cables, routed through a TBC and connected to a Backmagic device (just like how you would for using Media Express), so that's not too surprising that the file was missing audio. I was just surprised it captured anything at all! It's definitely the archival best practice. But let us know if you run into any other issues with DVRescue when transferring Digital8 and DV tapes. 

For the Digital Video Commander project, we're working to capture information about tapes using deck control, but will be able to capture the data stream for other analog-digital formats like Digital Betacam and use that information for diagonistics, quality control and facilitate more complete captures. The encoding for these tapes is different from the DV format, so we won't be using Firewire, but a combination of SDI and a custom cable. Since analog Betacam doesn't have a data stream, the capture of that format won't be able to be facilitated the same way, but any deck that has a 9-pin remote connection will definitely be able to be controlled using the Digital Video Commander cable (for play, FF, REW, stop and eject).

**Comment by scottgravlee** [comment]
Thanks for the info and all the work y'all do. I'm going to do further testing with the more proper setup.
