### ISSUE TITLE
DVRescue crashing when merging files

### ISSUE THREAD

**Issue by BrendanReidy** [mipops/dvrescue#952]
I'm running os15.0.1 with the latest gui install. Seeing DVRescue crash before Summary is produced and often before the file is fully output.
![Screenshot 2024-11-13 at 12 54 16 PM](https://github.com/user-attachments/assets/f7913297-8833-473e-b982-4317508512c1)

**Comment by libbyhopfauf** [comment]
This seems to be the same problem as described in issue #930. I'm going to reference this in that issue so that troubleshooting can be consolidated.
